ministryofjustice/opg-digideps

client/src/AppBundle/Service/File/Scanner/ClamFileScanner.php, client/tests/phpunit/Service/File/Scanner/ClamFileScannerTest.php
Ensure the UX is adequate in the case of a failed scan, and prevent the unnecessary critical alert.
Fixes [DDPB-3179](https://opgtransform.atlassian.net/browse/DDPB-3179)
The UX is handled reasonably gracefully as the error is caught and a message to retry is displayed to the user, which usually resolves the issue first time.
The log that we write to manually has been downgraded to an `error` status to prevent firing off a critical alert. There is no sign that previous occurrences have not been more or less instantly recoverable by a retry, so it feels reasonable to downgrade the error level. If we ever have a persistent outage, we can look at setting up a separate alert that monitors the success rate of scanner requests within an hour, to help capture it earlier.
=> DDPB 3179: Silence unnecessary scanner alerts

.circleci/config.yml, docs/AWS-DB-ACCESS.md, environment/api_sg.tf, environment/terraform.tfvars.json, environment/variables.tf, shared/cloud9.tf, shared/outputs.tf
Adding a single shared account level cloud9 means we can reduce the number of resources on our account (and associated costs) while locking down the security for RDS <--> cloud9.
Fixes DDPB-3031
This was a bit of a pain to get set up as we need to apply the security group automatically generated when creating a cloud9 environment to each environments RDS instance. We didn't have a mechanism to get the id of the account level cloud9 instance from `shared` to `environment` and terraform doesn't provide a data source for cloud9 instances. Instead, I've output the id of the cloud9 instance created during the `shared` which is then available in the tfstate file. We then access this state file remotely in S3 using a `terraform_remote_state` data source to access and assign the security group …
=> DDPB-3031 - Add account level cloud9 instance

environment/admin_elasticache.tf, environment/api_elasticache.tf, environment/dns_private.tf, environment/front_elasticache.tf
Initial part in 3 stage process to release DDPB-3192. 
Fixes DDPB-3192
Create the initial replication groups alongside the original cluster to test a switchover.
Full description in main PR: https://github.com/ministryofjustice/opg-digideps/pull/233
See main DDPB-3192 and https://github.com/ministryofjustice/opg-digideps/pull/233
=> ddpb-3224 add replication group without dns switch

environment/cleanup.tf, shared/events.tf, shared/sns.tf
Using GitHub as source for Slack terraform module to fix the path bug referenced [here](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/issues/21#issuecomment-565092931).
=> Prefer github source for slack module to fix path bug

environment/api_sg.tf
As some fallout from 3031, a security group rule that was used by cloud9 was actually allowing the restore of the database from prod into preprod. Since the rules were tightened up this failed to work as there was a rule missing.
Fixes DDPB-3031
Looked in console for the correct ingress rule and saw it was missing.
Learned that this doesn't work cross account. Prod backups to s3 then a separate process restores from that s3 bucket into the preprod env.
=> ddpb-3031 add missing sg rule for restore from prod

environment/admin_elasticache.tf, environment/api_elasticache.tf, environment/dns_private.tf, environment/front_elasticache.tf, environment/terraform.tfvars.json, environment/variables.tf
Create only 1 additional read node per ECS cluster for Front, Admin and API in production only (due to cost) in a different availability zone.
Fixes DDPB-3192
My initial approach was to try and add non clustered read replicas managed by terraform through this resource: aws_elasticache_replication_group and adding the replicas as stated here https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html. However after trying every combination and a lot of google searching, I wasn't able to get just two nodes with terraform managing the redis nodes so I had to let the aws_elasticache_replication_group manage it directly. For testing I used cloud9 with it's security group added to the redis sg allow list to use the redis-cli to set some values on redis, then fail over the …
=> ddpb-3192 remove old elasticache cluster

environment/api_rds.tf, shared/rds.tf
We were previously creating a role per environment, but getting a resource conflict because they have the same name. We only need one role per account, so I've moved it to shared.
=> Move enhanced monitoring role into shared

client/src/AppBundle/Form/Admin/ReportChecklistType.php
Question L7.2 is not relevant to 103 reports as accounts cannot be balanced. It should be removed for the 103 checklists of lay and PA clients (already done for professionals) 
Fixes DDPB-3195
I made the question dependent on the report having a balacing section, rather than muddling with report types again.
- N/A
- N/A, there's no real abstraction here
=> DDPB-3195: Remove L7.2 questions from 103 report checklists

client/src/AppBundle/Controller/UserController.php
This code should be unreachable, but is sometimes called (presumably because of the dual authorization providers). Rather than throwing a critical exception, just show an error message to the user.
Fixes DDPB-3250
I caught the exception and showed a user-friendly error message instead. This will prompt the user to fix the problem (by sending a new activation email) and not alert the service team.
Also fixed a few PHPStan issues.
- N/A
- N/A, since we don't know the exact circumstances under which this occurs. We could mock out the API to provide a contradictory response, but it would be a lot of work for something that we're guessing at.
- N/A
=> DDPB-3250: Prevent auth error from tripping alarm

environment/api_rds.tf, shared/lambda.tf, shared/sns.tf
In #252 we added a retention period to our manually-created log groups. However, we also have a few log groups which are automatically created by AWS with no retention period.
We need to bring these log groups under our control and give them suitable retention periods.
Fixes DDPB-3252
For the RDS cluster, I created a log group with the anticipated name and made it a dependency of the lambda (to ensure it's created first). I did this in all environments even though they're not all using clustered databases yet, so we're settled for the future.
I did the same for the redeployer lambda, but also removed the `logs:CreateLogGroup` permission since it's no longer necessary. I reduced the time to 14 days, which is still longer than we _really_ need.
For the slack notification lambda, I just set …
=> DDPB-3252: Add retention period to automatically-created log groups

.circleci/config.yml, api/app/DoctrineMigrations/Version231.php, api/composer.json, api/composer.lock, api/phpstan.neon, api/src/AppBundle/Entity/Report/Document.php, api/src/AppBundle/Entity/Report/ReportSubmission.php, client/composer.json, client/composer.lock, client/phpstan.neon, client/src/AppBundle/Entity/Report/Document.php, client/src/AppBundle/Entity/Report/ReportSubmission.php, client/src/AppBundle/Resources/translations/validators.en.yml, client/src/AppBundle/Resources/views/FlashMessages/missing-documents.html.twig, client/tests/phpunit/Service/DocumentDownloaderTest.php, client/tests/phpunit/Service/DocumentServiceTest.php
When we integrate with the API, we will automatically send documents to Sirius so that users don’t have to. However, users need to be aware of any failures or delay in the integration. Therefore, we will log which documents/submissions have been synchronised, which are queued, and which have failed.
Fixes DDPB-3237
I've added the new fields to the Document model, and also a new `uuid` field for ReportSubmission, which we'll need for making subsequent API requests to Sirius.
I also wanted to do PHPStan properly in this ticket, so I upgraded it in both API and client, and added phpstan-prophecy on the client (with our current tests it isn't needed on API). The rest of the work was tidying up based on PHPStan's feedback. Most significantly, I retyped a bunch of variables in unit tests.
The …
=> DDPB-3237: Add "synchronised" status and time to document model

.circleci/config.yml, client/app/config/config_dev.yml, client/app/config/config_test.yml, client/app/config/config_unittest.yml, client/app/config/services_mail.yml, client/src/AppBundle/Controller/Admin/IndexController.php, client/src/AppBundle/Controller/Org/OrganisationController.php, client/src/AppBundle/Controller/UserController.php, client/src/AppBundle/Service/Mailer/MailSenderInterface.php, client/tests/phpunit/Controller/AbstractControllerTestCase.php, client/tests/phpunit/Controller/AdminIndexControllerTest.php, client/tests/phpunit/Controller/ManageControllerTest.php, client/tests/phpunit/Controller/OrganisationControllerTest.php, client/tests/phpunit/Controller/UserControllerTest.php, client/tests/phpunit/Resources/views/Components/PaginatorTest.php, client/tests/phpunit/Resources/views/Report/FormattedTest.php
In the process of switching to Notify, we’ve stopped checking email sending in our end-to-end tests. Instead, we should write unit tests for the relevant controllers to ensure emails are being sent as expected.
This is particularly essential for our activation and password reset emails, since they are critical for users to access DigiDeps. Unlike other emails, there is no work around and they permanently break the user journey.
We are prioritising writing these tests to give a clear plan of  how we can increase coverage to other controllers/emails.
Fixes DDPB-3264
I went around most ways of writing unit tests and mocking things in Symfony, and settled on a method that I think works quite smoothly and is ripe for extending.
It uses Symfony's `createClient` function to create a driver for …
=> DDPB-3264: Write unit tests for activation/reset emails

client/src/AppBundle/Resources/translations/admin-checklist.en.yml, client/src/AppBundle/Resources/views/Admin/Client/Report/fullReviewChecklist.html.twig
Offer an option with the wording "I have closed the Review but further case work/actions are required" in the full review decision question.
Fixes DDPB-3241
As it happens, there is already an option which reads "Further case work/actions". This text just needs rewording, to make the intent of that option more clear, as opposed to adding a new option.
=> DDPB-3241: Updates wording of full review outcome option

client/src/AppBundle/Controller/Admin/Client/ReportController.php, docs/architecture/decisions/0003-use-aws-parameter-store-for-feature-flags.md, environment/api_rds.tf
Some fixes identified over the past few days that don't have a naturaly home
- Renaming a Terraform resource because I copy-pasted it and it doesn't make sense
- This doesn't need a state move since it isn't currently used outside of dev environments: delete & create is fine
- Ensuring a redirect is returned to the browser properly
- Adding an ADR for feature flags
- Should have done this in DDPB-3258, but still getting used to adding ADRs 🤦‍♂
=> A few small fixes

client/Dockerfile, client/package-lock.json, client/package.json
There are a few audit vulnerabilities in our JavaScript dependencies. We should perform updates to fix them.
We should remove `sass-lint` as it contains vulnerabilities, relies on unsupported dependencies, and provides little value.
Fixes DDPB-3282
I updated the vulnerabilities using `npm audit fix`, uninstalled and removed calls to `sass-lint`, and re-enabled `npm audit` in the pipeline.
- N/A
- N/A
- N/A
=> DDPB-3282: Fix npm audit vulnerabilities

client/Dockerfile, environment/api_rds.tf
Our serverless databases auto pause after 5 minutes, which impedes testing because cross-referencing a particular result often takes longer than that. We should increase it to 15 minutes to give people a little more time before being timed out.
Fixes DDPB-3275
I upped the auto pause timeout to 15 minutes.
This will cost us slightly more (because we have to pay for 10 minutes more of DB ACUs each time), but we're talking about thruppence which seems like a fair price for a bit more breathing room.
- N/A
-  N/A
-  N/A
=> DDPB-3275: Set serverless auto pause timeout to 15 minutes

api/tests/AppBundle/ControllerReport/ReportSubmissionControllerTest.php, client/Dockerfile, client/package-lock.json, client/package.json
There's been a new release to the GOV.UK Design System, bringing it to version v3.6.0.
This includes a fix to secondary text colour, improving contrast. It also adds a govuk-width-container mixin which we could use for our admin-facing nav bar instead of rolling our own solution.
Fixes DDPB-3040
`npm update govuk-frontend` 💅
But also I had to remove a flakey unit test and limit `npm audit` to only check production dependencies. In our world, that's the GOV.UK and MOJ Design Systems. We don't need to worry as much about other dependencies as they're only exposed in our workflow, not actually sent out to users.
- N/A
=> DDPB-3040: Upgrade GOV.UK Design System to v3.6.0

.circleci/config.yml, .circleci/set_env_pact.sh, client/tests/phpunit/Pact/Listener/PactTestListener.php
Once the consumer (digideps) has created the contract, it needs to be uploaded to the pact broker so the provider can verify it.
Fixes IN-135
I pass in various env vars to allow the the pact to be uploaded to the pact broker. I have put these at the circle level so it can still be run locally and just not send to a pact broker (if you don't want to set it up manually to do so)
I decided to allow digideps user to assume a role with limited access to the broker secret on the broker account rather than duplicate the secret in digideps. This is good if the secret needs to be rotated etc..
I'm sure the PHP could be improved but it's functional.
=> upload pact file to pact broker

api/src/AppBundle/Entity/Repository/ReportRepository.php, api/tests/AppBundle/ControllerReport/ReportControllerTest.php, api/tests/AppBundle/Entity/Repository/ReportRepositoryTest.php
In the "PA fees and expenses" section, we don't add any `Fee` records unless the user selects that they have fees to add. The function that adds the records additionally checks that the user has a named PA deputy in the `deputy_case` table. However, this is no longer always the case with the advent of organisations.
Fixes DDPB-3287
Used the `Report::isPaReport` method to check whether a report is a PA one.
We could've caught this from tests, but because we still support teams (and moreso because our tests are still based around them) we currently don't have test cases with pure organisations.
- N/A right now, might add end-to-end tests with a pure org in the future
=> DDBP-3287: Check report type to identify PA reports

client/src/AppBundle/Resources/views/Admin/Client/Client/details.html.twig, client/src/AppBundle/Resources/views/Admin/Client/Search/search.html.twig, client/src/AppBundle/Resources/views/Admin/Index/addUser.html.twig, client/src/AppBundle/Resources/views/Admin/Index/editUser.html.twig, client/src/AppBundle/Resources/views/Admin/Index/index.html.twig, client/src/AppBundle/Resources/views/Admin/Index/upload.html.twig, client/src/AppBundle/Resources/views/Admin/Index/uploadOrgUsers.html.twig, client/src/AppBundle/Resources/views/Admin/Index/uploadUsers.html.twig, client/src/AppBundle/Resources/views/Admin/Organisation/add-user.html.twig, client/src/AppBundle/Resources/views/Admin/Organisation/form.html.twig, client/src/AppBundle/Resources/views/Admin/Organisation/index.html.twig, client/src/AppBundle/Resources/views/Admin/Organisation/view.html.twig, client/src/AppBundle/Resources/views/Admin/ReportSubmission/index.html.twig, client/src/AppBundle/Resources/views/Admin/Setting/serviceNotification.html.twig, client/src/AppBundle/Resources/views/Admin/Stats/metrics.html.twig, client/src/AppBundle/Resources/views/Admin/Stats/stats.html.twig, client/src/AppBundle/Resources/views/Layouts/admin_moj_template.html.twig
Update the service notification page to match the new design.
Fixes DDPB-3232
I addressed most of this in #262, but I hadn't updated the layout of the radio buttons so this is fixed now.
I've also noticed that my "current page" approach on the nav in #262 didn't account for child pages. For example `/clients` would mark you as being on the "Clients" page, but `/clients/add` wouldn't. I replaced the calculation with an explicit `navSection` variable that each page can set to mark which element of the nav should be highlighted (if any). I updated all the major admin pages to set this variable.
I was tempted to identify the nav page by globbing the URL (for example, and pages starting `/clients` would mark "Clients" as the current page), but I've had trouble with this before where URLs …
=> DDPB-3232: Update design for Notification page to new design layout

client/app/config/services_mail.yml, client/src/AppBundle/Resources/translations/admin-clients.en.yml, client/src/AppBundle/Resources/translations/common.en.yml, client/src/AppBundle/Resources/translations/ndr-debts.en.yml, client/src/AppBundle/Resources/translations/ndr-more-info.en.yml, client/src/AppBundle/Resources/translations/ndr-visits-care.en.yml, client/src/AppBundle/Resources/translations/report-assets.en.yml, client/src/AppBundle/Resources/translations/report-debts.en.yml, client/src/AppBundle/Resources/translations/report-decisions.en.yml, client/src/AppBundle/Resources/translations/report-money-short.en.yml, client/src/AppBundle/Resources/translations/report-money-transaction.en.yml, client/src/AppBundle/Resources/translations/report-more-info.en.yml, client/src/AppBundle/Resources/translations/report-visits-care.en.yml, client/src/AppBundle/Resources/translations/report.en.yml, client/src/AppBundle/Service/ApiCollector.php
Symfony 4 has much stricter rules around YAML configuration. We should update our YAML to match these rules so that a future upgrade is easier.
Fixes DDPB-3293
I upgraded Symfony to v4, tried to compile and fixed any errors reported from YAML syntax. This also identified a missing method in `ApiCollector`.
- N/A
- N/A
- N/A
=> DDPB-3293: Fix YAML configuration in preparation for Symfony 4

api/src/AppBundle/Entity/Repository/ClientRepository.php, api/src/AppBundle/v2/Controller/ClientController.php, behat/tests/bootstrap/Common/ReportTrait.php, behat/tests/bootstrap/Common/SiteNavigationTrait.php, behat/tests/bootstrap/CourtOrderManagement/CourtOrderManagementTrait.php, behat/tests/bootstrap/ReportManagement/ReportManagementTrait.php, behat/tests/features/admin/04-client-details.feature, behat/tests/features/deputy/01-registration-steps/04-add-client-and-report.feature, behat/tests/features/deputy/02-ndr/11-report-submission.feature, behat/tests/features/deputy/03-report/01-102/23-report-resubmission.feature, behat/tests/features/deputy/03-report/01-102/24-lodging-checklist.feature, behat/tests/features/deputy/03-report/04-post-submit/00-report-download-admin.feature, behat/tests/features/pa/03-report/05-report-resubmission.feature, behat/tests/features/prof/05-organisation/04-organisation-updates-acl.feature, behat/tests/features/v2/courtOrderManagement/discharge-deputy.feature, client/src/AppBundle/Controller/Admin/Client/ClientController.php, client/src/AppBundle/Controller/Admin/Client/SearchController.php, client/src/AppBundle/Resources/views/Admin/Client/Search/search.html.twig
Prevents client search page from searching and returning full list on page load. Pressing submit with empty criteria will return that full list if required.
Fixes DDPB-3233
The implementation itself is a straightforward case of not firing the query if no params are sent in the request, i.e on initial page load.
This had a knock on effect to several behat tests which rely on the results returning in order to navigate to a client detail page. To bypass this cumbersome navigation, I have created an endpoint that retrieves client data by `caseNumber`: our tests always have access to a case number so we can hit this new URL directly, instead of navigating via the search. The new endpoint itself simply retrieves the ID of that case and performs a redirect to the exist id based URL.
_Any tips …
=> DDPB-3233: Update client search to prevent default search

client/src/AppBundle/Resources/views/Admin/Client/Report/fullReviewChecklist.html.twig
Based on user feedback the final review comments box has been updated to auto-size as users type. This brings it in line with existing designs for text input fields.
Fixes DDPB-3240
=> DDPB-3240: Add auto-sizing to full review checklist textinput

client/src/AppBundle/Resources/translations/report-documents.en.yml, client/src/AppBundle/Resources/views/Report/Document/step1.html.twig, client/src/AppBundle/Resources/views/Report/Document/step2.html.twig
Adds an inset hint advising deputy that they only need to provide supporting docs if requested to and some minor wording changes.
Fixes DDPB-2900.
=> DDPB-2900: Update supporting documents content

client/src/AppBundle/Resources/assets/javascripts/modules/textarea-autosize.js, docker-compose.yml
Fixes a bug in admin autosize boxes where the page scrolls to the top of the box when a user types in an expanded text box.
Fixes DDPB-3306
Went a bit crazy trying to replicate this until I decided to switch browser to Firefox where the page scrolls to the top of the textarea when autosizing is enabled.
I'm not taking any credit for the code - I stole it from here - https://stackoverflow.com/questions/18262729/how-to-stop-window-jumping-when-typing-in-autoresizing-textarea/60868351#60868351
=> DDPB-3306: Fix firefox page scroll bug

api/src/AppBundle/Entity/Report/Document.php, client/src/AppBundle/Entity/Report/Document.php, client/src/AppBundle/Service/ReportSubmissionService.php, client/tests/phpunit/Service/ReportSubmissionServiceTest.php
Transaction CSVs are incorrectly being given the "is report PDF" flag. This should only be set for the system-generated report PDFs.
Fixes DDPB-3304
I changed the flag in the `generateReportDocuments` function. (The `generateReportPdf` function still sets the flag for actual report PDFs)
- N/A
- N/A
=> DDPB-3304: Transactions files incorrectly labelled as report PDFs

api/app/DoctrineMigrations/Version232.php, api/app/config/services/event_listeners.yml, api/src/AppBundle/Controller/Report/ReportSubmissionController.php, api/src/AppBundle/Entity/Report/ReportSubmission.php, api/src/AppBundle/Entity/Repository/ReportSubmissionRepository.php, api/src/AppBundle/EventListener/DoctrineListener.php, api/tests/AppBundle/ControllerReport/ReportControllerTest.php, api/tests/AppBundle/ControllerReport/ReportSubmissionControllerTest.php, api/tests/AppBundle/Entity/Repository/ReportSubmissionRepositoryTest.php, behat/tests/features/deputy/03-report/01-102/21-check-and-submit.feature, client/docker/env/frontend.env, client/src/AppBundle/Controller/Admin/ReportSubmissionController.php, client/src/AppBundle/Resources/assets/javascripts/main.js, client/src/AppBundle/Resources/assets/javascripts/modules/detached-details.js, client/src/AppBundle/Resources/assets/javascripts/modules/table-multiselect.js, client/src/AppBundle/Resources/assets/scss/_digideps.scss, client/src/AppBundle/Resources/assets/scss/digideps/_table-multiselect.scss, client/src/AppBundle/Resources/assets/scss/digideps/_text.scss, client/src/AppBundle/Resources/translations/admin-documents.en.yml, client/src/AppBundle/Resources/views/Admin/ReportSubmission/_document-sync-table.html.twig, client/src/AppBundle/Resources/views/Admin/ReportSubmission/index.html.twig, client/src/AppBundle/Resources/views/Layouts/admin_moj_template.html.twig, client/src/AppBundle/Twig/ComponentsExtension.php, client/tests/phpunit/Controller/AdminReportSubmissionControllerTest.php, environment/api_service.tf
When we integrate with the API, we will automatically send documents to Sirius so that users don’t have to. However, users need to be aware of any failures or delay in the integration. Therefore, we will show on the documents page which documents/submissions have been synchronised, which are queued, and which have failed.
Fixes DDPB-3161
Working back-to-front:
- Updated the `GET /report-submission` API endpoint to return a new subset of submissions called "pending". These are submissions which have _at least document_ whose sync status is not `null`. "New" submissions have all documents as `null`.
- This makes the queries a bit more complex, but the performance impact is minimal because there are very few non-archived submissions
- Updated design of report submissions page to give more …
=> DDPB-3161: Show synchronisation status in admin panel

client/src/AppBundle/Resources/assets/javascripts/main.js
JavaScript doesn’t load properly on pages in Internet Explorer due to a lack of support of querySelectorAll().forEach.
This has been resolved in the Design System [by using a polyfill hybrid](https://github.com/alphagov/govuk-frontend/blob/063cd8e2470b62b824c6e50ca66342ac7a95d2d8/src/govuk/common.js#L6).
Fixes DDPB-3352
I've copied the polyfill across from the Design System and used it in place of `.forEach`.
[I've added a risk](https://trello.com/c/gOmHVofD/74-poor-detection-of-javascript-errors-in-internet-explorer) about our poor detection of JavaScript errors in Internet Explorer.
- N/A
- N/A, we don't test JavaScript
- N/A
=> DDPB-3352: Error rendering page in Internet Explorer

behat/tests/features/UserManagement/editingUserDetails.feature, behat/tests/features/deputy/04-user/04-user-edit.feature, behat/tests/features/pa/01-registration-steps/01-admin-add-pa-users-and-activate.feature, behat/tests/features/pa/02-team/01-team-setup.feature, behat/tests/features/pa/04-dashboard-client-profile/13-settings.feature, behat/tests/features/prof/01-registration-steps/01-admin-add-pa-users-and-activate.feature, behat/tests/features/prof/02-team/01-team-setup.feature, behat/tests/features/prof/04-dashboard-client-profile/13-settings.feature, client/src/AppBundle/Controller/Admin/IndexController.php, client/src/AppBundle/Form/Admin/EditUserType.php, client/src/AppBundle/Form/Org/OrganisationMemberType.php, client/src/AppBundle/Form/Org/TeamMemberAccountType.php, client/src/AppBundle/Form/Settings/ProfileType.php, client/src/AppBundle/Resources/views/Admin/Index/editUser.html.twig, client/src/AppBundle/Resources/views/Org/Organisation/edit.html.twig, client/src/AppBundle/Resources/views/Org/Team/edit.html.twig, docs/architecture/decisions/0004-user-emails-and-roles-are-immutable.md
As the OPG we want to ensure security on out products and remove the potential risks of users sharing information they shouldn't with others who are not suitable to view client and other deputy data 
We've had some recent concerns (and a security incident) which highlight the dangers of allowing users to freely change their account email addresses. Amongst other things, a high-authority user account can easily be given to a low-authority user by setting it to an email address they control.
Similarly, it's too easy to move a user account between realms (e.g. prof/PA/lay/admin) despite there being no good reason to do so and the realms being completely separate.
Fixes DDPB-3279
I removed the email and role fields from all places where it's available:
- "Edit user" in the admin panel
- "Edit …
=> DDPB-3279: Remove the function for changing user email address and roles

.circleci/config.yml, .circleci/set_env_pact.sh
The digideps side of this is just to add a tag after a deploy to production so that we can make checks on the data-deputy-reporting side against what is live.
Digideps side of in-174
Check the pact version exists. If it does then apply a tag on on the release to prod by means of a variable in the apply job. It should be applied after the build has gone through.
We need to do the pre check, that we get a status 200 on the consumer version, because pact allows you to do a 'put' against non existing versions.. Another interesting little quirk that one. 
Also for verify and canideploy options we are using a single combined tag that encapsulates version and production that allows us to more easily manage different api versions.
=> in-174 add pact prod version tags on prod release

client/src/AppBundle/Service/Availability/SiriusApiAvailability.php, client/tests/phpunit/Controller/ManageControllerTest.php, client/tests/phpunit/Pact/SiriusApiGatewayClientTest.php, environment/terraform.tfvars.json
Preprod is now pointing at preprod rather than prod. Previously whilst sirius preprod wasn't work we had this pointing at prod sirius endpoints but this needs to be updated.
Fixes in-180
updates the account to the preprod account
NA
=> update preprod account details for integrations

client/src/AppBundle/Service/OrgService.php
The CSV upload process times out after our changes in DDPB-3267 and DDPB-3268 have been applied. The upload breaks the CSV into chunks and we believe the work inside one of these chunks is taking too long.
Fixes DDPB-3268
I halved the chunk size from 100 to 50. By processing half as many records, each API call will take less time and use less memory.
This doubles the number of individual requests made to the API, so adds the overhead of wrapping twice as many requests. However, I believe this increase will be negligible in a process that already takes twenty minutes. Furthermore, memory savings on individual API calls might cover for this since we know memory usage is a big problem on this API endpoint.
I attempted the upload locally and it worked fine. This is likely because I have a …
=> DDPB-3268: Reduce org upload chunk size to 50

environment/alarms.tf
Increase the alarm threshold for application errors from 1 per hour to 3 per hour, to help eliminate unnecessary concern and developer downtime
Fixes DDPB-3273
Update terraform.
=> DDPB-3273: Increases alarm threshold to 3

api/src/AppBundle/Controller/Report/ReportSubmissionController.php, api/tests/AppBundle/ControllerReport/ReportSubmissionControllerTest.php, client/src/AppBundle/Controller/Admin/ReportSubmissionController.php, client/src/AppBundle/Resources/translations/admin-documents.en.yml, client/tests/phpunit/Controller/AdminReportSubmissionControllerTest.php, environment/admin.tf, environment/admin_service.tf, environment/admin_sg.tf, environment/common_sg.tf, environment/document_sync.tf, environment/front_service.tf, environment/front_sg.tf
We need to add a way to manually put a document in that state.
In early days of the integration, this will allow us to test that it works as anticipated with a small number of clients. Going forward, it will also allow us to retry failed documents if/when we fix the reason for failure.
Fixes DDPB-3163
I added a new "Synchronise" button alongside the current report submission options. If clicked it will use a new API endpoint to synchronise documents of all selected report submissions.
It will only synchronise null, `TEMPORARY_ERROR` and `PERMANENT_ERROR` documents. The rest will be left as-is.
- N/A
- No Behat test because the setup doesn't lend itself well to Behat (need a submitted report, with a document which has failed) and it would only duplicate unit tests
=> DDPB-3163: Allow users to queue a document for upload

api/src/AppBundle/Controller/Report/ReportSubmissionController.php, api/tests/AppBundle/ControllerReport/ReportSubmissionControllerTest.php, client/src/AppBundle/Controller/Admin/ReportSubmissionController.php, client/tests/phpunit/Controller/AbstractControllerTestCase.php, client/tests/phpunit/Controller/AdminReportSubmissionControllerTest.php
In DDPB-3163, we added a button to the report submissions page of the admin panel. This was made available to all admins, but should be restricted to super admins.
Fixes DDPB-3376
I restricted the button to only be shown if the user has the super admin role, and restricted the related endpoint as well.
I made a slight change to `mockLoggedInUser` so that it sets the mocked user's role to the first role in the permissions array. This could previosuly be done in `mockLoggedInUser`'s second parameter, but it seemed expected enough to just make default behaviour.
- N/A
=> DDPB-3376: Make Synchronise button only visible to super admins

behat/tests/features/deputy/03-report/01-102/08-documents.feature, client/src/AppBundle/Entity/Report/Document.php, client/src/AppBundle/Resources/assets/javascripts/modules/uploadFile.js, client/src/AppBundle/Resources/translations/report-documents.en.yml, client/src/AppBundle/Resources/translations/validators.en.yml
Due to size restrictions for the integration work, document file size needs to be reduced to 5MB in digideps to prevent users uploading documents that will fail to pass through to sirius.
Fixes DDPB-3355, DDPB-3354
Updated the limit on the `Document` entity, and the frontend helper (which warns users earlier if possible).
Updated the help text to match the new limit.
Symfony treats "5MB" as 5000000 bytes (as opposed to 5242880 bytes). This means users _might_ have a file which their computer identifies as <5MB but Symfony does not. This was the case with the previous 15MB limit too, just worth knowing about.
- N/A
- I've added a new test checking large files are rejected
=> DDPB-3355: Amend mb limit for document uploads

.circleci/config.yml, README.md, TECH-DEBT.md
We want to deprecate semvertag because it requires Python 2.7. Since we don't use semver properly, we'll replace with a hash-based versioning system rather than a direct replacement.
Fixes DDPB-3272
I removed semvertag and instead generated the version by combining the current branch and Git hash (`$CIRCLE_BRANCH-$SHORT_HASH`). This then allows us to upgrade the CircleCI executor to Python 3.
I removed the `git tag` step, since it seems pointless to tag a Git hash with a name including the hash (e.g. `master-0b92fed` would be a tag of commit 0b92fed).
Everything else works the same as before: the new version string is used as the tag in ECR, set as the environment variable `OPG_DOCKER_TAG` and displayed in the application footer.
- N/A
=> DDPB-3272: Generate application version statically, deprecate semvertag

api/src/AppBundle/Controller/Report/DocumentController.php, api/src/AppBundle/Entity/Repository/DocumentRepository.php, api/tests/AppBundle/Controller/DocumentControllerTest.php, client/scripts/documentsync.sh, client/src/AppBundle/Command/DocumentSyncCommand.php, client/src/AppBundle/Service/DocumentSyncService.php, client/tests/phpunit/Command/DocumentSyncCommandTest.php, client/tests/phpunit/Service/DocumentSyncServiceTest.php, environment/document_sync.tf, environment/front.tf, environment/parameters.tf
This change moves away from having a daemonable long-running command and instead creates a scheduled cloudwatch event that runs the document sync task once every five minutes. We lose the ability to control the frequency of the task due to the value being baked into the schedule terraform but from my testing today we're not seeing any out of memory errors.
Some other points this PR fixes:
- Now seeing the true number of failed documents per sync in output. Previously this was polluted when performing a batch update on supporting documents.
- Sorting the queued documents by is_report_pdf and then id. I witnessed cases, where the 100 documents returned, were all supporting documents which meant they would always be set to queued and no new documents would be picked up as a supporting …
=> DDPB-3403: Memory leak over document-sync cycles

environment/admin.tf, environment/api.tf, environment/ecs.tf, environment/front.tf
A separate audit log group that will hold any application audit information such as when a client is deleted. This is locked down from org infra so that viewers and operators (of which all console viewers will be a member of) can't view the contents. They can still see it exists.
Fixes DDPB-3330
A few issues with this. Talked to Matt about whether we needed breakglass for this group, he suggested we should. You can only attach one log group to an ECS container so we needed a better way of splitting out the logs. 
Using Monolog, we can split out the logs and give the task user access to only create streams and post logs, the set of permissions the task has is the minimum it needs to work with the new log groups.
Although you can create log groups with monolog, we want them managed by …
=> DDPB-3330 add audit log group

api/src/AppBundle/Controller/Report/ReportController.php, behat/tests/bootstrap/ReportManagement/ReportManagementTrait.php, behat/tests/features/v2/reportManagement/closing-incomplete-reports.feature, client/src/AppBundle/Controller/Admin/Client/ReportController.php, client/src/AppBundle/Entity/Report/Report.php, client/src/AppBundle/Form/Admin/CloseReportConfirmType.php, client/src/AppBundle/Form/Admin/CloseReportType.php, client/src/AppBundle/Resources/translations/admin-clients.en.yml, client/src/AppBundle/Resources/translations/validators.en.yml, client/src/AppBundle/Resources/views/Admin/Client/Report/manage.html.twig, client/src/AppBundle/Resources/views/Admin/Client/Report/manageCloseReportConfirm.html.twig
Give case managers to "close" (resubmit) a report that has been marked as incomplete, so that the deputy can progress to the next report. As it stands, deputies need to manually resubmit on behalf on the case manager which is an unnecessary inconvenience.
Fixes DDPB-2898
Added a separate form to the report management page, as per the design, that only renders when a report has been marked as incomplete (unsubmitted).
=> DDPB-2898: Add option to close (resubmit) an unsubmitted report

client/src/AppBundle/Service/IntlService.php, client/src/AppBundle/Service/Mailer/MailFactory.php, client/tests/phpunit/Service/Mailer/MailFactoryTest.php
Due to strict mode checks the application was failing when we were trying to convert a null country code value to the actual country name. This change supports null country values and reduces some mocking from our tests.
Fixes DDPB-3358
It felt like a better solution to support null values in `getCountryNameByCountryCode()` rather than handle separately in the MailFactory functions.
There was a little too much mocking going on in the affected tests as this masked what would actually happen if we fed in a null value rather than receive a null value from the function. I've used the real service in the test now rather than a mock.
=> DDPB-3358- Support clients and deputies not having a country 

client/app/config/services.yml, client/app/config/services_api.yml, client/composer.json, client/composer.lock, client/src/AppBundle/Controller/FeedbackController.php, client/tests/phpunit/phpunit.xml
Chipping away at deprecations that are required for a Symfony 4/5 upgrade.
Fixes DDPB-3373
I bought in symfony-phpunit-bridge which gives handy deprecation and warnings for the version you install it as (e.g. install phpunit-bridge 4.4 to get warnings for Symfony 4.4). The warnings are limited to code that is hit by phpunit but its a fairly quick way to start to fix things up.
There are 5 deprecations left that would involve a re-write of a test or changing the way a class works so I'm leaving this PR with the easy stuff for now.
=> DDPB-3374 - Low impact Symfony upgrade deprecation fixes

api/src/AppBundle/Entity/Organisation.php, client/src/AppBundle/Controller/Report/DocumentController.php, client/src/AppBundle/Entity/Client.php, client/src/AppBundle/Security/DocumentVoter.php, client/tests/phpunit/Security/DocumentVoterTest.php
Fix to allow org deputies to delete documents from reports
Fixes DDPB-3379
The current `DocumentVoter` in the client was only granting permissions on its actions if the Report belongs to a Client that is attached to the Deputy. In the case of an Org deputy whose court order never existed pre the organisation migration, the Client will never be associated to the Deputy, but instead they are associated by belonging to the same Organisation. 
I have updated the Voter to run a further a check on whether the Client belongs to the same Organisation as the Deputy.
I added unit tests for the entire Voter, and also tidied up the Voter code.
=> DDPB-3379: Fix to allow org deputies to delete documents from reports

api/src/AppBundle/DataFixtures/UserFixtures.php, api/src/AppBundle/Entity/Repository/UserRepository.php, api/src/AppBundle/FixtureFactory/CasRecFactory.php, api/src/AppBundle/FixtureFactory/UserFactory.php, api/src/AppBundle/v2/Fixture/Controller/FixtureController.php, client/src/AppBundle/Controller/Admin/FixtureController.php, client/src/AppBundle/Form/Admin/Fixture/CasrecFixtureType.php, client/src/AppBundle/Form/Admin/Fixture/CourtOrderFixtureType.php, client/src/AppBundle/Resources/translations/admin-fixtures.en.yml, client/src/AppBundle/Resources/views/Admin/Fixtures/casRec.html.twig, client/src/AppBundle/Resources/views/Admin/Fixtures/courtOrders.html.twig, client/src/AppBundle/Resources/views/FlashMessages/fixture-casrec-created.html.twig, client/src/AppBundle/Resources/views/FlashMessages/fixture-user-created.html.twig
During the investigation for DDPB-3406 I realised other than manipulating the CSV there was no way to easily create Casrec entries or registered co-deputies. I've expanded the court order fixture creation page to have the option of creating a co-deputy and if the user should be activated or not. I also added a new endpoint /fixtures/create-casrec that lets you add sole or co-deputy entries there ready to be used int he registration flow.
Fixes DDPB-3406.
I had some issues with returning entities when POSTing to the user creation endpoint which is why I've had to make the extra callout to get the created deputies. If there's a trick to this let me know @aiesoftware!
=> DDPB-3406 - Expand fixtures endpoints

api/tests/AppBundle/ControllerReport/ReportSubmissionControllerTest.php, client/src/AppBundle/Entity/Report/Report.php, client/src/AppBundle/Service/ReportSubmissionService.php, client/tests/phpunit/Service/ReportSubmissionServiceTest.php
Transaction CSVs are only useful for reports that have high assets but up until now we've been generating them for all report types. This change restricts the CSV generation to just high asset report types.
Fixes DDPB-3390
=> DDPB-3390 - Digideps creates CSV files for HW reports and 103 reports

behat/tests/bootstrap/UserTrait.php, behat/tests/features/pa/01-registration-steps/01-admin-add-pa-users-and-activate.feature, behat/tests/features/prof/01-registration-steps/01-admin-add-pa-users-and-activate.feature, client/src/AppBundle/Controller/Admin/IndexController.php, client/src/AppBundle/Resources/translations/admin.en.yml, client/src/AppBundle/Resources/views/Admin/Index/editUser.html.twig, client/src/AppBundle/Resources/views/Admin/Index/index.html.twig, client/src/AppBundle/Resources/views/Admin/Index/viewUser.html.twig, client/src/AppBundle/Resources/views/Admin/Organisation/view.html.twig
Currently clicking on a user in admin directs straight to the edit page of that user. This task creates a view page, which will be the landing page for all links linking to the deputy page, and will contain an "Edit user" button that will direct to the edit page. The flow is identical to the Organisation pages in admin.
Fixes DDPB-3082
Added a new route/controller/view for the view page
Update existing links to land on the view page instead of edit page
Move the table data from the edit page view into the view page view
Updated behat tests to account for the extra page in the journey
=> DDPB-3082: Add view page for deputy in admin

sync/Dockerfile
Updating to use Python 3 as the Python 2 / pip alpine images were no longer available. Fixes the pipeline due to backup and restore jobs needing a working version of awscli.
Fixes DDPB-3435.
=> Update to Python 3

client/src/AppBundle/Resources/views/Admin/Client/Report/manageConfirm.html.twig
We now have the functionality to recall reports that have been sent to users for amendments. This change removes the warning message that was in place prior to this functionality.
Fixes DDPB-3429
=> DDPB-3429: Remove warning on being unable to recall reports

client/app/config/services.yml, client/src/AppBundle/Model/Sirius/SiriusApiError.php, client/src/AppBundle/Service/DocumentSyncService.php, client/src/AppBundle/Service/SiriusApiErrorTranslator.php, client/tests/phpunit/Service/DocumentSyncServiceTest.php, client/tests/phpunit/Service/SiriusApiErrorTranslatorTest.php
We are currently storing the full json blob error responses from the integration API and displaying this to users in the submission admin panel. While there is some detail in the blob its not always easy to see what has gone wrong. This change translates the error types into easier to read versions.
Fixes DDPB-3384
I've used the Open API spec as the source of truth for all the error types (https://github.com/ministryofjustice/opg-data/blob/master/docs/deputy-reporting-openapi-v1.yml). I've raised the scenario where a caseref doesn't exist within Sirius with the integrations team (https://mojdt.slack.com/archives/CBKSZGH0C/p1590577117014100?thread_ts=1590484609.003800&cid=CBKSZGH0C) as it doesn't look like we have a way to identify this right now, but this shouldn't stop us from moving …
=> DDPB-3384: Improve readability of DocumentSync errors

client/src/AppBundle/Resources/views/Report/Balance/balance.html.twig, client/src/AppBundle/Twig/ComponentsExtension.php
Update tag to use gov-uk classes, using colours based on prototype discussed in the ticket.
Fixes DDPB-3248
The tag code is shared throughout the app so just a case of updating that central code.
=> DDPB-3248: Updates tag colours

api/src/AppBundle/Entity/Client.php, api/tests/AppBundle/Entity/ClientTest.php, client/src/AppBundle/Resources/views/Admin/Client/Report/partials/_deputy-and-client-info.html.twig
Case managers had reported an application error when accessing report checklists for reports that had a made date set to null. This change ensures users can access a report checklist despite a missing made date.
Fixes DDPB-3415
The issue actually turned out to be linked to the calculated report start and end date as this relies on there being a court date set on a report. I've returned null for the calculated start date (and by proxy, end date) which seems to have solved the issue. I've tested submitting reports and NDRs without a client court date and all seems well locally and the checklist is accessible.
**Can anyone think of any other unintended implications of returning null for an expected start and end date?** I've followed through the usages in the code and they seem minimal but …
=> DDPB-3415: Resolve made date issue preventing access to checklist

client/docker/confd/templates/pool.conf.tmpl
We noticed during testing some of the document bugs tickets that you could select more than 20 images to upload but only 20 would be attached with no errors displayed to users. This isn't a great user experience and makes testing the document sync feature slower.
Fixes DDPB-3437
=> DDPB-3437: Increase file upload limit from 20 to 100

.circleci/config.yml, .pa11yci, docker-compose.yml, pa11y/.pa11yci, pa11y/Dockerfile
Add Pa11y Accessibility testing tool to pipeline to alert developers to any areas of the service that may cause issues to users who are using other tools to view webpages.
Fixes DDPB-3325
Added a pa11y job into the config for CircleCI. This jobs runs the pa11y container/service. The container grabs all the dependencies needed to run the pa11y tool and brings in the config file pa11y needs. 
After the pa11y container is finished being brought up, prod mode is enabled is remove the symfony profiler from display. The job waits for a small amount of time before running the pa11y test.
During the test, pa11y will report any errors it detects. The command to run the pa11y test ensures that the job, and therefore the pipeline, does not fail when an error is detected.
Learnt how to create and …
=> Add Pa11y accessibility test tool to CircleCI pipeline

api/src/AppBundle/Controller/UserController.php, client/app/config/services.yml, client/src/AppBundle/Controller/Admin/AdController.php, client/src/AppBundle/Controller/Admin/Client/ClientController.php, client/src/AppBundle/Controller/Org/OrganisationController.php, client/src/AppBundle/Controller/SettingsController.php, client/src/AppBundle/Entity/User.php, client/src/AppBundle/Service/Audit/AuditEvents.php, client/tests/phpunit/Controller/AbstractControllerTestCase.php, client/tests/phpunit/Controller/ClientControllerTest.php, client/tests/phpunit/Controller/OrganisationControllerTest.php, client/tests/phpunit/Controller/SettingsControllerTest.php, client/tests/phpunit/Service/Audit/AuditEventsTest.php
Continuing with the audit logging risk identified - this change emits audit logs when a users role is changed.
Fixes DDPB-3336
I've been over the CSV upload process and couldn't see anywhere obvious where a User's role is changed. The only other two places I could see this happening was:
- A user removing admin privileges from themselves in the frontend
- A PA/Prof admin adding or removing admin roles to other members of their org
I purposefully left out team role updates as we'll soon be removing all team code.
=> DDPB-3336: Audit for account information - user role

client/src/AppBundle/Resources/views/Org/ClientProfile/_reportDetail-PA.html.twig, client/src/AppBundle/Resources/views/Org/ClientProfile/_reportDetail-Prof.html.twig
Semantically incorrect markup in the prof and PA report overview template was picked up in the DAC report that would cause screen readers to announce definition lists incorrectly. This change ensures both views are now semantically correct.
Fixes DDPB-3311
It seemed the easiest fix was to just move the `details` element into the `dd` element it was sitting next to as a sibling.  I've added a pa11y test for this view in #393 so haven't duplicated here.
=> DDPB-3311: Move Details element within dd element

.circleci/config.yml, client/src/AppBundle/Resources/views/Org/ClientProfile/overview.html.twig, pa11y/.pa11yci, pa11y/screenshots/.gitignore
Fix an issue with invalid aria values in an accordion that was identified as part of the DAC report.
Fixes DDPB-3310
I had a search around the codebase and couldn't find anywhere else we were appending an EPOCH time string to an accordion ID. From looking at the git history I think this may have come about when we were using a custom solution rather than the GDS version. The date string was originally added there to ensure the IDs were unique but the GDS component automatically appends a number based on how many sections of the accordion there are. The date string was probably left in after we moved to the GDS version.
=> DDPB-3310: Invalid ARIA attributes in organisation report overview accordion

.circleci/config.yml, api/scripts/reset_db_structure.sh, docker/bash_profile, docs/CONTRIBUTING.md, docs/DATABASE.md, docs/architecture/decisions/0002-use-amazon-aurora-for-application-database.md, environment/terraform.tfvars.json
As part of removing oppressive language from our codebase this change will rename references from `master` to `main`.
Fixes DDPB-3463
A search folder by folder highlighted the following places we needed to make the change:
- Rename all instances of master to main
- Update bash_profile scripts to use main rather than master
- Rename all instances of master to main in .circleci/config.yml
Change tfvars.json reference from master to main
Change default_branch_name in opg-org-infra to from master to main (PR raised separately)
=> DDPB-3463: Rename base branch from master to main

.circleci/config.yml, README.md, environment/admin_sg.tf, environment/front_sg.tf, environment/terraform.tfvars.json, environment/variables.tf
After the renaming of our default branch to `main` it seemed like a good opportunity to diverge the name of the workspace to something else. The reason behind this being that sharing a name insinuates that there is a direct link between the branch and the workspace when in reality they are completely separate. We've settled in `integration` as this is the closest name that describes the workspace's purpose (running integration tests in a prod-like environment).
Fixes DDPB-3534.
I now know what a workspace is 🙃  
```
A workspace is effectively a state file
So it's the full configuration for whatever you're building. You could have multiple workspaces in a single account or one workspace that puts resources across multiple accounts
In practice it affects what the resources are named …
```
=> DDPB-3534 - Rename master workspace to integration

client/src/AppBundle/Controller/Org/IndexController.php, client/src/AppBundle/Service/Audit/AuditEvents.php, client/tests/phpunit/Controller/Org/IndexControllerTest.php, client/tests/phpunit/Service/Audit/AuditEventsTest.php
The system currently supports adding and removing Client email addresses alongside changing them but our audit logging does not. This change allows the old and new email address to be null to support this.
=> DDPB-3530: Support audit logging when removing and adding client email address

environment/document_sync.tf, environment/parameters.tf
The dastardly `02` of `production02` strikes again. This change should stop the Sirius URL from being updated to the mock server on prod.
=> Use correct workspace name for prod

client/src/AppBundle/Resources/views/Admin/Client/Client/details.html.twig, client/src/AppBundle/Resources/views/Admin/Index/index.html.twig, client/src/AppBundle/Resources/views/Admin/Organisation/index.html.twig, client/src/AppBundle/Resources/views/Org/ClientProfile/_reportDetail-PA.html.twig, client/src/AppBundle/Resources/views/Org/ClientProfile/_reportDetail-Prof.html.twig, client/src/AppBundle/Resources/views/Org/Team/list.html.twig, client/src/AppBundle/Resources/views/Report/Report/_subsection.html.twig, docs/PULL_REQUEST_TEMPLATE.md
We have multiple instances where links are limited to single words (Edit, Remove, Add etc) or contextually incomplete phrases (send email rather than send email to <users name> etc). This makes it more difficult for users of screen readers to navigate and work with our application. This change adds context to as many instances of these links and buttons as possible. 
Fixes DDPB-3314
I've added an extra checklist to our frontend checklist as a reminder to ensure we add context to any links or buttons that we add as part of a PR to make sure our app continues to be screen reader-friendly.
=> DDPB-3314: Update non-descriptive links

client/src/AppBundle/Resources/views/Index/index.html.twig, client/src/AppBundle/Resources/views/Ndr/Action/start.html.twig, client/src/AppBundle/Resources/views/Ndr/Action/step.html.twig, client/src/AppBundle/Resources/views/Ndr/BankAccount/start.html.twig, client/src/AppBundle/Resources/views/Ndr/DeputyExpense/start.html.twig, client/src/AppBundle/Resources/views/Ndr/IncomeBenefit/start.html.twig, client/src/AppBundle/Resources/views/Org/ClientProfile/_notes.html.twig, client/src/AppBundle/Resources/views/Report/Action/start.html.twig, client/src/AppBundle/Resources/views/Report/Action/step.html.twig, client/src/AppBundle/Resources/views/Report/Balance/balance.html.twig, client/src/AppBundle/Resources/views/Report/BankAccount/start.html.twig, client/src/AppBundle/Resources/views/Report/Decision/exist.html.twig, client/src/AppBundle/Resources/views/Report/Decision/start.html.twig, client/src/AppBundle/Resources/views/Report/DeputyExpense/start.html.twig, client/src/AppBundle/Resources/views/Report/Gift/start.html.twig, client/src/AppBundle/Resources/views/Report/MoneyOut/summary.html.twig, client/src/AppBundle/Resources/views/User/register.html.twig
Restoring this after @jamesrwarren overwrote the previous work (totally my faulty as I had the wrong branch name 🙈 ).
Switching from custom CSS classes on `details` and `summary` elements to using GDS versions with an added data-module to support IE11 fallback.
Fixes DDPB-3313
=> DDPB-3313: Update detail and summary elements to use GDS version for IE11 fallback

client/src/AppBundle/Resources/views/Report/Formatted/_prof_deputy_costs_estimate.html.twig, client/src/AppBundle/Resources/views/Report/ProfDeputyCostsEstimate/_answers.html.twig
An issue was identified where the in the “More Information” box in the “Deputy Costs Estimates” section, it only accepts the first capital letter and any capital’s afterwards (e.g. start of a second sentence) are turned into a lower case when the form is produced.
This means on both the summary page for the section and review page for the report, the information entered by the user would only have a capital letter for the first character, and the rest would be lower case. However, returning to page to edit the information would show the information in its original format as entered by the user.
Fixes DDPB-3457
We removed `| capitalize` which was the source of the issue. This would load the text and format it as to upper-case the first character and lower-case the rest. Unsure as to why it …
=> DDPB-3457: Capitals not persisted in text boxes

client/src/AppBundle/Controller/Admin/IndexController.php, client/src/AppBundle/Service/Audit/AuditEvents.php, client/src/AppBundle/Service/Logger.php, client/tests/phpunit/Controller/AdminIndexControllerTest.php, client/tests/phpunit/Service/Audit/AuditEventsTest.php
Adds audit logging for deleting a deputy.
Fixes DDPB-3332
Although very unlikely, I've added some error catching around failures to delete a deputy so we aren't logging events that never happen.
=> DDPB-3332: Add deputy deleted event and add logging to delete deputy action

environment/terraform.tfvars.json
It was brought to our attention that the development environment was running slowly. There didn't seem to be much difference in traffic except that the aws availability check was being hit repeatedly. By changing this single option to false we bypass this check. It's also probably better to be on aurora as the env is not used that often.
Fixes DDPB-3532
=> DDPB-3532 see if works better as always_on false

.gitignore, .pre-commit-config.yaml, README.md
I've added in a couple of pre-commit hooks to our repo to try to automatically fix any styling errors as according to PSR2 and to add strict types to newly created PHP files so we don't need to keep remembering to do it.
`sed` on mac does not work like `sed` on Linux!
=> Add php commit hooks

.circleci/config.yml, environment/monitoring_lambda_event.tf
We've been seeing timeouts in the integration pipeline recently after changing from a medium to a small docker executor. This bumps the timeouts slightly higher to account for this.
Also disabling the queued documents alarm in non-prod environments as we are usually going to encounter this and the alarms are not required.
=> Increase timeouts and disable non-prod doc queue alarams

behat/tests/features/admin/00-prechecks.feature, behat/tests/features/deputy/01-registration-steps/00-prechecks.feature, client/composer.lock, client/docker/env/frontend.env, environment/front_sg.tf, environment/mock_sirius_integration_service.tf
Security group rules were missing access from frontend to mock sirius! As part of this fix, I've added a test that would pick this issue up in future (as it was still returning 200 even though the sirius check was timing out).
Also needed to update composer as had a security vulnerability come up that stopped the build.
Fixes DDPB-3630
Fixed sec group rule and added a test
NA
=> DDPB-3630 fix sec group rule for mock end point

environment/scan.tf, environment/terraform.tfvars.json, environment/variables.tf
Scan service is falling over. This should at least alleviate the issue for now. Need to do thorough testing on whether we can make a the settings help minimise this instead.
=> DDPB-3636 adding extra memory to scan task in pre and prod

client/src/AppBundle/Resources/views/Admin/Client/Report/Formatted/checklist_formatted_body.html.twig, client/src/AppBundle/Resources/views/Macros/macros-review.html.twig, client/src/AppBundle/Resources/views/Ndr/Formatted/Asset/_property.html.twig, client/src/AppBundle/Resources/views/Ndr/Formatted/_actions.html.twig, client/src/AppBundle/Resources/views/Ndr/Formatted/_assets.html.twig, client/src/AppBundle/Resources/views/Ndr/Formatted/_contacts.html.twig, client/src/AppBundle/Resources/views/Ndr/Formatted/_debts.html.twig, client/src/AppBundle/Resources/views/Ndr/Formatted/_income_benefits.html.twig, client/src/AppBundle/Resources/views/Report/Formatted/Accounts/_money_in_out_short.html.twig, client/src/AppBundle/Resources/views/Report/Formatted/Asset/_property.html.twig, client/src/AppBundle/Resources/views/Report/Formatted/_assets.html.twig, client/src/AppBundle/Resources/views/Report/Formatted/_attached_documents.html.twig, client/src/AppBundle/Resources/views/Report/Formatted/_debts.html.twig, client/src/AppBundle/Resources/views/Report/Formatted/_gifts.html.twig, client/src/AppBundle/Resources/views/Report/Formatted/_mental-capacity.html.twig, client/src/AppBundle/Resources/views/Report/Formatted/_pa_fee_expenses.html.twig, client/src/AppBundle/Resources/views/Report/Formatted/_prof_current_fees.html.twig, client/src/AppBundle/Resources/views/Report/Formatted/_prof_deputy_costs.html.twig, client/src/AppBundle/Resources/views/Report/Formatted/_prof_deputy_costs_estimate.html.twig
In the generated report PDF we use “X” in a box to indicate the user's selection:
This is read out to screenreader users as “cross”, which is unclear. This tickets adds the attribute aria-label=”Selected” so that screenreaders read it as “Selected” instead.
Fixes DDPB-3324
Add the attribute aria-label=”Selected” so that screenreaders read it as “Selected” instead.
=> DDPB-3324 - Selected boxes are unclear to screenreaders in report preview

client/src/AppBundle/Resources/views/Index/index.html.twig, client/src/AppBundle/Resources/views/Macros/macros.html.twig
Improved usability for screenreader users
The <aside> HTML5 tag is considered a landmark tag in and by it's self.
The HTML specification suggestes landmarks should not be contained
within other landmarks and our sidebars are contained within the
<main> tag which is considered a landmark therefore we change the
<aside> tag to a standard <div> tag
Fixes DDPB-3317
=> DDPB-3317: removed the <aside> HTML tag as it should not be contained within a landmark

client/src/AppBundle/Resources/views/Admin/Organisation/form.html.twig
This removes the "Your report is ready to submit." notification message
from the admin panel when editing an organisations as this message is
for the deputy side of the app
Fixes DDPB-3496
=> DDPB-3496: Removed the status notification from admin

Makefile, client/src/AppBundle/Resources/assets/javascripts/main.js
There was an issue where if we had a form error on the page we didn't
auto-focus onto the error summary. According to the GOV.uk design system
we should auto-focus onto any error summaries on the page to
Fixes DDPB-3321
=> DDPB-3321: Error summaries do not auto-focus

client/src/AppBundle/Resources/assets/javascripts/main.js, client/src/AppBundle/Resources/assets/scss/_digideps.scss, client/src/AppBundle/Resources/assets/scss/digideps/_links.scss, client/src/AppBundle/Resources/views/Report/Document/submitMoreDocumentsConfirm.html.twig
When adding documents to a submitted report, we can hit the button multiple times and this causes additional document submission rows to be entered in the DB.
Fixes DDPB-3628
Quick fix to only allow us to submit once as once the button is pressed once, it becomes inactive.
Learned a bit about how the data-modules work with CSS.
=> DDPB-3628 fix double click when adding documents to a report

client/src/AppBundle/Resources/views/Admin/Client/Report/macros.html.twig, client/src/AppBundle/Resources/views/Admin/Client/Report/partials/_deputy-and-client-info.html.twig, client/src/AppBundle/Resources/views/Admin/Client/Report/partials/_lodging-summary.html.twig, client/src/AppBundle/Resources/views/Report/Decision/_form.html.twig
Heading that are of the same semantic level should use the same HTML
heading level tag. For example all `<h2>` but when a sub-heading is added
it should increment the level by one `<h3>`. This ticket does that while
also removing `<h4>` as they should rarely be needed.
Fixes DDPB-3315
=> DDPB-3315: Illogical heading structure

docker-compose.override.yml
By having a single volume for /app there is some kind of overwriting going on for the value of the client secret app env in admin that determines which roles are allowed to sign in to which side of the frontend. I've reinstated them to how they were before so this should fix local docker login issues for admin.
=> Reinstate separate app volumes

codecov.yml
A quick update to ignore some folders we don't want to be included in our coverage metrics in codecov.
=> Add ignore paths

environment/s3.tf, shared/s3_replication.tf
Our existing structure of S3 bucket replication settings broke when we tried to apply it to the same bucket we are replicating to. To fix this we've moved the replication bucket to account level to be created in the development account only.
We will need to update the bucket reference in Sirius to point to this in order for testing the Document flow on branches to work.
=> Move replication bucket to account level in development only

environment/s3.tf
The pipeline was still broken following #449 as the ARN is only available in the development account. This change locks the data source for the bucket to using the development provider to ensure the ARN is always available but replication is disabled in non-branch environments.
=> Lock replication bucket ARN to development provider

README.md, shared/s3_replication.tf
Missing this count meant non-development environments were trying to reference a non-existent resource.
=> Add missing count to dev only resources

shared/document_sync.tf
The naming was wrong on s3 read integration role. Make it so that it works properly in prod and preprod.
Fixes DDPB-3659
Make it work
=> DDPB-3659 fix to s3 read integration role

client/app/config/security.yml, client/src/AppBundle/Controller/IndexController.php, client/src/AppBundle/Resources/translations/accessibility.en.yml, client/src/AppBundle/Resources/views/Index/accessibility.html.twig, client/src/AppBundle/Resources/views/Layouts/application.html.twig
Composed the google doc with our accessibility statement into a twig template using translations.
I wasn't around for the majority of the accessibility tickets so would appreciate some feedback on if external links etc are handled properly.
Fixes DDPB-3632
Small thing but you need to apply a `raw` filter when using translations that contain html.
=> DDPB-3632: Add accessibility page

api/docker/confd/templates/pool.conf.tmpl, client/docker/confd/templates/pool.conf.tmpl, environment/api_rds.tf, environment/front_service.tf, environment/mock_sirius_integration_service.tf, environment/scan.tf, environment/terraform.tfvars.json, environment/variables.tf, environment/wkhtmltopdf.tf
Scale down infra as we have way too much unused CPU and RAM. In fact previously RAM was set to 256 max for PHP so I have upped that to be inline with the container size.
Integration tests should use the app far more than we would use it for UAT and they all pass with normal times. 
I haven't scaled down prod as I don't deem it to be worth it. In fact for the scan containers I've given them extra RAM again as they seemed happier with the extra memory.
Fixes DDPB-3644
Make changes in terraform and to the PHP ini file.
=> DDPB-3644 scale down existing infra to manage costs

client/src/AppBundle/Resources/views/Admin/Client/Report/Formatted/checklist_formatted_body.html.twig
Checklist question l7.2 is an only applicable on certain report types and only shows up to check on the checklist where it exists on those reports. Whilst some users found this confusing, it's how it was designed to work. 
However to avoid confusion it shouldn't then appear on the PDF when it doesn't exist on the checklist. 
Checked all the checklist options with different report types and this was the only instance of this I could find. Full sections were already handled properly. As such the end fix for this is a very straight forward fix
Fixes DDPB-3627
Only displays the balance on spreadsheet where that section exists in report
Certainly learned a bit more about how checklists worked. Easy fix but interesting area for business logic
=> DDPB-3627 exclude missing sections from checklist pdf

.circleci/config.yml, environment/provider.tf, environment/versions.tf, shared/provider.tf, shared/versions.tf
Upgrades Terraform to 0.13, change fixes some annoying bugs and adds the ability to use count on modules
Fixes DDPB-3664
Used HashiCorp provided upgrade tool
Performed manual state moves in each terraform workspace for providers
=> DDPB-3664 - Terraform 0.13 Upgrade

client/docker/confd/templates/app.conf.tmpl
Add missing security headers to requests
Fixes DDPB-3568
Updated nginx config to add missing headers
=> DDPB-3568 - Add missing security headers

environment/api_rds.tf, environment/terraform.tfvars.json, environment/variables.tf
Upgrades postgresql from `9.6.16` to `10.7` to unblock the move to RDS Aurora
Fixes DDPB-3228
- Update all env to 10.7 immediately (apart from production)
- Make sure things are working, Ie tests etc
- second PR (probably next week) to update production version
=> DDPB-3228 - Upgrade postgres to 10.7

api/docker/confd/conf.d/nginx.conf.toml, api/docker/confd/templates/nginx.conf.tmpl, api/docker/env/api.env, client/docker/confd/conf.d/nginx.conf.toml, client/docker/confd/templates/nginx.conf.tmpl, client/docker/env/admin.env, client/docker/env/frontend.env, environment/.envrc, environment/admin_service.tf, environment/alarms.tf, environment/api_service.tf, environment/front_service.tf
Addresses DDPB-3579 adding in alerting at each app tier for application errors and tracking response times for the two application load balancers
I switched out the log format in the NGINX config to pass JSON to cloudwatch.  This change allows the logs to be queried intelligently rather than string matching.  It also allows metric filters on the log files to be configured more easily.
I used metric filters to track 5XX errors in NGINX in frontend, admin, & API tiers and alert.
I enabled anomaly detection on the Average Response Times for both ALB's and alerting on that.
=> Monitoring & Alerting

client/src/AppBundle/Controller/UserController.php
We're currently returning 500 responses for expired user tokens. Now we're alerting on 500s a little more consistently this has led to some slack spam. We should return the more appropriate response code of 401 for unauthorised access to an endpoint.
Fixes DDPB-3724
Return 401 (and find a way to use 418 in future tickets 🍵 )
=> DDPB-3724: Return unauthorised rather than server error for expired user tokens

client/src/AppBundle/Controller/UserController.php
Follow up to #485 to use whatever we return from the API rather than a 401.
=> Use the response code from API when token is invalid

.circleci/config.yml, environment/terraform.tfvars.json
There are some changes due for beginning of November that mean that there will be limit on no. of pulls from dockerhub for unauthenticated PRs using circleci.
Fixes DDPB-3721
Set up our dockerhub user and creds in org infra.
This is the digideps side of things that forces our pipeline to use the credentials.
=> DDPB-3721 add docker auth variables

.circleci/config.yml, environment/admin_sg.tf, environment/checklist_sync.tf, environment/document_sync.tf, environment/scan_sg.tf
Quick wins for tightening security rules that don't break things.
Part a of this ticket was looking at making the cidr ranges tighter but broke on lots of things
Part b is looking at a spike for squid egress proxy.
This part is some quick wins that can easily implement now.
Fixes DDPB-3663
Tighten some of the 0.0.0.0/0 outbounds down to security groups
=> DDPB-3663c first pass with mock fixes

environment/.envrc, environment/alarms.tf, environment/dashboard.tf, environment/terraform.tfvars.json
Add in a CloudWatch dashboard for some observability of the DigiDeps service.  
Easily expose the uptime stats from the Route53 Healthchecks.
I have tuned down the alarm thresholds to counter false triggers.
=> DDPB-3228 - System Availability Dash

environment/alarms.tf, environment/s3.tf, shared/s3_replication.tf
We currently encrypt data on s3 using a policy. To show that that the buckets use encryption we can set it at the bucket level. AES256 encryption which the policy specifies is the same as the aws kms key uses so they should be compatibly and we can leave in the policy as it was previously working.
Fixes DDPB-3184
Got a bit nervous about how this would affect existing data so spun it up without the encryption, ran the end to end tests then manually ran the encryption on the buckets through terraform and checked I could still access the existing files and that I could upload new files through the app.
Checked the integrations still work fine in environment.
=> DDPB-3184 create enc to test adding encryption to s3

.circleci/config.yml, shared/environment_secrets/main.tf, shared/environment_secrets/variables.tf, shared/secrets.tf, shared/terraform.tfvars.json, shared/variables.tf
Bring secret management (creation/deletion) under the control of terraform.
Fixes DDPB-3564
As there are three different approaches to secrets, I've chosen to unify them by having each environment have it's own set of secrets generated at the account/shared level.  The downside to this is that secrets must be created at the environment level before a new persistent environment can be created.
I've taken the approach of passing a list of environments per workspace into a module with a list of secrets that are required, I feel this is the cleanest and easiest to manage approach.
=> DDPB-3564 - Secret Management

.circleci/config.yml
Adding a step to push digideps release times to OPG metrics. This will give us an overview of when releases are pushed out to production. This won't be totally accurate as there will be a short delay between apply production and the metrics job running but its POC for now and we can look at exporting the actual release time to a variable and sharing it with the metrics job in the future.
=> Push release time to OPG Metrics

.circleci/config.yml, environment/admin.tf, environment/alarms.tf, environment/front.tf, environment/run_tasks.tf
Reduce the amount of alerting spam from ALB Response Time alarms which were tracking anomaly detection, change this to the static threshold of 1 second as agreed with the team.
Fixes DDPB-3749
I have also refactored the PR Pipeline to plan against shared development and the pr environment whilst the PR is building to give quicker (and in the case of shared missing) feedback on terraform issues.
I also noted that the unit tests were being blocked by deployment, but had no dependency on AWS Infrastructure so I have removed that dependency reducing the time to the integration tests being playable from 24 minutes to 16, a saving of 8 minutes.
=> DDPB-3749 - Update ALB Response Alarms to static threshold

api/src/AppBundle/Service/ReportUtils.php, api/src/AppBundle/v2/Registration/Assembler/CasRecToOrgDeputyshipDtoAssembler.php, api/src/AppBundle/v2/Registration/DTO/OrgDeputyshipDto.php, api/src/AppBundle/v2/Registration/Uploader/OrgDeputyshipUploader.php, api/tests/AppBundle/v2/Registration/Uploader/OrgDeputyshipUploaderTest.php
Ensures we provide an accepted type to `OrgDeputyshipDto::setCourtDate()` so the org CSV upload doesn't fail when we get unexpected/blank dates.
Fixes DDPB-3757
During the Org CSV upload process we parse some dates that relate to the client and court order. We use a custom parsing function to do this in order to handle dates that don't explicitly include the century in the year (think 14 vs 2014/1914). When a Date doesn't parse correctly we're currently returning false but we should return null instead so the value can be set in the DTO. 
Additionally, this change centralises the error handling for missing essential data into a single function.
Getting this out quickly so the pro team can upload the CSV but I'll be making a follow-up ticket with expanded behat tests to include some dodgy …
=> Return null rather than false when dates dont parse

environment/ecr.tf, environment/scan.tf
An update to Clam has caused it to break. Reverting image version back to a previous working version.
Fixes DDPB-3778
=> DDPB-3778 - Updating clam image version

api/src/AppBundle/Entity/Repository/ClientRepository.php, api/src/AppBundle/FixtureFactory/UserFactory.php, api/src/AppBundle/v2/Assembler/ClientAssembler.php, api/src/AppBundle/v2/Assembler/UserAssembler.php, api/src/AppBundle/v2/DTO/ClientDto.php, api/src/AppBundle/v2/DTO/DeputyDto.php, api/src/AppBundle/v2/Transformer/ClientTransformer.php, client/src/AppBundle/Controller/Admin/Client/ClientController.php, client/src/AppBundle/Controller/Admin/IndexController.php, client/src/AppBundle/Entity/Client.php, client/src/AppBundle/Resources/translations/admin.en.yml
Fixes timeouts on the client details page and when searching for users by case number with a case reference linked to a client in a large Org.
Fixes DDPB-3781
As part of the audit logging refactor we had reverted to using the old client endpoint rather than v2. Testing locally with a large org (1000 client and 150 users) there were no issues but on prod we've witnessed timeouts so this suggests its more than the users and clients causing the slowdown. I'll put a ticket in the backlog to try to recreate the problem locally but this fix should get us back to a working state.
=> Revert to using v2 endpoint for client details

client/src/AppBundle/Resources/translations/admin-checklist.en.yml, client/src/AppBundle/Resources/views/Admin/Client/Report/checklistSubmitted.html.twig
Updates the content of the checklist submit confirmation banner to give case managers more confidence that the checklist is actually being sent to Sirius.
Fixes DDPB-3714
=> DDPB-3714: Update checklist submit confirmation message

client/docker/confd/templates/pool.conf.tmpl
Ensure that all session cookies have the Secure and HTTPOnly flags enabled.
Fixes DDPB-3557
Looking at the cookies we currently have, there seems to be only 1 session cookie, and these already have the Secure and HTTPOnly flags (See comments of [DDPB-3557](https://opgtransform.atlassian.net/browse/DDPB-3557)).
There seems to be no obvious declaration in the code where this cookie is instantiated. I have therefore added settings to our php.ini should ensure any further cookies we create will have the necessary headers.
https://www.php.net/manual/en/session.security.ini.php
=> DDPB-3557 - Confirm we use secure and http only cookies.

client/src/AppBundle/Controller/ManageController.php
We should keep the status in manage availability but we don't want the healthcheck to affect our uptime stats as it's not a vital part of our service and docs will just remain queued if it's down.
Fixes DDPB-3733
Don't return unhealthy status if it's just sirius that's down.
NA
=> DDPB-3733 do not fail healthcheck on sirius down

behat/tests/features-v2/deputy-management/deputy/edit-myself.feature, behat/tests/features/admin/01-admin.feature, behat/tests/features/admin/02-cross-checks.feature, behat/tests/features/pa/04-dashboard-client-profile/13-settings.feature, behat/tests/features/prof/04-dashboard-client-profile/13-settings.feature, client/Dockerfile, client/src/AppBundle/Form/ChangePasswordType.php, client/src/AppBundle/Resources/translations/validators.en.yml, client/src/AppBundle/Validator/Constraints/CommonPassword.php, client/src/AppBundle/Validator/Constraints/CommonPasswordValidator.php, client/tests/phpunit/Validator/Constraints/CommonPasswordValidatorTest.php
Stop users from using passwords that are too common by taking the top 100k known pwned passwords and making sure password is not in the list.
When we move to symfony 4 we should use the constraint that does this check automatically! It's cleverer than what we are doing.
Fixes DDPB-3555
Went back and forth on approach a bit. Initially I wanted the list in the database but in the end after realising the size of the list (tiny) I went for a hybrid approach of DLing file locally where it doesn't already exist or if it's older than 24 hours and using that for the comparison. The check takes milliseconds so seems fine doing it this way.
I created a new bespoke constraint and added some unit tests and behat tests to check it.
Constraints, unit testing constraints, (although not in the code, I …
=> DDPB-3555 add password validation for pwned passwords

client/src/AppBundle/Controller/Admin/AjaxController.php
Fixes the broken CSV upload.
Fixes DDPB-3816
We had reports that the CSV upload process was hanging in production. Looking in cloudwatch there was an error related to the Ajaxcontroller that gets called when splitting the CSV into chunks of 2000 rows - a class wasn't being injected into the controller function that required it. 
I've fixed the typehint now but the reason our tests didn't pick this up is all of the CSVs we upload are under 2000 rows long. As chunks are set at 2000 rows the Ajaxcontroller was never called in tests. I'm looking into writing a JS enabled test in behat to cover this off but want to get the fix out now so the Lay team can get the most recent lays added to the system.
=> DDPB-3816: Fix failing lay CSV upload

Makefile, api/app/DoctrineMigrations/Version247.php, client/src/AppBundle/Controller/FeedbackController.php, client/src/AppBundle/Form/FeedbackType.php, client/src/AppBundle/Form/Traits/HasTranslatorTrait.php, client/src/AppBundle/Resources/assets/javascripts/main.js, client/src/AppBundle/Resources/translations/feedback.en.yml, client/src/AppBundle/Resources/views/Feedback/index.html.twig, client/tests/phpunit/Form/FeedbackTypeTest.php
We had a limit of 1200 characters at the DB level for the feedback form
but did not apply the limit to the frontend. We now just increased the
DB character count to a lot more by changing the field to a TEXT field.
Also we added a honeypot method to the feedback form to try and stop
random (non-targeted) spam.
Issue DDPB-3786
For the honeypot trick basically we have a hidden field on the form that to a spambot would look like a normal field to fill in. If this field is filled in then we reject the submission and it could be potential spam.
Honeypot field in Symfony: https://www.strangebuzz.com/en/blog/implementing-a-honeypot-in-a-symfony-form
=> DDPB-3786: Handle larger text in the feedback form and prevent spam

.circleci/config.yml, docs/runbooks/PULL-REQUEST-PROCEDURE.md, environment/scripts/workspace_cleanup.sh, environment/workspace_cleanup.tf, shared/workspace-cleanup.tf
So we don't have to destroy environments as part of the pipeline and get left with random environments and loads of empty workspaces, we need a script that runs through them and destroys them.
Fixes DDPB-3645
Went for an approach of locking them for 24 hours. Although it says 24 hours this basically means that they will remain for this working day and the next as the job runs at midnight each night. If you want to extend the duration you can either rerun the whole pipeline, change the expiry in dynamo or probably the quickest is just rerun the protect bit of the pipeline again. 
The bulk of the work here was actually clearing up all our old workspaces. Manually went through them with the script to make sure everything was in a fit state... took ages..
NA
=> DDPB-3645 scheduled workspace cleanup

behat/tests/features/pa/03-report/04-submit-report.feature, behat/tests/features/prof/03-report/07-submit-report.feature, client/src/AppBundle/Controller/Report/ReportController.php, client/src/AppBundle/Resources/translations/report-submitted.en.yml, client/src/AppBundle/Resources/views/Ndr/Ndr/submitConfirmation.html.twig, client/src/AppBundle/Resources/views/Report/Report/submitConfirmation.html.twig
Changes the notification element to a banner element when submitting Reports and NDRs for all deputy types. Also removes the link at the bottom of the page to return to reports and replaces with a button link underneath the banner.
Fixes DDPB-3750
=> DDPB-3750: Success banner on deputy report submission

environment/s3.tf
We only have the main bucket that is of interest here. It already had versioning but needed logging
Fixes DDPB-3130
added logging and made versioning have better expiration rules
=> DDPB-3130 add logging bucket

api/app/config/parameters.yml, api/src/AppBundle/Controller/Report/ReportSubmissionController.php, api/src/AppBundle/Service/Stats/Query/Query.php, api/src/AppBundle/Service/Stats/StatsQueryParameters.php, api/tests/AppBundle/ControllerReport/ReportSubmissionControllerTest.php, client/app/config/parameters.yml, client/src/AppBundle/Form/Admin/ReportSubmissionDownloadFilterType.php
There was a bug where the DAT download was only the dates 1 day before
the endDate that was send in the form submission. This hopefully fixes
that
Issue DDPB-3818
=> DDPB-3818: Respect the to date when choosing a date period for DAT reports

api/src/Service/UserRegistrationService.php, client/src/EventSubscriber/DeputySelfRegisteredSubscriber.php, client/templates/Manage/api-collector.html.twig, client/tests/phpunit/EventSubscriber/DeputySelfRegisteredSubscriberTest.php
Removing some old court order code that was leftover that resulted in some registrations not completing and adding a missing send email listener for self-registration events.
Fixes DDPB-3852.
We clearly have some holes in our behat tests. The sooner we get on the rewrite the better.
=> DDPB-3852: Fix registration flow and add missing eventSubscriber

client/src/Controller/Report/DocumentController.php, client/templates/Report/Document/step2.html.twig, client/translations/report-documents.en.yml
When a user adds a file successfully as a document on the document upload page, they will see a green confirmation banner.
Fixes DDPB-3805
=> DDPB-3805b: Implement success message for file upload

api/Dockerfile, client/Dockerfile
Security checks using the existing symfony security check have ended at end of Jan for 3.x. Using suggested package instead until we upgrade to 4.x
=> DDPB-3871 fix out of date sec checker

shared/vpc_flow_logs.tf
Naming was inconsistent and as a resource hadn't been deleted properly anyway and is breaking main pipe, it's given me the excuse to name these with dashes instead of underscores.
=> fix bad inconsistent naming of vpc flow log

client/src/EventSubscriber/DeputySelfRegisteredSubscriber.php
Registration emails were still not being sent in dev and prod - turned out there was a missing class implementation on the event subscriber so the service was never tagged to be a subscriber.
Fixes DDPB-3852
=> DDPB-3852: Implement EventSubscriber for DeputySelfRegisteredSubscriber

api/src/Controller/StatsController.php, api/src/Controller/UserController.php, api/src/Entity/Repository/UserRepository.php, api/src/FixtureFactory/LoadTestFactory.php, api/src/TestHelpers/ClientTestHelper.php, api/src/TestHelpers/ReportSubmissionHelper.php, api/src/TestHelpers/ReportTestHelper.php, api/src/TestHelpers/UserTestHelper.php, api/tests/App/Controller/StatsControllerTest.php, api/tests/App/Controller/UserControllerTest.php, api/tests/App/Entity/Repository/ReportRepositoryTest.php, api/tests/App/Entity/Repository/UserRepositoryTest.php, api/tests/App/Entity/UserTest.php, client/src/Controller/Admin/StatsController.php, client/src/Service/Client/Internal/StatsApi.php, client/src/Service/Client/Internal/UserApi.php, client/src/Service/Csv/ActiveLaysCsvGenerator.php, client/tests/phpunit/Service/Csv/ActiveLaysCsvGeneratorTest.php
The active lay report was timing out on prod as there were approximately 23K Users being returned. This change streamlines the process to allow the full dataset to be returned.
Fixes DDPB-3886
I replicated creating a large dataset using a factory locally and running in a test multiple times. I backed up the test database and restored to the API database. We could look at building this functionality into our fixtures so we have a representative DB size to work with when we need to test anything with high loads.
=> DDPB-3886: Fix active lay report

api/config/services.yml, api/docker/confd/templates/parameters.yml.tmpl, environment/api_service.tf
Development is currently broken due to a missing env var from API. I'd somehow managed to get #595 through the pipeline despite the fact the env var `FIXTURES_ACCOUNTPASSWORD` didn't exists in the API service. 
I thought about adding some logic to determining which system environment to add this to but that seems overly complex considering the risk of having the env var there is pretty low. 
Fixes DDPB-3908.
=> DDPB-3908: Set fixtures password env var in api service

environment/disaster_recovery/kms.tf, environment/s3.tf, environment/s3_access_logs.tf, environment/terraform.tfvars.json, environment/variables.tf
Added all the digideps side for bucket replication to a backup account. The org infra side has already been merged in.
Fixes DDPB-2914
Tried the full setup in a PR on our side first to check everything lined up then pulled out the backup account stuff and opened a PR in org infra with it. 
Couple of things.. you need a filter setting to have two replication setups even if you don't use it. That was a bit of a gotcha. Also the whole dynamic for_each setup of all the vars to do per env setup on the org infra side (not in this PR) was a bit of learning to get it working as I wanted. We may want to remove dev or even preprod from the replication in the future but it's nice to have the option to replicate and proves it works through real envs before hitting prod.
=> DDPB-2914 add bucket backup replication

environment/backup.tf, environment/checklist_sync.tf, environment/document_sync.tf, environment/integration_test.tf, environment/reset_database.tf, environment/restore.tf, environment/restore_from_production.tf, environment/smoke_test.tf
Sort out permissions on vpc endpoints for CI jobs
Fixes DDPB-3920
Clearly when I did this originally regarding the fargate upgrade months ago I hadn't done the CI bits fully. This is now causing issues. This fixes it.
NA
=> DDPB-3920 fix missed vpc endpoint rules

wkhtmltopdf/Dockerfile
Fix python versions. Was actually gunicorn causing the issue but we can fix the other versions as well.
Fixes DDPB-3935
=> ddpb-3935 fix python versions as breaks on latest gunicorn

behat/tests/behat.yml, behat/tests/bootstrap/v2/common/AuthTrait.php, behat/tests/bootstrap/v2/common/BaseFeatureContext.php, behat/tests/bootstrap/v2/common/IShouldBeOnTrait.php, behat/tests/bootstrap/v2/common/ReportTrait.php, behat/tests/bootstrap/v2/common/UserDetails.php, behat/tests/bootstrap/v2/reporting/sections/ActionsSectionTrait.php, behat/tests/bootstrap/v2/reporting/sections/ReportingSectionsFeatureContext.php, behat/tests/features-v2/feedback/post-submission-feedback.report.feature, behat/tests/features-v2/reporting/sections/actions/actions.feature
Capture possible permutations around the actions section of the report form
Fixes DDPB-3474
After talking with Alex, he suggested that we should not use the old behat links. This was a slight challenge for some elements. Also he suggested not to use variables where possible (though in one instance it did just make total sense to use variables and this can be reused for all report sections).
As such an approach that seems sensible is having  specific code in the section trait that calls more generic functions in the reporting sections feature context.
I have tried where possible to navigate the app rather than just visiting urls. The purpose of this is to make sure the correct links are where we expect them on each page and work as expected. I did have one issue here..
I feel we could do …
=> DDPB-3474 actions section behat tests

Makefile, api/src/TestHelpers/BehatFixtures.php, api/src/TestHelpers/ClientTestHelper.php, api/src/TestHelpers/OrganisationTestHelper.php, api/src/TestHelpers/ReportTestHelper.php, behat/tests/behat.yml, behat/tests/bootstrap/v2/common/AlertsTrait.php, behat/tests/bootstrap/v2/common/BaseFeatureContext.php, behat/tests/bootstrap/v2/common/ErrorsTrait.php, behat/tests/bootstrap/v2/common/IShouldBeOnTrait.php, behat/tests/bootstrap/v2/common/IVisitTrait.php, behat/tests/bootstrap/v2/common/ReportTrait.php, behat/tests/bootstrap/v2/feedback/FeedbackTrait.php, behat/tests/bootstrap/v2/reporting/sections/DocumentsSectionTrait.php, behat/tests/bootstrap/v2/reporting/sections/ReportingSectionsFeatureContext.php, behat/tests/features-v2/feedback/post-submission-feedback.report.feature, behat/tests/features-v2/reporting/sections/actions/actions.feature, behat/tests/features-v2/reporting/sections/additional-information/additional-information.feature, behat/tests/features-v2/reporting/sections/contacts/contacts.feature, behat/tests/features-v2/reporting/sections/documents/documents.feature, behat/tests/features-v2/reporting/sections/documents/documents.org.feature, behat/tests/features-v2/reporting/sections/gifts/gifts.feature
Covers off the documents section of the report in new style behat tests.
Fixes DDPB-3476.
I've really doubled down on trying to make the BDD as understandable and domain-specific as possible in this ticket. Hopefully, I've got the balance right between step naming and asserting in the context files but wide open to feedback if things could be clearer.
I've also added our first professional fixture users in to pass a test on org user specific alerting. I've only used them to log in so far so we could find things aren't quite right when we come to use them for more involved tests but there's a basis to build all other org fixture users out from. We should also keep an eye on the time it takes to build out the fixtures between each scenario. I'm kind of on the fence with at the end of the …
=> DDPB-3476: Behat report sections - Documents

client/package-lock.json, client/package.json
Upgrading webpack to v5 seems to have broken JS features in IE for some of our users. Reverting to v4 here until we can work out the polyfills/reason behind the breakages.
Fixes DDPB-3940
Testing IE on mac sucks. We settled on a chrome tab extension called IETab but its far from ideal. Need to find a long term way of testing IE (most likely VMWare/Virtualbox).
=> DDPB-3940: Revert webpack

api/src/Migrations/Version250.php, api/tests/Fixtures.php, behat/tests/bootstrap/DbTrait.php
Getting rid of the team related tables and removing associations between clients and non-lay deputies.
Fixes DDPB-3956
We were alerted to a case of org members still seeing a client list even after being removed from the org. After further investigation, we found that the old mechanism for team members to view clients/reports was still in place (essentially using the same mechanism as lay deputies by associating the client with the team user in the deputy_case table).
We've already run the client association removal code on prod so this is just recording the fact in source control but the migration included here also drops the dd_team and user_team tables and constraints.
=> DDPB-3956: Remove final traces of teams and clear up team user client associations

api/src/Entity/Ndr/Ndr.php, api/src/TestHelpers/BehatFixtures.php, api/src/TestHelpers/ReportTestHelper.php, api/src/v2/Fixture/Controller/FixtureController.php, behat/tests/behat.yml, behat/tests/bootstrap/v2/common/BaseFeatureContext.php, behat/tests/bootstrap/v2/common/ElementSelectionTrait.php, behat/tests/bootstrap/v2/common/IShouldBeOnTrait.php, behat/tests/bootstrap/v2/common/PageUrlsTrait.php, behat/tests/bootstrap/v2/common/ReportTrait.php, behat/tests/bootstrap/v2/reporting/sections/AccountsSectionTrait.php, behat/tests/bootstrap/v2/reporting/sections/ActionsSectionTrait.php, behat/tests/bootstrap/v2/reporting/sections/AdditionalInformationSectionTrait.php, behat/tests/bootstrap/v2/reporting/sections/ContactsSectionTrait.php, behat/tests/bootstrap/v2/reporting/sections/DocumentsSectionTrait.php, behat/tests/bootstrap/v2/reporting/sections/GiftsSectionTrait.php, behat/tests/bootstrap/v2/reporting/sections/ReportingSectionsFeatureContext.php, behat/tests/features-v2/reporting/sections/accounts/accounts.feature, behat/tests/features-v2/reporting/sections/accounts/accounts.ndr.feature, behat/tests/features-v2/reporting/sections/gifts/gifts.feature, client/package.json, client/templates/Macros/macros.html.twig, client/templates/Ndr/Ndr/declaration.html.twig, client/templates/Report/Report/declaration.html.twig, client/translations/validators.en.yml
Add the behat tests for accounts.
EDIT: Added scaffolding for NDRs and applied them to this test. Couldn't quite bring myself to go back and apply to the other features as part of this ticket but will do in the next!
About NDR: As the paths should react largely the same (though it turns out they do use different templates sometimes...), I have avoided duplicating all the tests by simply making the first portion of the path a variable everywhere and just adding differences expected between NDR and report into the existing bootstrap code files.
Fixes DDPB-3478
We go through and do all the possible permutations of using the accounts section whilst clearly defining the scope of the tests and not straying into all the areas that accounts touch (gifts, moving money ect)...
I believe I have …
=> Ddpb 3478 - Add accounts behat tests

.pre-commit-config.yaml, Makefile, api/Dockerfile, api/composer.json, api/phpstan.neon, api/scripts/apiunittest.sh, behat/tests/bootstrap/v2/common/BaseFeatureContext.php, client/Dockerfile, client/composer.json, client/phpstan.neon, client/scripts/client-unit-tests.sh, docker-compose.override.yml, phpstan.neon
Adding PHPStan to pre-commit hooks to ensure any new code we write has some base level of static analysis applied. 
I've also formalised running PHPStan under a couple of makefile commands so we can get depressed about the thousands of errors its spits out. At some point, it would be nice to tackle them level by level but for now, having the new code we've written checked is a good first step.
Fixes DDPB-3961.
=> DDPB-3961: Add PHPStan to pre-commit

client/src/Service/DocumentSyncService.php, client/tests/phpunit/Service/DocumentSyncServiceTest.php
Removes whiteapace during document syncing process to take into account users who uploaded documents for a report prior to releasing the code that sanitises the filename on document upload.
Fixes DDPB-3962
Unfortunately, we’re only able to do half of this ticket. Being able to add a missing file extension requires the actual file the user has uploaded. We made the switch from sending the document data to the S3 reference a while back to in order to add missing file extensions we’d need to revert to pulling the file down from S3 which wouldn’t be a good move (mainly as this was leading to some out of memory errors for larger files).
To at least get some value out of the ticket I've ensured there is a clear error message showing the file needs to be manually synced to Sirius if there is a …
=> DDPB-3962: Remove whitespace between filename and extension during document syncing

api/Dockerfile, behat/Dockerfile, client/Dockerfile
No longer need to pin composer. Fix security vulnerability in composer.
Fixes DDPB-3977
Needed extra argument to ignore platform req for php as otherwise it expects php8
=> DDPB-3977 update composer to latest version

api/src/TestHelpers/ReportTestHelper.php, api/tests/Behat/behat.yml, api/tests/Behat/bootstrap/v2/Common/IShouldBeOnTrait.php, api/tests/Behat/bootstrap/v2/Common/IVisitFrontendTrait.php, api/tests/Behat/bootstrap/v2/Common/PageUrlsTrait.php, api/tests/Behat/bootstrap/v2/Common/ReportTrait.php, api/tests/Behat/bootstrap/v2/Reporting/Sections/MoneyOutSectionTrait.php, api/tests/Behat/bootstrap/v2/Reporting/Sections/MoneyOutShortSectionTrait.php, api/tests/Behat/bootstrap/v2/Reporting/Sections/ReportingSectionsFeatureContext.php, api/tests/Behat/features-v2/reporting/sections/money-out/money-out-short.feature, api/tests/Behat/features-v2/reporting/sections/money-out/money-out.feature
Money out long section behat tests as run on pfa high assets
Fixes DDPB-3482
This one was a tricksey one so it twas. Because of the extra subsection type layout in the summary page, it made any sort of looping a bit painful. Worked it out eventually and using the expected helper function didn't make this any more difficult really. Just had to think about the structure of the objects...
Nothing really except that these ones are a pain.. not sure if the next one of these type will be much quicker. Hopefully a bit now we have a template...
=> Ddpb 3482 - money out behat tests

environment/cloudwatch_queries.tf, environment/versions.tf
Persists a couple of common queries we use when filtering cloudwatch logs in the insights view.
Fixes DDPB-4003
=> DDPB-4003: Add cloudwatch queries

api/tests/Behat/behat.yml
Increases contrast for both light and dark terminals when outputting behat text.
Before:
After:
=> Tweak behat colours

docker-compose.yml, environment/scan.tf, wkhtmltopdf/Dockerfile
Despite it working flawlessly and passing all the tests and generating lovely pdfs, the alerts brought up some interesting behaviour. 
Turns our our new alpine version uses a lot more cpu and memory and so dies after a while on smaller specced services. Couldn't guarantee the behaviour on prod and don't really want to just up the services. Also it seems to take a bit longer to generate PDFs. Not hugely longer but enough to give us response time alerts from manage/availability...
Tried a few things...
tried to make my own binary work in alpine.. failed. Tried to up glibc version but it's super baked into buster. Tried to use a python slim debian bullseye image but none existed so made one from scratch. That worked but it still had lots of sec vulnerabilities so not a huge point there.. I …
=> Revert wkhtmltopdf changes

api/tests/Behat/behat.yml, api/tests/Behat/bootstrap/v2/ClientManagement/ClientManagementTrait.php, api/tests/Behat/bootstrap/v2/Common/AuthTrait.php, api/tests/Behat/bootstrap/v2/Common/BaseFeatureContext.php, api/tests/Behat/bootstrap/v2/Common/FixturesTrait.php, api/tests/Behat/bootstrap/v2/Common/FormFillingTrait.php, api/tests/Behat/bootstrap/v2/Common/IShouldBeOnAdminTrait.php, api/tests/Behat/bootstrap/v2/Common/IVisitAdminTrait.php, api/tests/Behat/bootstrap/v2/Common/ReportTrait.php, api/tests/Behat/bootstrap/v2/Common/UserDetails.php, api/tests/Behat/bootstrap/v2/Helpers/FixtureHelper.php, api/tests/Behat/bootstrap/v2/ReportManagement/ReportManagementFeatureContext.php, api/tests/Behat/bootstrap/v2/ReportManagement/ReportManagementTrait.php, api/tests/Behat/features-v2/report-management/report-management.feature, client/templates/Admin/Client/Client/details.html.twig
Covers the report management section of the app on the admin side.
Fixes DDPB-3947
I took the opportunity to:
* Drop out a bunch of properties from `FixtureHelper` that was a hangover from when behat was separate to API. We were just setting them and then passing them to a function on the next line down so seemed pointless.
* Make some of the fixture users more explicit in their naming for report types
* Use DateTime objects for UserDetails properties rather than strings to expand their usage in tests
* Fixed the pesky en dash used in the report period on client overview page
=> DDPB-3947: Behat rewrite - report management

api/tests/Behat/behat.yml, api/tests/Behat/bootstrap/v2/Common/AlertsTrait.php, api/tests/Behat/bootstrap/v2/Common/AssertTrait.php, api/tests/Behat/bootstrap/v2/Common/BaseFeatureContext.php, api/tests/Behat/bootstrap/v2/Common/ElementSelectionTrait.php, api/tests/Behat/bootstrap/v2/Common/INavigateToAdminTrait.php, api/tests/Behat/bootstrap/v2/Common/IShouldBeOnAdminTrait.php, api/tests/Behat/bootstrap/v2/Common/IVisitAdminTrait.php, api/tests/Behat/bootstrap/v2/Common/PageUrlsTrait.php, api/tests/Behat/bootstrap/v2/Helpers/FixtureHelper.php, api/tests/Behat/bootstrap/v2/UserManagement/UserManagementFeatureContext.php, api/tests/Behat/bootstrap/v2/UserManagement/UserManagementTrait.php, api/tests/Behat/features-v2/user-management/create-user.feature, api/tests/Behat/features-v2/user-management/edit-user.feature, api/tests/Behat/features-v2/user-management/search-user.feature, api/tests/Behat/features/admin/08-deputy-search.feature, client/src/Entity/User.php, client/src/Form/Admin/SearchType.php, client/templates/Admin/Index/index.html.twig, client/translations/admin-clients.en.yml
Create user administration behat tests (not file upload of users though)
Fixes DDPB-3942
Fairly standard approach. A few caveats though:
- When we edit users, the super user edits each type but for admin and manager I decided it would take too long so just checked they have the edit option available.
- Same for checking the fields. I only go into the view on a lay rather than each as it's the same mechanism (though i do check all of them in the search window for updates).
Picked up a few mistakes in the templates as I was doing this. Fixed them. 
NA
=> DDPB-3943 behat tests for user administration

client/src/Service/Client/Sirius/SiriusApiGatewayClient.php, client/tests/phpunit/Service/Client/Sirius/SiriusApiGatewayClientTest.php
believe timeouts are causing healthcheck to fail even though we're seeing 200s despite sirius being down (as we had expected and fixed in a previous ticket months ago)
Pretty sure that going for timeouts under 2 secs is the way to go here. Doesn't really matter if occasionally says it's offline when it isn't as this doesnt affect our availability but it will stop us getting alerts when sirius is down and we're not (I hope).
=> tweak to sirius request timeout

api/scripts/localstack-init.php, client/scripts/localstack-init.php, client/src/Controller/Ndr/NdrController.php, client/src/Controller/Report/ReportController.php, client/src/Service/ParameterStoreService.php, environment/front.tf, environment/parameters.tf
Adding a date-based feature flag to allow developers to show/hide certain features and functionality behind the flag.
Using a date as to accommodate certain scenarios such as hiding questions on reports which have submitted before said date.
Fixes DDPB-4038
Update terraform to create additional feature flag in AWS Parameter Store.
Update AWS IAM Policy to allow reading of variable to role.
Update scripts to create flag for localstack.
Add feature flag to Parameter Store Service.
Update Report and NDR controllers to pull in feature flag.
Not only do you need to create a feature flag in `parameters.tf`, but you will also need to ensure you update the policy for the aws role to allow for reading in `front.tf`.
=> Added date feature flag for additional benefits questions

.circleci/config.yml
Mistakes were made.. we need to specify environments for all the tasks running against main. It uses the WORKSPACE env var which gets set as tf_workspace to decide what environment to use. It does this with sh script that checks if it's been set so we can have dynamic envs. In main it needs to be set.
=> DDPB-4092c specify environment for main build

api/src/Entity/Report/ClientBenefitsCheck.php, api/src/Entity/Report/IncomeReceivedOnClientsBehalf.php, api/src/Entity/UserResearch/UserResearchResponse.php, api/src/Migrations/Version254.php, docs/ADDING_REPORT_SECTIONS.md
Creates the entities and migration for the new form section 'Benefits check'.
Fixes DDPB-4062
Following on from comments made in various retros and health checks I've ensured the ids of the two entities are UUIDs to protect against users trying to access resources incrementally. 
There may be some tweaks to the entities when we come to implement the forms - especially `ClientBenefitsCheck::whenLastCheckedEntitlement` as this can be either a string or DateTime so some type of conversion will need to happen after checking if the value is a DateTime (e.g. `DateTime::createFromFormat('m/Y', '01/2021')`).
The readme I added is a first stab and will evolve as we implement the rest of this form section.
=> DDPB-4062: Create the entities and migrations for the new report section

client/config/services.yml, client/src/Twig/ComponentsExtension.php, client/src/Twig/FormFieldsExtension.php, client/templates/Components/GoogleAnalytics/hiddenEvent.html.twig, client/templates/Org/Index/dashboard.html.twig, client/templates/Report/Report/index.html.twig, client/tests/phpunit/Twig/ComponentsExtensionTest.php
Following on from recent conversations we needed a way to track how many of our users have JS disabled in their browsers so we can make more informed decisions on how we design the app. This adds tracking for for lays and org users when they log in so we can breakdown how many users there are in Google Analytics.
=> Adds javascript disabled tracking for logged in users

api/scripts/localstack-init.php, client/scripts/localstack-init.php, client/src/Service/ParameterStoreService.php, environment/front.tf, environment/parameters.tf
Adding a feature flag to allow developers to show/hide certain features and functionality behind the flag.
Fixes DDPB-4030
Update terraform to create additional feature flag in AWS Parameter Store.
Update AWS IAM Policy to allow reading of variable to role.
Update scripts to create flag for localstack.
Add feature flag to Parameter Store Service.
=> DDPB-4030 - Add feature flag for paper reports

.circleci/config.yml
Our weekly integration test run looks to have been broken for a long time - https://app.circleci.com/pipelines/github/ministryofjustice/opg-digideps/7657/workflows/96b587e6-5aeb-4569-8632-054b7937d195. It looks like we're missing a required step to ensure `layer.tar` is available when we run an apply so adding in now.
@xaithe @jamesrwarren - let me know if I've oversimplified this solution 😅
=> Ensure we have layer.tar ready for apply integration

.circleci/config.yml
Dropping this step from the pipeline as no one is using it.
=> DDPB-4162: Drop optional destroy from CI pipeline

client/templates/Admin/Client/Report/partials/_money-in-and-out.html.twig, client/translations/common.en.yml
Currently on the checklist, accounts are not flagged to show whether they are joint accounts or not.
This fix adds in a new column to the account balance table to flag joint accounts.
Fixes DDPB-4077
=> DDPB-4077 - Show joint accounts on the checklist 

api/tests/Behat/behat.yml, api/tests/Behat/bootstrap/v2/ServiceHealth/ServiceHealthFeatureContext.php, api/tests/Behat/features-v2/service-health/external-dependecy-checks.feature, client/config/services.yml, client/frontend.env, client/govuk-notifications.yaml, client/src/Service/Availability/RedisAvailability.php, docker-compose.yml
Fixes the Redis health check on /manage/availability along with adding a missing integration test for overall service health.
Fixes DDPB-4171
It turns out Redis wasn't broken - the RedisAvailability class was still using the old skool approach of getting Redis directly from the container after it was built rather than via dependency injection.
As a side adventure (and in order to make the integration tests pass locally) I drafted up a super quick open API spec for the two Notify endpoints we use in the app so we could have a real mock Notify to call out to. It could be a little more dynamic but for the purpose of getting the integration tests to pass it's serviceable! The logic is a little backwards in that we only ever provide the base URI locally via frontend.env. If that env var is …
=> DDPB-4171: Fix redis and add service health integration tests

client/templates/Report/Formatted/formatted_body.html.twig
We're showing the new report section on report previews and PDFs as we check if the report contains the `moneyIn` section rather than `clientBenefitsCheck`.
Fixes DDPB-4173.
Copy and paste is rarely a good thing.
=> DDPB-4173: Ensure benefits check is required in formatted report rather than money in

api/Dockerfile, api/composer.json, api/composer.lock, client/Dockerfile
Fixes https://nvd.nist.gov/vuln/detail/CVE-2021-42383 by bumping busybox to 3.14 (hopefully).
Fixes DDPB-4170
=> DDPB-4170: Bump PHP alpine images to use busybox v3.14

Makefile, docker-compose.override.yml, docker/install-composer.sh
As part of #731 I got sick of having to either switch PHP version locally or manually install composer each time I exec-ed into a container in order to install or update packages so I've added a couple of helper commands to achieve this.
=> Simplify composer tasks

Makefile, api/src/Controller/AuthController.php, api/src/Entity/User.php, api/tests/Unit/Controller/AuthControllerTest.php, client/src/Controller/SettingsController.php, client/tests/phpunit/Service/Client/Internal/UserApiTest.php
Remove password hashes from being returned in an API response that holds user data. There was 1 issue with this where when a user changes their password it would no longer log them out afterwards. To solve this we just redirect the user to the logout page after submitting a password change and the form is valid
Fixes DDPB-3884
=> [DDPB-3884] Remove password hashes from api responses

.pre-commit-config.yaml, api/src/Entity/Client.php, api/tests/Behat/bootstrap/v2/ClientManagement/ClientManagementTrait.php, api/tests/Behat/features-v2/client-management/admin/discharge.lay.feature, api/tests/Behat/features-v2/client-management/admin/discharge.org.feature, client/templates/Admin/Client/Client/details.html.twig
In the templates for the org client details page we hide the button for discharging a deputy behind a check on if a named deputy is associated with the client. While this makes logical sense we have over 7000 deputies without a named deputy associated with them since we dropped the named deputy table and rebuilt via the CSV. The reason behind this high number is due to the fact we don't remove a client/deputy from digideps when they drop off the CSV. This means in the rare cases where auto discharge doesn't happen on CSV upload we are unable to discharge a deputy and allow a new deputy to be associated with a client.
This change moves the discharge deputy button outside of the check on named deputy so we can discharge when needed. This may be a little confusing for users so we should link …
=> DDPB-3851: Allow discharge of org deputies without associated named deputies

api/tests/Behat/run-tests-parallel.sh, client/Dockerfile, client/composer.json, client/composer.lock, client/src/Twig/AssetsExtension.php, client/src/Twig/ComponentsExtension.php, client/templates/Admin/Client/Client/details.html.twig
During the PHP upgrades, I noticed we were requiring some dependencies in the main require stanza when they should be in the dev-dependencies stanza. I also took the opportunity to apply the latest package updates which created a breaking change for some old twig functions and syntax we were using.
I also experimented with removing the `gd` extension as I've never understood what we use it for (image processing seems to be encapsulated in the PDF service we use). Tests are all passing so I'm assuming it was an old dependency that was never removed once we stopped using it.
Fixes DDPB-4185.
=> DDPB-4185: Reorganise, remove gd extension and bump client dependencies

environment/admin_elb.tf, environment/front_elb.tf
Our current TLS listeners on our load balancers have some weak or insecure cypher suites.
To remove these, we have updated the listener to use a more update to date version: `ELBSecurityPolicy-FS-1-2-Res-2020-10`
This listener contains no weak or insecure policies.
Fixes DDPB-4138
Updated ssl_policy on both Frontend and Admin ELBs to use the new listener.
Tested the changes on [BrowserStack](https://live.browserstack.com/) to confirm that the [browsers we should be compatible with](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices) are working as expected.
Development branch is publicly accessible, which meant it was really easy to test against using BrowserStack. Possible to make use of the dev branch more often for tickets like this.
=> DDPB-4138 - Update TLS 1.2 to remove out of date cypher suites

client/src/Service/File/FileNameFixer.php, client/src/Service/File/S3FileUploader.php, client/tests/phpunit/Service/File/FileNameFixerTest.php, client/tests/phpunit/Service/File/S3FileUploaderTest.php
An output of the IT health check identified a vulnerability with our file upload service, where users could potentially provide malicious filenames, that could be executed by our app. This PR will sanitise filenames to ensure this cannot happen.
Fixes DDPB-3880
We were already manipulating some filenames as part of the S3 uploader, so we extended the functionality in this class to remove and replace suspicious characters.
=> DDPB-3880: Filename sanitisation

api/tests/Behat/bootstrap/v2/Reporting/Sections/MoneyOutSectionTrait.php, api/tests/Behat/features-v2/reporting/sections/money-out/money-out.feature
Occasionally when running a build, this particular test can sometimes fail.
It seems this is as a result of the steps falling out of sync with the browser, as the usual error message refers to the test step expecting the browser to be on a certain page and the browser actually being on a different one.
This ticket is to try and solve this issue.
Fixes DDPB-4190
Ran this test a few times with various number of steps, and it did seem at a higher number of steps the error was more likely to occur.
Although it would be nice to test every type of money out payment as we currently do, all the types use the same layout and so just testing a few should prove the pages work as expected.
_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about …
=> DDPB-4190 - Fix Scenario: A user adds one of each payment type

api/docker/confd/templates/app.conf.tmpl
Enforces TLS2 or 3 as a minimum and http2. I've been struggling to test this locally due to our self signed certificate returning an error when I curl with some tls options set using `curl -I -v --tlsv1.2 --tls-max 1.2 https://localhost:8090`. As the API is only available to services with AWS I can't run an SSL check on it from the open web. Everything is still working so I'm not too worried about misconfiguration, I just can't tell if this has fixed the problem 🤷 
Fixes DDPB-4138.
This [config generator](https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=intermediate&openssl=1.1.1d&guideline=5.4) was very useful in determining what to set for a broad range of compatibility.
=> DDPB-4138: Enforce TLSv1.2 as a minimum

client/assets/scss/digideps/_sections.scss, client/assets/scss/digideps/_tags.scss, client/templates/Macros/macros.html.twig, client/templates/Report/ClientBenefitsCheck/_answers.html.twig
Fixes a couple of visual issues with the new benefits section:
* Ensures status tags remain on one line
* Adds spacing to edit/remove links (and moves to macro)
Fixes DDPB-4188, DDPB-4207
=> DDPB-4188, DDPB-4207: New client benefits section markup fixes

api/src/Controller/StatsController.php, api/src/Repository/UserRepository.php, api/tests/Behat/bootstrap/v2/ACL/ACLTrait.php, api/tests/Behat/bootstrap/v2/Analytics/AnalyticsTrait.php, api/tests/Behat/bootstrap/v2/Common/IShouldBeOnAdminTrait.php, api/tests/Behat/bootstrap/v2/Common/IVisitAdminTrait.php, api/tests/Behat/bootstrap/v2/Common/PageUrlsTrait.php, api/tests/Behat/features-v2/acl/admin/super-admin-only.feature, api/tests/Behat/features-v2/analytics/analytics.feature, api/tests/Unit/Entity/Repository/UserRepositoryTest.php, client/src/Controller/Admin/StatsController.php, client/src/Service/Client/Internal/StatsApi.php, client/templates/Admin/Stats/metrics.html.twig, client/templates/Admin/Stats/reports.html.twig, client/templates/Admin/Stats/userAccountReports.html.twig, client/translations/admin-metrics.en.yml
The JML team need retention data on Digideps user accounts, so that we can help form a security process for leavers and movers. 
Fixes DDPB-4186
- Created a new reports page (only accessible for super admins) that enable admins to view a summary of the current admin account metrics based on the requested search criteria. 
- Also moved the existing links from the button menu to the reports page to avoid overloading the existing dropdown menu.
=> DDPB 4186 - Report for admin accounts (Joiners, Movers, Leavers) 

api/tests/Behat/bootstrap/v2/Common/IShouldBeOnFrontendTrait.php, api/tests/Behat/bootstrap/v2/Common/ReportTrait.php, api/tests/Behat/features-v2/report-submission/submitting-a-report.feature, api/tests/Behat/features-v2/report-submission/submitting-a-report.ndr.feature, client/assets/scss/digideps/formatted_report/_main.scss, client/templates/Macros/macros.html.twig, client/templates/Ndr/Ndr/_header.html.twig, client/templates/Ndr/Ndr/_pdf_download_link.html.twig, client/templates/Ndr/Ndr/_review_buttons.html.twig, client/templates/Ndr/Ndr/declaration.html.twig, client/templates/Ndr/Ndr/overview.html.twig, client/templates/Ndr/Ndr/review.html.twig, client/templates/Report/Report/_pdf_download_link.html.twig, client/templates/Report/Report/_review_buttons.html.twig, client/templates/Report/Report/declaration.html.twig, client/templates/Report/Report/review.html.twig, client/translations/common.en.yml, client/translations/ndr-overview.en.yml, client/translations/report-display.en.yml
A pattern has emerged that shows deputies are having trouble submitting their annual reports and NDRs. 
They either: 
mistakenly believe they have submitted their report when they haven't and the report ends up late (and OPG has to chase them)
make unnecessary contact with OPG to ask for help submitting the report 
Fixes DDPB-3832
- Followed report prototype - https://www.figma.com/proto/SGISRCgqfPNJnxwlh98Y6Q/Digideps-LAY-DEPUTY?node-id=203%3A1384&scaling=min-zoom&page-id=0%3A1 
- Applied the above to both ndr and reports
- Created a 'submitting a report' feature test
=> DDPB-3832: Format the report review page to make it easier to submit a report 

api/tests/Behat/features-v2/contact-details/contact-details.feature, api/tests/Behat/features-v2/report-submission/document-synchronisation.feature, api/tests/Behat/features-v2/report-submission/report-submission.feature, api/tests/Behat/features-v2/reporting/sections/gifts/gifts.feature
After working on the filename sanitisation ticket (#751) the behat tests for documents were failing locally. After investigation, it turned out we had 4 feature files we didn't have tagged properly to run in CI. This ticket adds missing tags and fixes the document sync tickets.
For behat feature tests to run in CI the `Feature` step needs to be tagged with `v2` and one of `v2_admin`, `v2_reporting_1` or `v2_reporting_2`. We should probably come up with a way to enforce this or come up with a more elegant solution to chunking up the tests into groups.
=> Fix document tests and ensure all tests run in CI

environment/check_csv_uploaded.tf
Adding in S3 permissions to security group to fix command.
Fixes DDPB-4169
=> Added S3 back to CSV uploaded security command

api/src/Controller/UserResearchController.php, api/src/Entity/User.php, api/src/Repository/UserResearchResponseRepository.php, api/tests/Unit/Entity/Repository/UserResearchResponseRepositoryTest.php, api/tests/Unit/Fixtures.php, client/src/Controller/Admin/StatsController.php, client/src/Service/Client/Internal/UserResearchApi.php, client/src/Service/Csv/UserResearchResponseCsvGenerator.php, client/tests/phpunit/Service/Csv/UserResearchResponseCsvGeneratorTest.php, client/translations/admin-metrics.en.yml
As we were working with hydrating full models and returning them from the API to the frontend, our API was timing out whenever more than a day or two of reports was selected. This change returns an array of raw data in JSON that we manually parse into the CSV on the frontend.
Fixes DDPB-4175
From some manual testing it looked like the slowdown was in Doctrine hydrating the objects fully to then turn back into JSON. We now skip this step and just return the raw data. I tested this locally with 10000 user research responses and it was returning the CSV is around 3 seconds. Our timeout for the API is 20 seconds so we should be able to go comfortably above this without timing out.
Unfortunately, I wasn't able to come up with a way for testing this without having a very slow running test. To …
=> DDPB-4175: Return JSON for report rather than whole objects, fix CSV download

environment/versions.tf, shared/cloud9.tf, shared/versions.tf
- DDPB-4245 - upgrade aws provider
- DDPB-4245 - give breakglass read/write for cloud9
=> DDPB-4245 - add breakglass read/write to cloud9 instances

shared/cloud9.tf, shared/variables.tf
Handle Cloud9 access programatically
Fixes DDPB-4245
The "cloud9_users" list in `shared/variables.tf` is iterated through in the `aws_cloud9_environment_membership` block in `shared/cloud9.tf`, assigning read/write c9 access to each listed user. User name has to be the same as AWS
=> DDPB-4245 - Cloud9 memberships

.circleci/config.yml, api/tests/Behat/features-v2/report-submission/document-synchronisation.feature, api/tests/Behat/features-v2/reporting/sections/documents/documents.feature
I remember now why we disabled the document behat tests. As the tests involve running a command that changes the status and triggers syncing when running these tests in parallel it can cause them to fail randomly.
We should always aim to be able to run tests in isolation but given this is an app-wide command that's run I'm not sure how to isolate them. At least this way we still get the coverage and can have reliable tests.
If anyone else has suggestions let me know.
=> Run document tests in sequence as paralell running makes flaky tests

.circleci/config.yml
The images we're using in CI for PHP and Golang are about to be out of support. This bumps to the newer maintained versions for both.
Fixes DDPB-4280
=> DDPB-4280: Upgrade circleCI images to next gen versions

.circleci/config.yml
Due to some [deprecations](https://discuss.circleci.com/t/github-ssh-deprecation-information-resolutions/42887) in CircleCI the use of RSA SSH will stop working with certain images. From investigation, it appears this could only impact us on our pa11y and cross-browser tests. This change updates the machine images to use to the newest ubuntu images that have the required tools.
Fixes DDPB-4281.
=> DDPB-4281: Update from classic image to ubuntu image

api/src/Entity/Ndr/MoneyReceivedOnClientsBehalf.php, api/src/Entity/Report/MoneyReceivedOnClientsBehalf.php, api/src/Migrations/Version262.php
As part of expanding the new benefits section we added a field to record where money was received from. The migration to create the new column ran fine locally and in envs where the DB was dropped and created but in preproduction we have some existing rows in the DB that would have NULL values in this column post migration. This change removes the DB constraint and relies on code constraints instead to allow the migration to run.
Fixes DDPB-4286
=> DDPB-4286: Allow null values for whoReceivedMoney to support migrations

api/src/Controller/StatsController.php, api/src/Entity/CasRec.php, api/src/Entity/Ndr/AssetProperty.php, api/src/Entity/Ndr/Ndr.php, api/src/Entity/Report/AssetProperty.php, api/src/Entity/Report/Report.php, api/src/Repository/NdrRepository.php, api/src/Repository/ReportRepository.php, api/tests/Behat/bootstrap/v2/Helpers/FixtureHelper.php, api/tests/Behat/bootstrap/v2/ReportManagement/ReportManagementTrait.php, api/tests/Unit/Entity/CasRecTest.php, client/src/Controller/Admin/StatsController.php, client/src/Entity/CasRec.php, client/src/Entity/Report/Report.php, client/src/Entity/ReportInterface.php, client/src/Service/Client/Internal/StatsApi.php, client/src/Service/Csv/AssetsTotalsCSVGenerator.php, client/templates/Admin/Stats/reports.html.twig, client/translations/admin-metrics.en.yml
OPG require a report showing the total value of liquid and non-liquid assets managed in digideps broken down by type. This change adds a CSV download link to the metrics admin page showing the values.
Fixes DDPB-4285
I started to just write an SQL query for this report but it was getting complex once I started to try to exclude NDRs that had already been submitted so I pivoted to creating a downloaded report via code.
Given the tight deadlines I've not TDDed this or written tests but have carried out some manual checks to ensure we're getting back the expected figures. We should play a follow-up ticket to add tests to this once we have the time next week.
=> DDPB-4285: Add report to metrics page for total liquid and non-liquid assets

.prettierrc.json, api/config/services.yml, api/src/Controller/StatsController.php, api/src/Entity/Ndr/Asset.php, api/src/Entity/Ndr/BankAccount.php, api/src/Entity/Report/Asset.php, api/src/Repository/AssetRepository.php, api/src/Repository/BankAccountRepository.php, api/src/Repository/NdrAssetRepository.php, api/src/Repository/NdrBankAccountRepository.php, api/src/Repository/NdrRepository.php, api/src/Repository/ReportRepository.php, api/tests/Unit/Entity/Repository/UserResearchResponseRepositoryTest.php, api/tests/Unit/Fixtures.php
The original code to generate a report of asset values relied on iterating over PHP entities and summing values. This worked fine locally with a dataset of 10 reports and NDRs but took too long to response once run on prod. This change pushes the summing logic down into DQL to make sure we can actually run the report on prod.
Fixes DDPB-4291.
Having relied on ORMs so heavily in the past whenever I get a data ticket I tend to avoid trying to come up with a DQL/SQL solution as its out of my comfort zone. This (along with previous time out bugs) should serve as a reminder that its not scary and SO is my friend 😂 . Interstingly this solution took around the same amount of time to come up with compared to the original.
Also, test against large datasets!
=> DDPB-4291: Fix assets report

api/src/Entity/Report/Report.php
We've had the new benefits check section toggled off while developing for full reports. This change enables the section for all reports (plus 60 days from the date set here). It's already live for NDRs.
Fixes DDPB-4278.
=> DDPB-4278: Set client benefits section section release date to 16 March 2022

api/src/Controller/Report/ReportController.php, api/src/Entity/SynchronisableTrait.php, api/src/Repository/ReportRepository.php, api/tests/Behat/bootstrap/v2/ClientManagement/ClientManagementTrait.php, api/tests/Behat/bootstrap/v2/Common/IVisitAdminTrait.php, api/tests/Behat/bootstrap/v2/Common/PageUrlsTrait.php, api/tests/Behat/bootstrap/v2/Reporting/Admin/ReportingAdminFeatureContext.php, api/tests/Behat/bootstrap/v2/Reporting/Admin/ReportingChecklistTrait.php, api/tests/Behat/features-v2/report-checklist/checklist-synchronisation.feature, client/src/Controller/Admin/BehatController.php, client/src/Controller/Admin/Client/ReportController.php, client/templates/Admin/Client/Report/checklist.html.twig, client/templates/Admin/Client/Report/sidebar/_statuses.html.twig, client/translations/common.en.yml
Following some reports from case managers on checklists failing to sync we investigated and noticed that checklists linked to a report belonging to a discharged deputy (e.g. client soft deleted) were throwing errors during the sync process. This change allows checklists with discharged deputies to be synced, adds a sync status to the checklist and covers the feature in behat tests.
Fixes DDPB-4288.
=> DDPB-4288: Allow checklists linked to a discharged client to be synced with Sirius

.circleci/config.yml, api/src/Controller/Report/ReportController.php, api/tests/Behat/bootstrap/v2/Reporting/Admin/ReportingChecklistTrait.php, client/src/Command/ChecklistSyncCommand.php, client/src/Command/DocumentSyncCommand.php, client/src/Controller/Admin/BehatController.php, client/src/Service/ChecklistSyncService.php, client/src/Service/Client/Internal/ReportApi.php, client/src/TestHelpers/ChecklistTestHelper.php, client/tests/phpunit/Command/ChecklistSyncCommandTest.php, client/tests/phpunit/Service/ChecklistSyncServiceTest.php, environment/parameters.tf
Turns out re-enabling the softdeleteable filter in a foreach loop stops records with a deleted client from being returned in time. I've dropped this line and tests are passing again (must have gamed the CI tests somehow).
Fixes DDPB-4296.
=> DDPB-4296: Drop enabling softdeleteable filter in loop

api/src/Entity/Ndr/MoneyReceivedOnClientsBehalf.php, api/src/Entity/Report/MoneyReceivedOnClientsBehalf.php
An NDR user reported they were unable to submit their NDR and after some investigation, it was clear this was linked to the recent changes to the client benefits check section. This section was live for NDR Users in February but we added a field to the section in March which was nullable at DB level but not app level. This resulted in application errors being thrown when users logged in. 
Fixes DDPB-4299
Allowing this value to be null fixes the issue.
=> DDPB-4299: Allow whoReceivedMoney to be null

.circleci/config.yml
We scale our AWS ECS tasks for API and frontend services just before running our integration tests. We skip scaling admin though and given our very flaky test runs of late it looks like bumping admin has helped somewhat in branch env test runs.
=> Also scale admin in tests

api/tests/Behat/bootstrap/v2/ACL/ACLTrait.php, api/tests/Behat/bootstrap/v2/AppNotification/AppNotificationTrait.php, api/tests/Behat/features-v2/acl/admin/super-admin-only.feature, api/tests/Behat/features-v2/app-notification/app-notification.feature, client/src/Controller/Admin/SettingController.php, client/templates/Layouts/admin_moj_template.html.twig
The notifications section of the app is meant for super admins only but it looks like when we implemented super admins this link and endpoint was missed. This change limits the link visibility and endpoint to users with a super admin role.
Fixes DDPB-4304.
=> DDPB-4304: Limit app notifications page to super admin users

environment/document_sync.tf
Having tested this with a backlog of hundreds of documents recently we can reduce the scheduled time the document sync task runs to get through the queued documents in a shorter period of time.
=> Reduce document sync schedule time to 2 minutes

api/src/Migrations/Version263.php
It looks like our PSQL indexes locally don't quite match what's in RDS. The index we were trying to delete in 263 isn't present in AWS so I've dropped the instruction out.
=> Stop dropping non-existent indexes on named_deputy

api/src/Controller/StatsController.php, api/src/Entity/Report/ClientBenefitsCheck.php, api/src/Repository/ReportRepository.php, api/tests/Unit/Controller/StatsControllerTest.php, client/package-lock.json, client/src/Controller/Admin/StatsController.php, client/src/Entity/User.php, client/src/Form/Admin/BenefitsMetricsFilterType.php, client/src/Service/Client/Internal/StatsApi.php, client/src/Service/Csv/ClientBenefitMetricsCsvGenerator.php, client/templates/Admin/Stats/benefitsReportMetrics.html.twig, client/templates/Admin/Stats/reports.html.twig, client/templates/Admin/Stats/satisfaction.html.twig, client/templates/Admin/Stats/urResponses.html.twig, client/templates/Admin/Stats/userAccountReports.html.twig, client/translations/admin-metrics.en.yml
We are implementing the first new section in a long time and it would be good to use this as an opportunity to get some stats on a new piece of work. 
It is difficult to find information about how users typically respond to this question because it is less commonly answered with supporting information and it is difficult to track the information across paper only reports. 
Fixes DDPB-4206
Stuff I'm not too keen on in this PR but was unable to figure out a different way to do it:
- `api/src/Controller/StatsController::getBenefitsReportMetrics()` don't like the way I have to filter the results out based on the query parameters sent in the download request. Feel like the foreach is doing too much work and it's duplicating a whole section but was unsure how to filter the results when it came …
=> [DDPB-4206] Track how often users are completing information in the new benefits section

environment/check_csv_uploaded.tf
Limits checking if Sirius CSVs have been uploaded to production.
Fixes DDPB-4327
=> DDPB-4327: Only check CSV uploaded on production

.circleci/config.yml, .gitignore, environment/.terraform.lock.hcl, environment/api_elasticache.tf, environment/frontend_shared_elasticache.tf, environment/s3_access_logs.tf, environment/versions.tf, shared/.terraform.lock.hcl, shared/s3_replication.tf, shared/sns.tf, shared/versions.tf
We are running a bit of an old version of both terraform and the AWS provider. Update them.
Fixes DDPB-4352
So as of 4.9 we're not forced to make all the deprecation changes to the s3 providers so I have skipped neatly to latest version. I have however done the changes on the s3 access log bucket. I checked and it doesn't seem to try and destroy the bucket and the applies work fine against an env where bucket is in it's current format.
However, for the purpose of risk mitigation I was going to put this all the way through to prod and then do a small follow up (call it 4352b or something) for the deprecation warnings on our main s3 bucket and follow then plan through very carefully to prod.
Updated a few other deprecation warnings. Also including the lock file as it's best practice: …
=> DDPB-4352 bump terraform version and provider versions (specifically AWS)

Makefile, client/phpstan.neon
This is the first stage of fixing Level 1 PHPStan errors. Files have been updated in order for the phpstan make commands to run locally. 
Fixes DDPB-3123
- Updated the memory limit in the docker commands for api and frontend 
- Updated the jangregor path in order for the phpstan-frontend command to work
=> DDPB-3123: Fix PHPStan errors

.pre-commit-config.yaml, api/src/Controller/ManageController.php, environment/checklist_sync.tf, environment/document_sync.tf, environment/monitoring_lambda_event.tf
Costing a whole lot in config because of the creation of multiple resources every time the cloudwatch event triggers
For now shall we just set prod to be every 5 mins for both jobs and everything else to be once every 24 hours. Also do we need checklists and reports to be separate commands? Could half the number of calls if we just dumped all the code in one command called sync to sirius or something.
NA
=> amend sync timings

Makefile, README.md, api/src/Controller/Report/ClientBenefitsCheckController.php, api/src/Controller/Report/ReportController.php, api/src/Entity/Report/Report.php, api/src/Service/ReportStatusService.php, api/src/v2/Fixture/Controller/FixtureController.php, generate_certs.sh
This bug was introduced when creating the client benefits section. As we
was not flushing the db again after updating the report status cache
check we was not getting the client benefit status back as completed and
instead it was returning not done
Also in this PR is a fix for creating multiple client and the SSL cert fix that now gives us a secure connection to the local development server rather than a not secure warning when loading the webpage
Fixes DDPB-4346
=> [DDPB-4346] fixed bug around finished reports showing as not finished

.circleci/config.yml
Cut down on costs by being a bit more ruthless with the env teardown
Fixes DDPB-4373
Only thing of note here is I put the workspace protection before the plan and all that malarkey. The reason for this is that now that we're running hourly I can imagine a situation where we try and delete at the same time as rerunning a workflow and doing an apply. This should avoid this from happening as the workspace will be protected before it runs the deletes...
However thinking about it, the destroy could happen first and then the job will fail on plan or apply. However there will be a state lock so this shouldn't cause issues and job can be rerun. If it does end up causing issues then we will need to chuck in a waiter script that looks for the deletion runs and checks if they are running but it …
=> DDPB-4373 change the teardown schedule on ephemeral envs

api/src/Repository/ReportRepository.php, api/src/v2/Registration/Uploader/LayDeputyshipUploader.php, api/tests/Unit/Entity/Repository/ReportRepositoryTest.php
After we started receiving CSVs from Sirius rather than casrec, case numbers with letters were appearing with uppercase letters whereas previously they were lowercased. As we weren't lowercasing when searching on case numbers in the lookup during CSV upload any case with letters was not updated with report type changes. This change ensures we lowercase both the property on Report and the case number in the CSV.
Fixes DDPB-4409.
=> DDPB-4409: Ensure we lowercase casenumbers when matching during lay CSV upload

api/src/v2/Registration/Uploader/OrgDeputyshipUploader.php, api/tests/Behat/features-v2/registration/ingest.org.sirius.feature, api/tests/Unit/v2/Registration/Uploader/OrgDeputyshipUploaderTest.php
Prior to casrec we were automatically updating deputy name and org alongside automatic discharges. As the name and org went in tandem with a discharge this log was sound but now we have disabled that step we are updating the deputy and address before a discharge has happened. This can lead to the wrong people being able to see reports.
Fixes DDPB-4431
=> DDPB-4431: Stop automatically moving clients into new orgs and updating named deputy name on CSV upload

api/src/v2/Registration/Uploader/OrgDeputyshipUploader.php, api/tests/Unit/v2/Registration/Uploader/OrgDeputyshipUploaderTest.php, client/package.json
A further ticket to tighten up our CSV upload process. We are currently updating the deputy name and address if they have changed. We should only do this if they are the existing deputy for the client.
Fixes DDPB-4435
=> DDPB-4435: Only update deputy name and address if they are the existing deputy reporting on a client

client/config/packages/framework.yml
Temporarily disabling verifying SSL when using the API scoped client. Follow up fix will be made to revert this change once we've fixed the verify problems.
Fixes DDPB-4439
=> DDPB-4439: Stop verifying SSL in api client

api/src/Service/PreRegistrationVerificationService.php
At some point we stopped trimming the strings we receive from Sirius when matching against them. This reinstates that step to ensure we account for client and deputy last names that contain whitespace from Sirius.
Fixes DDPB-4440
=> DDPB-4440: Trim names when matching against PreRegistration data

client/templates/Admin/Client/Report/Formatted/checklist_formatted_body.html.twig, client/tests/phpunit/Service/ChecklistPdfGeneratorTest.php
Bug fix that now ensures that 'non-applicable' answers selected on the report checklist by the case manager is now visible on the pdf once it's saved in Sirius.
Fixes DDPB-4375
- Updated the twig template for the non-applicable answers.
- A follow up ticket has been added to the backlog to write a test for this.
=> DDPB-4375: Response for checklist question not appearing

client/src/EventSubscriber/ClientUpdatedSubscriber.php, client/src/EventSubscriber/ReportSubmittedSubscriber.php, client/src/EventSubscriber/UserUpdatedSubscriber.php, client/tests/phpunit/EventSubscriber/ClientUpdatedSubscriberTest.php, client/tests/phpunit/EventSubscriber/ReportSubmittedSubscriberTest.php, client/tests/phpunit/EventSubscriber/UserUpdatedSubscriberTest.php
Some event subscribers had that triggered multiple functions off of a single event were setup incorrectly.
This PR is to update the configuration to have the right structure.
Fixes DDPB-4443
=> DDPB-4443: Review and fix EventSubscribers that have multiple event listeners

api/config/packages/dev/monolog.yml, api/config/packages/monolog.yml, api/config/packages/prod/monolog.yml, api/config/packages/test/monolog.yml, api/config/parameters.yml.dist, api/docker/confd/templates/parameters.yml.tmpl, api/src/v2/Registration/Controller/LayDeputyshipUploadController.php, api/src/v2/Registration/Uploader/LayDeputyshipUploader.php, client/config/packages/dev/monolog.yml, client/config/packages/prod/monolog.yml, client/config/parameters.yml.dist, client/docker/confd/templates/parameters.yml.tmpl, client/src/Controller/Admin/AjaxController.php, client/src/Controller/Synchronisation/SynchronisationController.php
Make the csv logger a bit more generic to avoid us having to have loads of difference (also add it to sync controller)
Fixes DDPB-4471
So as part of a previous PR, devs added a new logger as we didn't want to change the log level across the app as it may have meant logging things we didn't want to in prod. Adding the extra logger gave us more fine grained control for individual classes. However, its name made it not very reusable. I think rather than having a new logger every time we want to capture notices, we can have verbose logger and use it for those time we want to capture more but not call it a warning.
NA
=> DDPB-4471 change log levels to be more generic

api/src/v2/Registration/Uploader/OrgDeputyshipUploader.php, api/tests/Behat/features-v2/registration/ingest.org.sirius.feature, api/tests/Unit/v2/Registration/Uploader/OrgDeputyshipUploaderTest.php, docker-compose.dev.yml
Following on from a previously PR where an automation step was disabled for the Org CSV upload, we implemented a workaround to re-enable the automation for named deputy changes that happen within the same org.
Continuing on from this, this PR implements a similar workaround to automate when a deputy moves organisation and takes their clients with them.
Fixes DDPB-4474
=> DDPB-4474: Accommodate deputies who move firms and take their clients with them 

api/src/Entity/Client.php
Currently reports and checklists are not in any particular order once the report is submitted by the deputy. This fix now lists the most recent submitted report at the top of the list to make it easier for the case managers when they view the clients page.
Fixes DDPB-4454
Added an @OrderBy annotation to the reports property in the Client entity that sorts the reports by the submitted date.
=> DDPB-4454: Reports out of chronological order

client/src/Command/DocumentSyncCommand.php, client/src/Model/Sirius/SiriusApiError.php, client/src/Service/SiriusApiErrorTranslator.php, client/tests/phpunit/Service/SiriusApiErrorTranslatorTest.php
We still have some documents that get stuck during the sync process to Sirius. One of the error messages that is difficult to interpret is the message OPGDATA-API-INVALIDREQUEST: The body of the request is not valid. This message could be linked to a number of different things. Specific messaging is sent from integration but was not being used in Digideps.
Fixes DDPB-4452
- Updated the SiriusAPiError model
- Removed translations from SiriusApiTranslator class and refactored translateApiError function
- Updated the array keys in deserializeError & jsonIsUnexpectedFormat functions
- Removed redundant test and added new tests
- Integration repo was updated to send error messages in a consistent format
- [x ] I have added tests to prove my work
=> DDPB-4452: Create more specific document failure errors 

client/templates/Report/Formatted/_client_benefits_check.html.twig
Currently the new benefits section on the report pdf does not display all the information the deputy enters on the report.
Specifically, the "Person or organisation who received the money" information is not displayed.
The purpose of this PR is to display that information. I've also added in headings for each section, as the information entered by the deputy may not make it clear what is being represented.
Fixes DDPB-4475
=> DDPB-4475: Data from New Benefits not pulling through to the report PDF

api/Dockerfile, client/Dockerfile
Fix for vulnerability picked up in ECR scan.
Fixes DDPB-4501
Ironically the security vulnerability is in local-php-security-checker which does the same checks as dependabot is what was causing the golang security vulnerability warning from ECR. I tried to update it to latest version but that still had the issue so decided to remove completely as it does just check the composer lock files for know vulnerabilities the same as dependabot does so it's not really adding anything for us.
Updated php version to use latest alpine whilst I was there. 
NA
=> DDPB-4501 remove golang vulnerability

shared/secrets.tf, shared/sync.tf
When the JWT prototype was initially being worked on, the secrets were not put in terraform, as such we need to push them through so that each env has correct secrets.  
Fixes DDPB-4456b
Add the secrets and allow sync task to access them.
NA
=> DDPB-4456b properly add the jwt secrets

api/src/Service/ReportService.php, api/tests/Unit/Service/ReportServiceTest.php
Bug fix ticket that addresses users that are submitting reports but appear to have an inactive status. 
Fixes DDPB-4498
This issue was resolved in a [previous ticket](https://github.com/ministryofjustice/opg-digideps/pull/883/files#diff-9278b433160f7b21d5efaec96b4e224b0d6643f229521933a8e8f90cec42298c), which also covered Lay Deputies. However it didn't resolve this particular user as they registered before the issue was addressed. 
With regards to this ticket, the users active status will be updated and set to 'true' once their report submission has been persisted to the database.
A unit test has also been added to test this.
- [x ] I have added tests to prove my work
=> DDPB 4498: PAs users that are submitting reports look inactive by status 

client/scripts/document_and_checklist_sched.sh, environment/checklist_sync.tf, environment/document_sync.tf, environment/monitoring_lambda_event.tf, environment/parameters.tf
Fixes DDPB-4508
Set it up with opposite settings to mimic prod and did some manual testing.
Put through 3000 docs to check it didn't run into memory or cpu issues (i was more checking that it didn't go up over time which is doesn't seem to) and to check that it processed them properly running in this form.
We can see them going through fine here:
I just did this in the most straight forward way possible after the frustrations of the previous attempt so that in all envs we do one scheduled run per day but in prod we have a container up constantly that runs every minute.
NA
=> DDPB-4508 make a container that runs sync commands continuously

environment/checklist_sync.tf, environment/document_sync.tf, environment/htmltopdf_sg.tf, environment/parameters.tf
Decided to move this setup to the checklist container which is what we should have done in the first place.
Fixes DDPB-4508
An oversight on the original ticket meant the setup didn't work properly with checklists. Didn't catch it before we merged but caught before it caused a problem and put in an emergency fix for it. However, with a bit more thought, we should have just switched to checklists container for the script. This ticket addresses that. 
NA
=> DDPB-4508c use the checklist container for the sync setup

api/src/Repository/ClientRepository.php, api/tests/Behat/bootstrap/v2/Common/IShouldBeOnFrontendTrait.php, api/tests/Behat/bootstrap/v2/Registration/IngestTrait.php, api/tests/Behat/bootstrap/v2/Registration/SelfRegistrationTrait.php, api/tests/Behat/features-v2/registration/self-register.feature, api/tests/Behat/fixtures/sirius-csvs/lay-2-rows-co-deputy.csv
A co-deputy could not sign up to the service.
The reason for this was because the deputy was entering their case number with a capital T which did not match the lower case t in the database.
We are doing lowercase comparisons on case numbers elsewhere in the app, so this needs updating to match this.
Fixes DDPB-4592
Updated comparison to lowercase both the input parameter, and the values from the database.
=> DDPB-4592: Co-deputy cannot sign up to the service

environment/alarms.tf, environment/waf.tf
Add the resources for WAF protection with shield advanced 
Fixes DDPB-4552
Did the main bit in different repo. 
This is just to add a couple of alarms for when we are being DDOSed and adding the protection. We still need to add the Elastic IP addresses in manually as doesn't seem to be a way in terraform...
NA
=> DDPB-4552 add resource protection

disaster_recovery/backup/Dockerfile, disaster_recovery/restore/Dockerfile
Don't need setuptools once we've installed all packages and sometimes has vulnerabilities in the package.
Remove setup tools
NA
=> remove setuptools after pip installs

client/assets/javascripts/modules_new/TextAreaAutoSize.js
Fix based on Product feedback on [[DDPB-4115](https://opgtransform.atlassian.net/browse/DDPB-4115)] 
[DDPB-4115]: https://opgtransform.atlassian.net/browse/DDPB-4115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Match on parent with .js-autosize not a textarea with that feature

api/config/packages/dev/monolog.yml, api/config/packages/prod/monolog.yml, api/config/services.yml, api/src/Controller/ClientController.php, api/src/Event/ClientArchivedEvent.php, api/src/EventDispatcher/ObservableEventDispatcher.php, api/src/EventSubscriber/ClientArchivedSubscriber.php, api/src/Service/Audit/AbstractAuditLogHandler.php, api/src/Service/Audit/AuditEvents.php, api/src/Service/Audit/AwsAuditLogHandler.php, api/src/Service/Audit/LocalAuditLogHandler.php, api/tests/Behat/run-tests-parallel.sh, api/tests/Unit/Service/Audit/AuditEventsTest.php
We've had a few reports that clients were being archived without being action by users.
Unfortunately, we did not have the visibility to track whether these were done by a user or if there is some flaw in our archiving logic which causes this issue.
To help get better visibility of this issue, we are adding in audit logging to be able to track when and who is archiving which clients.
Fixes DDPB-4610
I followed the same pattern we have used previously for audit logging tickets which involves using the Event Dispatcher component provided by Symfony. 
The documentation for this can be found [here](https://symfony.com/doc/5.4/components/event_dispatcher.html).
However this time, I decided to implement this on the API instead of the client.
The reason behind this is that we are wanting to move …
=> DDPB-4610: Logging for deputies who have archived clients 

.circleci/config.yml, client/Dockerfile
Bumps node from 18.13.0-alpine to 18.14.2-alpine.
---
updated-dependencies:
- dependency-name: node dependency-type: direct:production update-type: version-update:semver-minor ...
=> Bump node from 18.13.0-alpine to 18.14.2-alpine in /client

environment/frontend_shared_elasticache.tf
Somehow prod version has been updated but only for frontend. This is strange as auto update of minor versions should apply only for ver 6 and above. Having said that, it's not clear if this applies to patch updates. Strange that it hasn't updated the other api redis though.
In either case, lets upgrade this to 5.0.6 so production release will work then we can look to upgrade redis to 6.x version
=> match prod ver of elasticache

client/assets/javascripts/common.js
[Incident](https://incident.opg.service.justice.gov.uk/incident/694/) created as we were capturing some personal data in Google Analytics.
This fix should disable the capturing of form validation errors altogether to prevent any event data being sent to GA.
Fixes DDPB-4661
=> DDPB-4661: Disable capturing of Form Validation Errors in Google Analytics

environment/alarms.tf
Fixes DDPB-4666
Removes some inconsistency in our alarm naming, should make slack alerts easier to read at a glance
I went with the hyphenated format, with the environment name first. i.e. `environment-alarm-reason`.
Happy for there to be some discussion on this if needed
=> DDPB-4666 - Standardise alarm naming

environment/alarms.tf
Left a fullstop in an alarm name, should probably remove that
=> remove fullstop from start of alarm

environment/.terraform.lock.hcl, environment/api_elasticache.tf
Sets a more aggressive max memory policy on the API cache to prevent further OOM problems
If the problem continues we should look into increasing the node size
=> DDPB-4640 - modify redis maxmemory policy

environment/api_elasticache.tf, shared/.terraform.lock.hcl, shared/elasticache_parameters.tf
The parameters are shared across environments, but currently live in the environment folder so will fail to create
=> Move redis param group to Shared

.github/workflows/workflow-path-to-live.yml
Enforce unit tests pass before carrying on path to live.  Set the block as apply to development to stop us deploying bad containers to any env if there's an issue.
=> enforce unit tests pass before carrying on path to live

client/translations/report-money-transaction.en.yml
Update the radio option in the Money Out section so that it reads  'Payments from [Client]’s accounts to other accounts' instead of 'Transfers from [Client]’s accounts to other accounts'. 
This should create a clearer distinction between payments to other accounts belonging to the client and transfers between accounts belonging to the client (which we handle  in a separate section).
Fixes DDPB-4662
- Changed wording in translation file so it's reflected in Money out section and the report pdf
- [x ] I have performed a self-review of my own code
=> DDPB-4662: Replace the word 'transfer' in Money Out list on report to avoid confusion

api/src/v2/Fixture/ReportSection.php, client/templates/Report/Decision/_list.html.twig
Edit and remove buttons incorrectly rendered in the decisions section of the checklist.
Issue raised by Peter.
Also noticed that the significant decisions question was not getting set when fixtures are created, so I fixed that too.
Fixes DDPB-4690
- Wrapped if not block around the buttons to prevent incorrect rendering
=> DDPB-4690: Edit and Remove buttons running over the column in checklist

.github/workflows/_build-and-push.yml
The `security-checks` input for the trivy action was deprecated, this uses the updated `scanners` input - which is the same thing
=> DDPB-4692 - update trivy input

api/src/Controller/Report/MoneyTransferController.php, api/src/Entity/Report/MoneyTransfer.php, api/src/Migrations/Version269.php, client/src/Controller/Report/MoneyTransferController.php, client/src/Entity/Report/MoneyTransfer.php, client/src/Form/Report/MoneyTransferType.php, client/templates/Components/Form/_input.html.twig, client/templates/Report/MoneyTransfer/_list.html.twig, client/templates/Report/MoneyTransfer/step.html.twig, client/translations/report-money-transfer.en.yml
As part of the 'transfers' epic, add an optional description field to the money transfer section and display input on the summary page. 
Fixes DDPB-4680
- Description column added to money_transfer table 
- Optional description field added to money transfers page
- Character count component applied
- Description rendered on the summary page and transfer deletion page
=> DDPB-4680: Create new data field for transfer description 

shared/certificates.tf, shared/terraform.tfvars.json
make secrets consistent part 1.
Fixes DDPB-4317
Seems we started the work to make our secrets consistent across envs. 
This part just moves training to preproduction as this was missed as part of our move.
Next part will then use the environment names secrets prefix for respective secrets for each env and default for our default environments. 
This is good as our secret rotation can then ignore default.
I also added a wildcard cert in here for a pattern that follows what they do on modernise and use an lpa.
NA
=> DDPB-4317 make secrets consistent - part 1

README.md, api/src/Controller/AuthController.php
Throw exception when user token is null.
Fixes DDPB-4724
=> DDPB-4724: Unhandled Auth Error - Raises 500

.github/workflows/_cycle_secrets.yml, .github/workflows/scheduled-cycle-secrets.yml, environment/scripts/cycle_secrets/cycle_secrets.py
Rotate the db password at same time as secrets
Fixes DDPB-4597
There were issues in some environments due to 2 factors:
- Secrets are paginated so we need to bring them all back.
- Apply immediately is turned off by default on some of our envs to stop patches getting applied during normal hours.
Only solution for the second issue that I could think of is to apply the DB secret update as part of the rotation job as there's no way of doing this in a non messy way in terraform. This should have the affect that connections will continue to work even if the tf apply fails. The TF apply is simply to update the container specs so everything is fully synced though it's not totally necessary now.
NA
=> DDPB-4597 add db secret rotation to cyclesecrets script

README.md, api/src/Controller/SatisfactionController.php, client/src/Form/UserResearchResponseType.php, client/translations/validators.en.yml
Frequent 500 error message thrown, related to a post request against the /satisfaction endpoint on the api side. 
Also noticed that a 400 error message is thrown to deputy if they try to submit an empty user research form, so a fix has been added to this ticket.
Fixes DDPB-4725
- Recreated the error by submitting a satisfaction score and then going back to that same page and resubmitting the same or different score. 
- Updated logic to create a new entity if it doesn't already exist in the database and update it if it does.
- Validation added to user research form fields to prevent blank submission attempts
=> DDPB-4725 : Satisfaction 500 error - Create upsert behaviour

environment/ecs.tf, environment/s3_iam_replication.tf, environment/scripts/workspace_cleanup.sh
add containerinsights to tf managed state
Fixes DDPB-4747
add to log group so it creates destroys it properly when env is taken down. Also was hard to see what env backup role belonged to so added env to name.
Sadly whilst destroying the log group is recreated even if you do a targeted destroy. The easiest solution is to import it again and destroy it which does seem to work.
NA
=> DDPB-4747 add containerinsights to tf managed state

environment/ecs.tf
By default this was always 1 day. The PR to bring into terraform set it to 0 (keep forever). This simply puts it back to what it's default value was.
=> change retention in days for performance insights

.editorconfig
Adds a .editorconfig file for consistent terraform formatting as per the OPG Terraform guidance
https://docs.opg.service.justice.gov.uk/documentation/guides/terraform_practices.html#use-editorconfig-in-all-repos-for-consistent-whitespace
=> DDPB-4757 - add .editorconfig file

client/translations/admin-checklist.en.yml
Remove two lines in the checklist that direct staff users to a void document 
Fixes DDPB-4740
- Remove unwanted text from translation file
=> DDPB-4740: Remove two lines in the checklist that direct staff users to a void document 

api/src/Controller/StatsController.php, api/src/Repository/UserRepository.php, api/tests/Behat/bootstrap/v2/ACL/ACLTrait.php, api/tests/Behat/bootstrap/v2/Common/IVisitAdminTrait.php, api/tests/Behat/bootstrap/v2/Common/PageUrlsTrait.php, api/tests/Behat/features-v2/acl/admin/super-admin-only.feature, api/tests/Unit/Controller/StatsControllerTest.php, api/tests/Unit/Entity/Repository/UserRepositoryTest.php, client/src/Controller/Admin/StatsController.php, client/src/Form/Admin/InactiveAdminReportFilterType.php, client/src/Service/Client/Internal/StatsApi.php, client/src/Service/Csv/InactiveAdminUsersCsvGenerator.php, client/templates/Admin/Stats/inactiveAdminUsersReport.html.twig, client/templates/Admin/Stats/reports.html.twig, client/translations/admin-metrics.en.yml
Allows us to tailor the report to our needs to find which admin accounts are inactive.
Fixes DDPB-4729
Making a use of the existing endpoint which takes in a time period to bring back a list of admin users that haven't logged in since that time period.
Renamed various methods/endpoints/variables to be consistent and clear about what they are.
Updated report to include super admins and admin managers.
Updated tests to reflect the above changes.
=> DDPB-4729: Allow users to change the inactivity period for the inactive admin users report 

api/src/Entity/User.php, client/src/Controller/UserController.php, client/src/Entity/User.php, client/translations/password-reset-expired.en.yml
Reduce the 48 hour time limit to 1 hour when a user requests a password reset. This will reduce the risk of attackers intercepting the generated token. 
Fixes DDPB-4773
- Created new const for password reset and set to 1 hour
- Split controller logic to handle expired activation and password reset tokens separately.
- Will need to manually update Notify email template to reflect the updated time limit.
=> DDPB-4773: Reduce token time limit for a password reset request

.github/workflows/_run-terraform.yml, account/lambda.tf
Updates the redeployer lamdba runtime to `provided.al2` as `go1.x` will be deprecated soon
=> DDPB-4781 - update redeployer lambda runtime

environment/admin_tg.tf, environment/ecr.tf, environment/front_tg.tf
Because of lifecycle policy (and to avoid downtime) I have change the tg group name. Couldn't use name_prefix as it was max 6 chars and I really want to use the env name as part of it for identification so this is a compromise.
Additionally the tag was on the app image of development rather than the webserver image (another issue that is hard to test before path to live)
=> DDPB-4735c update tg and development image

terraform/account/cloudwatch_queries.tf
Some more pre-made insights queries for analysing live issues
Fixes DDPB-4830
Useful insights queries that are added to cloudwatch that allow us to more quickly identify issues related to response time alarms, 5xx alarms among others.
Useful feature is being able to add comments to the queries to explain to a new dev what the purpose of the query is.
NA
=> DDPB-4830 additional insights queries for analysing issues in the logs

api/src/Repository/UserRepository.php
Script failing on join deletion.
Fixes DDPB-4832
The logic was supposed to be anything that doesn't have a report or NDR 30 days after registering, ditch it. However a user had left feedback and this was a foreign key constraint that was causing this job to fail. 
As we may want to see user feedback from users that had issues signing up, we decided to just not delete those users that have left feedback independent of reports or NDRs.
Tested in preprod, saw we needed to add an extra bit and restested... now we get:
This will work equally in live
NA
=> DDPB-4832 add extra filter for user research table to fix cleanup script

terraform/account/waf.tf
This reverts commit c31a9379d6b84b3038e9638a559fcc42eaf31df3.
Still an issue, pdfs get blocked without this.
=> Revert "DDPB-4846 - re-add XSS waf rule (#1443)"

terraform/environment/admin_sg.tf, terraform/environment/api_sg.tf, terraform/environment/dns_private.tf, terraform/environment/elasticache.tf, terraform/environment/front_sg.tf
Move the used cache from environment specific cache to shared cache
Fixes DDLS-40
This is part 2. In part 1 we created the shared cache and changed all the keys to prepend the environment. We talked about how this did not change the functionality of production as it's a single environment account but would be a good saving for dev and preprod.
NA
=> DDLS-40 move to shared cache part2

api/app/src/Command/ResyncResubmittableErrorDocuments.php, api/app/src/Repository/DocumentRepository.php, api/app/tests/Unit/Entity/Repository/DocumentRepositoryTest.php, terraform/account/elasticache.tf, terraform/account/terraform.tfvars.json, terraform/account/variables.tf, terraform/environment/scheduled_events.tf, terraform/environment/scheduled_events_checks.tf
Sync docs nightly
Fixes DDLS-59
Some docs fail to sync sometimes because of an outage on sirius side or some other networking issue. We know which error statuses will likely resync when we try again so this is a nightly job that sets them back to queued. 
Another thing I am pushing through as part of this ticket is to change the elasticache to have a maintenance window and not apply immediately. I have set them 1 day apart for pre and prod to show any issues in pre the previous day. This will make upgrades easier.
NA
=> DDLS-59 resubmit resubmittable documents on a nightly basis

terraform/account/provider.tf, terraform/environment/provider.tf
I've checked with plans against preproduction for account and environment and it doesn't remove any tagging or recreate anything unexpected.
=> DDLS-68 add default tags to resources

client/app/templates/Report/MoneyInShort/_answers.html.twig
Had to drop dump function as it accidentally got released as part of DDLS-7 which has triggered alarms in prod
Fixes DDLS-7A
=> DDLS-7A: Extension of DDLS-7 branch (Money In) 

client/app/src/Controller/Admin/IndexController.php
The CSV upload pages were missing their statuses as a result of a recent change to how we use redis.
Redis keys are now stored in with the workspace (environment) name prepending the key name - `environment_keyname`
The setting of the keys were changed in the initial PR, however the retrieval wasn't updated along side this.
Fixes DDLS-74
=> DDLS-74: CSV upload pages missing status

terraform/environment/api_rds.tf, terraform/environment/modules/aurora/main.tf, terraform/environment/modules/aurora/variables.tf
Updates our RDS to use the latest AWS CA cert.
This shouldn't require any downtime as can be updated in place - checked in branch env
=> DDLS-37 - update RDS certs

api/app/config/parameters.yml.dist, api/app/config/services.yml, api/app/src/Command/SatisfactionPerformanceStatsCommand.php, api/app/src/Service/File/Storage/S3SatisfactionDataStorage.php, api/app/tests/Unit/Command/SatisfactionPerformanceStatsCommandTest.php, api/docker/app/confd/templates/parameters.yml.tmpl, local-resources/localstack/localstack-init.sh, terraform/environment/region/cloudwatch_scheduled_events.tf, terraform/environment/region/cloudwatch_scheduled_events_checks.tf
Fixes [DDLS-83](https://opgtransform.atlassian.net/browse/DDLS-83)
This change creates a console command to extract the satisfaction performance scores at the start of every month and upload the stats in the desired format to S3. A github action on the performance repo (opg-performance-data) would then pick up the extracted file from S3 merge it into the Digideps satisfaction scores file on the performance repo.
This automation change will eliminate the manual process at the start of every month.
The code runs a raw query on the Digideps database to extract the figures and then uses the S3 service to upload the file into a new S3 bucket created specifically for this purpose. 
_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about …
=> DDLS-83 : Console command for generating the Satisfaction score

terraform/environment/region/cloudwatch_iam_events.tf, terraform/environment/region/cloudwatch_scheduled_events.tf, terraform/environment/region/cloudwatch_scheduled_events_checks.tf, terraform/environment/region/ecs_iam_performance_data.tf, terraform/environment/region/ecs_task_performance_data.tf
Cloudwatch events for satisfaction data
Fixes DDLS-84
Create the scheduled events in terraform to run it.
NA
=> DDLS-84 : Satisfaction data cloudwatch event schedule updates

api/app/src/Repository/DocumentRepository.php, api/app/tests/Unit/Entity/Repository/DocumentRepositoryTest.php
Handle docs stuck in IN_PROGRESS
Fixes DDLS-130
Whilst rare (I've seen this maybe 3 or 4 times ever), we occasionally get docs stuck in progress. I didn't have the data to work out why but we had some old ones from a particular day. My only thought is that there was some network or container fail between setting them to in progress and setting them to SUCCESS or PERMANENT_ERROR.
If a doc is in progress then there shouldn't be any higher chance of anything being wrong with it than if it was queued so the solution is to set them back to queued. 
My approach was to add docs stuck in IN_PROGRESS for more than a day to be set back to queued along with the re-submittable error docs. This should take out some of the manual effort and investigation needed.
NA
=> DDLS-130 add resubs for docs stuck in progress

terraform/account/region/secrets.tf
We need this secret to go through the accounts before we can add the smoke tests (already tested with the secret in branch)
=> DDLS-165c prepreq secret in account for DDLS-165

terraform/environment/region/ecs_service_admin.tf, terraform/environment/region/ecs_service_front.tf
Bug fix. Makes sure, on first deploy that dependent services exist first so that /etc/hosts in sc containers are updated correctly. Very rare as I think admin and front were usually created last anyway as they depend on LBs but this should stop the issue from happening.
=> DDLS-200 bug fix for occassional deploy issues with service connect

api/app/src/v2/Registration/Uploader/OrgDeputyshipUploader.php
The Org CSV upload always defaults the Deputy Organisation name to ‘Your Organisation’.
The CSV has a value against the Deputy Organisation field. So the ingestion process has to use the value and default it to ‘Your Organisation’ only if the value is not present. 
Fixes DDLS-174
The code checks if the Organisation Name is empty in the CSV and defaults to using the default organisation name "Your Organisation". However, if an the email is not matched but an organisation name is provided in the CSV then this organisation name is used.
=> DDLS-174 - Org CSV Upload always defaults the Deputy Org name

api/app/src/Migrations/Version273.php
When an admin user invites a user to the app, a link is created between admin user and the invited user.
This is used purely for investigatory purposes and is not used for any other purposes currently.
This link (referred to a constraint in sql) was set up without the permission to be deleted when the admin user is deleted.
This PR fixes this by recreating the constraint with new configuration to allow for deletion.
Fixes DDLS-203
We cannot change or alter a constraint after is it has been created. Therefore we have to drop the constraint and create it again with the new configuration needed.
=> DDLS-203: Admin users who invited users to the app can't be deleted

api/app/src/Command/SatisfactionPerformanceStatsCommand.php, api/app/src/Repository/SatisfactionRepository.php
Fixes DDLS-204
The satisfaction data in the Admin Analytics Dashboard vs the CSV report download & performance stats on the OPG Services Performance Data site is different when entering the same dates. The reason being that the CSV report & performance stats excludes satisfaction feedback which are not linked to a report or NDR. The dashboard includes them and so is the difference in the number of responses.
This change now includes the satisfaction feedback which are not linked to a report or NDR, into the CSV report & performance stats on the OPG Services Performance Data site. The code also fixes a minor issue with the formatting of the user satisfaction percentage value in OPS Service performance stats by changing it from a string to int so that it can uploaded without any errors. …
=> DDLS-204 : Satisfaction data mismatch

client/docker/web/confd/templates/app.conf.tmpl
Will 403 for many file types used in scripts that shouldn't be in public instead of doing the 404 and logging an error to nginx logs. This will keep our alarms a bit more clear of spam
Fixes DDLS-213
Added a list of extensions to 403 for. 
NA
=> DDLS-213 make nginx 403 certain files

api/app/src/Entity/CourtOrder.php, api/app/src/Migrations/Version275.php
Fixes [DDLS-214](https://opgtransform.atlassian.net/browse/DDLS-214)
The court order UID column in the Court Order database table was set to the data type 'integer'. But the court order UIDs from Sirius exceed the number range of an integer in PostgreSQL (2147483648 to +2147483647). So the column has been changed to the data type 'bigint' to support large UID numbers.
The court order UID attribute in the Court Order entity in the API has been updated to the datatype 'bigint'. This has resulted in a new migration file to apply the changes to the database. There is no data in the table yet - so no impact.
[DDLS-214]: https://opgtransform.atlassian.net/browse/DDLS-214?atlOrigin= …
=> DDLS-214 : Updated court order uid column to bigint

client/app/templates/Report/MoneyIn/_list.html.twig, client/app/templates/Report/MoneyOut/_list.html.twig
Fixes bug created from DDLS-162. Twig template was updated in ticket to list the 'add item of income' and 'add payment' links to the money in/out summary page for high asset reports if the user has money to report on but has no transactions listed - this was done to improve user flow. 
As a result of twig update, a condition was removed that incorrectly renders the same links on the checklist. This has now been added back in.
Fixes DDLS-219
- Add hideEditLink condition back into twig templates
=> Hide add income/payment links from checklists

client/app/src/Controller/Report/ReportController.php
Fixes [DDLS-224](https://opgtransform.atlassian.net/browse/DDLS-224)
The review page of a report checks if there are documents attached to the report which are quite old and not available in S3 anymore. In such a scenario, the system asks the user to reupload the documents. The logic did not filter submitted reports. This fix adds a check to see if the report is submitted and if it is, then the logic is ignored.
[DDLS-224]: https://opgtransform.atlassian.net/browse/DDLS-224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DDLS-224 : Add a check for submitted reports in report review page

api/app/src/Command/SatisfactionPerformanceStatsCommand.php, api/app/src/Repository/SatisfactionRepository.php, api/app/src/Service/Stats/Query/RespondentsQuery.php, api/app/src/Service/Stats/Query/SatisfactionQuery.php, api/app/tests/Unit/Stats/Query/RespondentsQueryTest.php, api/app/tests/Unit/Stats/Query/SatisfactionQueryTest.php
Fixes [DDLS-233](https://opgtransform.atlassian.net/browse/DDLS-233)
The satisfaction feedback scores and details are displayed on OPG Service Performance Data site and on the Digideps Admin Analytics dashboard and report. The scores currently consider standalone feedback i.e. feedback that are not associated with a report or a NDR. But a lot of bots are getting past our honey pot traps, selecting dissatisfied scores and putting junk in our feedback forms. This results in the scores getting corrupted. 
This change excludes the standalone feedback from the scores and details across the Satisfaction Scores command job  and the Digideps Admin Analytics dashboard and report so that we can get an accurate reflection of the user feedback about our product.
_Any tips and tricks, blog posts or …
=> DDLS-233 : Filter out satisfaction scores not related to a report or a NDR

api/app/src/Entity/User.php, client/app/src/Entity/User.php
Fixes DDLS-241
The Deputy UID has been made optional to cater for scenarios where there is no deputy no for a user in the old data prior to DDLS-144 release.
=> DDLS-241 : Making Deputy UID optional in the User entity

lambdas/functions/slack_lambda/app/slack.py, orchestration/sleep_mode/main.go, terraform/account/region/lambda_slack.tf, terraform/environment/region/ecs_iam_sleep_mode.tf
Getting annoying spam in dev channel when we take the preprod envs down overnight.
Fixes DDLS-245
Easier than working our which jobs need turning off and reactivating... it's easier to just update an env on the lambda and not send out the notifications when it's set to pause_notifications.
NA
=> DDLS-245 pause overnight notifications

orchestration/tests/package-lock.json, orchestration/tests/package.json
Bumps [ws](https://github.com/websockets/ws) to 8.18.0 and updates ancestor dependency [puppeteer](https://github.com/puppeteer/puppeteer). These dependencies need to be updated together.
Updates `ws` from 8.16.0 to 8.18.0
- [Release notes](https://github.com/websockets/ws/releases)
- [Commits](https://github.com/websockets/ws/compare/8.16.0...8.18.0)
Updates `puppeteer` from 22.4.0 to 22.12.1
- [Release notes](https://github.com/puppeteer/puppeteer/releases)
- [Changelog](https://github.com/puppeteer/puppeteer/blob/main/release-please-config.json)
- [Commits](https://github.com/puppeteer/puppeteer/compare/puppeteer-v22.4.0...puppeteer-v22.12.1)
---
updated-dependencies:
- dependency-name: ws dependency-type: indirect
- dependency-name: puppeteer dependency-type: direct:production ... …
=> Bump ws and puppeteer in /orchestration/tests

Makefile, client/docker/web/confd/templates/app.conf.tmpl, client/resources/webpack.config.js, file-scanner/Dockerfile
Fix some log issues we're seeing where users are getting file not found
Fixes DDLS-281
For some reason, some users access previous versions of the static assets folder sometimes. This causes an error on the webserver that causes us alerts.
If we create a fallback folder and do a rewrite with break then it silently rewrites to the fallback folder. 
This is good as it still enables cache busting. What this means is that for the user the file path will change and it will bust their local cache of the resource but in the background it will always pull from the fallback folder.
To do this, I added a fallback folder as part of the webpack build process and did the rewrite in the correct places in the nginx config.
I tested it by changing the file contents and checking it was pulling the css …
=> Ddls 281 - cache bust assets but avoid stale connections

.github/workflows/workflow-path-to-live.yml, .github/workflows/workflow-pull-request-path.yml
add useful information in build output
Fixes DDLS-277
Originally I was looking to implement the docker build github action but actually I like the control we have over the caching  with the current approach. I noticed that it does some nice summary outputting though which I took for our pipeline. 
As such this is just a small one to give us a bit of useful env info in our pipeline summary.
EDIT: also added map to the assets nginx writes as it was logging them out and we don't need them and it interferes with our ip blocking pattern
NA
=> DDLS-277 add build output

.github/workflows/_unit-tests-api.yml, .github/workflows/_unit-tests-client.yml, .github/workflows/manual-spin-up-development.yml, .github/workflows/scheduled-update-training-environment.yml, .github/workflows/workflow-path-to-live.yml, .github/workflows/workflow-pull-request-path.yml, docker-compose.override.yml, docs/ADDING_REPORT_SECTIONS.md, docs/CROSS_BROWSER_TESTS.md, docs/DISASTER_RECOVERY.md, docs/ENVIRONMENT_VARIABLES.md, docs/TESTING.md, file-scanner/README.md, local-resources/local-load-balancer/certificates/certificates.md, orchestration/Dockerfile, orchestration/tests/package-lock.json, scripts/miscellaneous/bash_profile, terraform/environment/region/ecs_iam_admin.tf, terraform/environment/region/ecs_task_reset_database.tf
Separate out reset DB from integration tests
Fixes DDLS-295
Previously this was set as integration tests with an override for historic reasons. It makes more sense that it uses the pre-specified reset database container image. This allows for more granularity in permissions. This should also fix a failed training env reset job.
Additional fixes:
- Added a missing permission to the admin side for regenerating missing reports. 
- Fixed all the docker compose issues where it was using the old docker-compose syntax
- Updated npm spec to fix a vulnerability
NA
=> DDLS-295 separate out reset db from integration tests at infra level

api/app/src/Migrations/Version282.php
If a user has been discharged from a client but if the user has previously submitted a satisfaction score and then a user research form (which appears after the satisfaction survey form), then the system throws an error while deleting the user.
Fixes DDLS-261
1. Add delete on cascade to constraint in user id in user research response table
=> DDLS-261 Deleting a user with user research response data gives an error

.github/workflows/scheduled-update-training-environment.yml, api/app/src/Repository/DocumentRepository.php, terraform/environment/region/cloudwatch_scheduled_events.tf
Overnight job can resubmit these without issue.
Fixes DDLS-290
We have a overnight job that sets error status document submissions back to 'queued' if the errors are of a temporary nature. 
This PR simply adds the forbidden error message syntax to that query as any permissions issues from our containers should be temporary.
I have also changed a couple of timings on jobs that were occasionally bumping into each other.
NA
=> DDLS-290 add forbidden errors to the document sync overnight job

terraform/account/region/secrets.tf
Add the secret that we need to populate
Fixes DDLS-302
Have to add the secret to account first and run it through all the envs or it will complain in the main PR that the secret doesn't exist. We use default as namespace for ephemeral envs so that secrets are populated properly rather than doing it as a per workspace namespace.
NA
=> DDLS-302 Pre work to add the secret that we need to populate

.github/workflows/_build-and-push.yml
Trivy was constantly breaking due to rate limiting
Fixes DDLS-353
This is one suggested approach by trivy to fix this issue
NA
=> DDLS-353 use pull through cache from our ecr for trivy

terraform/environment/region/ecs_iam_front.tf
Permissions were removed due to not thinking they were needed ages ago but turns out they are now we have reactivated dependency endpoint polling
=> DDLS-356b re-add sirius api permissions to front container

api/app/tests/Behat/bootstrap/v2/Common/AuthTrait.php, api/app/tests/Behat/bootstrap/v2/Common/BaseFeatureContext.php, api/app/tests/Behat/bootstrap/v2/Common/IShouldBeOnFrontendTrait.php, api/app/tests/Behat/bootstrap/v2/Common/IVisitAdminTrait.php, api/app/tests/Behat/features-v2/acl/login/login.feature, api/app/tests/Behat/features-v2/registration/self-register.feature, client/app/src/Controller/Report/ReportController.php, client/app/src/Entity/Client.php, client/app/src/Service/Client/Internal/ClientApi.php, client/app/src/Service/Redirector.php
As a user with multiple deputies, I want to be able to use my primary login to view my remaining deputies when I am discharged from the court order linked to my primary account.
Fixes DDLS-358
- Update Redirector class to track number of active client(s) and redirect to the correct route
- Redirect deputy to 'client_add' page if they no longer have active clients
- Add behat tests to cover various journey's dependent on single or multi-client deputy with secondary clients
- Update redirector class to ensure deputy is only redirected to 'report-create' page if they have no active reports
=> DDLS-358: Persist primary account when deputy is discharged from court order related to that account

api/app/src/TestHelpers/UserTestHelper.php, client/app/src/Controller/Report/ReportController.php
=> DDLS-380: Fix for org users trying to access reports

terraform/account/region/kms_service_sns.tf, terraform/account/region/lambda_monitor_notify.tf, terraform/account/region/sns.tf
Encrypt SNS queues
Fixes DDLS-391
Tried to encrypt both SNS queues but cross region encryption not possible so just did the one. Tested that alerts still come through.
NA
=> DDLS-391 add encryption to SNS

client/app/src/Service/HtmlToPdfGenerator.php, htmltopdf/Dockerfile, htmltopdf/requirements.txt
Update htmltopdf service generally
This was failing with just the weasyprint major update so had to do a bit of mucking around. 
Did the following.
- Upgraded python to a feature supported version. 
- Upgraded alpine to later version
- Alpine upgrade required me to replace two apk packages as they have been replaced in alpine distro
- Newer pdfs generated are slightly smaller in size so had to amend healthcheck to account for that
Checked that PDFs still generated fine and looked the same. They looked find to my eye. 
NA
=> Renovate Update dependency weasyprint to v63

file-scanner/Dockerfile
Fix vulnerability
I believe all the stdlib bits are related to the go package which needs to be updated to latest version. I tried a local scan and it didn't flag it so let's see if this fixes it in pipeline.
NA
=> add file scanner vulnerability fix

terraform/environment/region/variables.tf
Had a request (https://mojdt.slack.com/archives/C7YH87C3A/p1732884764266839) around vpn access for prisma uses - turns out the prisma ip range is not in the `moj_sites` list, so this adds it directly
=> Add primsa vpn range to the default allow list

terraform/account/region/dynamodb.tf, terraform/account/region/elasticache.tf, terraform/account/region/lambda_ip_blocker.tf
This adds the encrypting to the ramaining dynamodb resource.
Fixes DDLS-408
Added the encryption. Additionally, I have created two new security groups instead of just amending the current ones. I'm doing it this way to avoid any down time. In subsequent PRs I will duplicate the settings for the cache sg for all the env services then in another PR remove the original. This will result in zero downtime. It's a bit more of a faff but I'll just add it to other PRs that I do.
NA
=> DDLS-408 add encryption to remaining dynamo table

api/app/src/Entity/PreRegistration.php, api/app/src/Migrations/Version285.php, api/app/src/v2/Registration/Assembler/SiriusToLayDeputyshipDtoAssembler.php, api/app/tests/Unit/Controller/SelfRegisterControllerTest.php
We weren't aware but it is in fact possible that the source data may contain null values here.
It was possible to edit the same doctrine migration script, 285, as it hasn't yet run on prod and all the other envs rebuild schema.
=> Switch clientFirstName to nullable

api/app/src/Command/ProcessLayCSVCommand.php, api/app/src/Entity/Client.php, api/app/src/Repository/ClientRepository.php, api/app/src/Repository/PreRegistrationRepository.php, api/app/src/Repository/UserRepository.php, api/app/src/v2/Assembler/ClientAssembler.php, api/app/src/v2/Registration/DeputyshipProcessing/CSVDeputyshipProcessing.php, api/app/src/v2/Registration/Uploader/LayDeputyshipUploader.php, api/app/tests/Behat/bootstrap/v2/Registration/IngestTrait.php, api/app/tests/Behat/features-v2/registration/ingest.lay.sirius.feature, api/app/tests/Behat/fixtures/sirius-csvs/lay-2-rows-deputy-has-multiple-client-deputyships.csv, api/app/tests/Behat/fixtures/sirius-csvs/lay-2-valid-rows-not-unique.csv, api/app/tests/Unit/Command/ProcessLayCSVCommandTest.php, api/app/tests/Unit/v2/Registration/Uploader/LayDeputyshipUploaderTest.php
Clients that are associated with existing deputies are now created automatically as part of the daily ingest
Fixes DDLS-360
=> DDLS-360 Add new clients found in the LayDeputy csv

.github/workflows/_build-and-push.yml, .github/workflows/_codecov.yml, .github/workflows/_cycle-secrets.yml, .github/workflows/_ecr-scanning.yml, .github/workflows/_latest-deployed-image.yml, .github/workflows/_lint-terraform.yml, .github/workflows/_run-task.yml, .github/workflows/_run-terraform.yml, .github/workflows/_scale-services.yml, .github/workflows/_slack-notification.yml, .github/workflows/manual-spin-up-development.yml, .github/workflows/scheduled-cycle-secrets.yml, .github/workflows/scheduled-disaster-recovery-test.yml, .github/workflows/scheduled-resilience-tests.yml, .github/workflows/scheduled-restore-anon-preprod.yml, .github/workflows/scheduled-update-training-environment.yml, .github/workflows/scheduled-workspace-cleanup.yml, .github/workflows/workflow-destroy-on-merge.yml, .github/workflows/workflow-path-to-live.yml, .github/workflows/workflow-pull-request-path.yml, terraform/account/provider.tf, terraform/environment/provider.tf
Multi part ticket to move to limited permissions on state file write
Fixes DDLS-434
With this PR I just wanted to do some pre work to sure the permissions we were using on our terraform were all set in the right places and that we aren't inheriting secrets incorrectly. I decided to do this first so that any changes we then make to the terraform roles, won't be affected by this bit of work.
What I have mainly done here is: 
- Remove inherit for added security and specified what we're inheriting
- Moved the aws credentials login to directly prior to the step where it's needed so that any compromised package running in between could not exfiltrate the creds.
- Explicitly unset the creds after use. As the last step is pretty much always the step that needs the creds, this isn't explicitly …
=> DDLS-434 part 1 of move to limited permissions on state file write

README.md, docker-compose.override.yml, docker-compose.yml
Tweaks to readme and composer file for first time local environment creation.
Couple of changes:
- Removed some lingering code in docker compose files from the synch lambda that was removed in a previous PR
- Updated the readme file
NA
=> Minor fixes to readme for first time creation of local environment

api/app/api.env, api/app/src/Migrations/Version286.php, api/app/src/Migrations/Version287.php, terraform/environment/region/ecs_cluster.tf, terraform/environment/terraform.tfvars.json, terraform/environment/variables.tf
Allows us to separate account information from deputy entity and move one step closer to aligning Lay deputy data to Prof and PA.
Fixes DDLS-402
Adds migration script to add missing deputies to deputies table from user table. 
=> DDLS-402 - Migrate existing data from dd_user table to deputy table

docker-compose.behat.yml, terraform/account/provider.tf, terraform/environment/provider.tf
Use a more limited role that can only update the state file and dynamo lock db for digideps
Fixes DDLS-434
Use a more limited role
NA
=> DDLS-434c change state role to limited state write role

terraform/account/.envrc, terraform/account/provider.tf, terraform/account/variables.tf, terraform/environment/.envrc, terraform/environment/provider.tf, terraform/environment/region.tf, terraform/environment/region/variables.tf, terraform/environment/variables.tf
Now that everything works with the digideps-custom-ci role I have switched the access to be the same as this on old digideps-ci role and this PR switches us back to using that name so we don't need two vars for digideps-ci
=> DDLS-434f swap back to digideps-ci with retricted access

api/app/tests/Behat/bootstrap/v2/Common/BaseFeatureContext.php, api/app/tests/Behat/features-v2/acl/login/login.feature
Non primary accounts that have no active clients associated with them are taken to the add client screen instead of the ‘use your other account’ screen.
Fixes DDLS-370
Added in test to cover the scenario where secondary account with discharged client tries to login and is logged out and flash message appears with primary email address to login with.
=> DDLS-370 Non primary accounts should get redirect message instead of add client

api/app/src/Entity/Client.php, api/app/src/Entity/CourtOrder.php, api/app/src/Migrations/Version287.php
Create a 1 to many association between clients and court orders (one client can have 1 or more court orders, but each court order belongs to a single client).
Fixes DDLS-450
Add client property to Court Order entity
Add court orders property of type array (as more than one needs to be stored) to Client entity
Create new migration for this relationship with client id being added as a foreign key to Court Order table
=> DDLS-450 Associate clients with court orders (database changes)

api/app/src/Entity/CourtOrder.php, api/app/src/Entity/Report/Report.php, api/app/src/Migrations/Version288.php
Reasoning: due to hybrids & a need to link both court-orders of the hybrid to the report a link table (many-to-many) for court orders and reports is required.
Fixes DDLS-454
The approach is similar to the one used for deputy_case table.
ORM\JoinTable within Doctrine has been used to create the many-to-many relationship.
Delete cascade has also been added to the links in the JoinTable so that if the court order or report is deleted then the relationship is also deleted in the court_order_report table.
=> DDLS-454 Create a link table (many-to-many) for court-orders & reports

client/app/tests/phpunit/Event/ClientDeletedEventTest.php, client/app/tests/phpunit/Event/UserUpdatedEventTest.php, client/app/tests/phpunit/phpunit.xml
The phpunit.xml config for the client unit tests does not include the Event directory mentioned, so these tests are being ignored.
Fixes DDLS-452
Added in Event folder to phpunit.xml file for client unit tests.
Fixed failing tests in Event folder now being included.
=> DDLS-452 Event tests (in client/app/tests/Event) are not included in suite

api/app/src/Entity/CourtOrder.php, api/app/src/Entity/CourtOrderDeputy.php, api/app/src/Entity/Deputy.php, api/app/src/Migrations/Version288.php, api/app/src/Migrations/Version289.php, api/app/tests/Unit/Entity/DeputyIntegrationTest.php, api/app/tests/Unit/Entity/DeputyTest.php, docs/TESTING.md
As part of the database change work, this PR is to add a link table between court orders and deputies so that one deputy can have many court orders, and one court order can have many deputies.
Fixes DDLS-451
- Create CourtOrderDeputy entity class (which acts as the link table) 
- Getter method added to Deputy entity to retrieve court order objects and discharged property
- Define ManytoOne relationship with CourtOrder and Deputy entities
- Generate Doctrine migration 
- Add unit and integration test 
Note: associateWithCourtOrder method has been added to the Deputy entity class temporarily to show how the association would work between the link table and associated entities, this logic would eventually move into a factory class. The integration test would also get replaced with a more …
=> DDLS-451: Associate deputies with court orders (database changes)

terraform/environment/region/cloudwatch_scheduled_events.tf, terraform/environment/region/cloudwatch_scheduled_events_checks.tf, terraform/environment/region/variables.tf
We need to create and implement a new job within cloudwatch scheduled events to handle the execution of the nightly Court Order CSV job, ensuring it runs at the designated time each night. 
As this is a DB operation, you will need to make sure that no other tasks are interfering with the DB, you should also consider that this needs to run before the other CSV jobs (Lay, PA & Prof)
You can find examples of other scheduled jobs in the file cloudwatch_scheduled_events.tf
The results of the job will also need to be posted to the slack channel opg-digideps-scheduled-jobs, this will also require a separate cloudwatch task to be created, examples of this can be found within cloudwatch_scheduled_events_checks.tf
Fixes DDLS-486
_Any tips …
=> DDLS-486 - Create scheduled task within Cloudwatch for new Court Order CSV Job

client/app/src/Controller/Ndr/NdrController.php, client/app/src/Entity/Ndr/Ndr.php, client/app/src/Service/Client/Internal/NdrApi.php, client/app/tests/phpunit/Entity/Ndr/NdrTest.php
When important data for the submission is missing for whatever reason, create exception before creating the report pdf and doing other updates
Fixes DDLS-485
This is the first in a number of submission related bug fixes. This does a check early on for casenumber and court_date and if they're missing it raises an exception that breaks the request early. I'm also logging instances of missing address and postcode as although this would not break the submit (and hence I don't raise exception), it would be useful to see how often we're missing the address and postcode.
For the unit tests I'm using createMock as the prophesise was giving deprecation warnings.
=> DDLS-485 check submission valid for NDR before submitting

api/app/src/Repository/DocumentRepository.php
Document syncing issue, SQL fails to retrieve documents as no ID has been passed.
Fixes DDLS-484
Adds a check to make sure we have a value before adding to the array of ID's
=> DDLS-484 - BUG - Documents stuck at IN PROGRESS

.github/workflows/_build-and-push.yml, api/app/scripts/wait-for-db.sh, api/docker/app/Dockerfile, api/docker/web/Dockerfile, client/docker/app/Dockerfile, client/docker/web/Dockerfile, file-scanner/Dockerfile, terraform/environment/region/ecs_service_admin.tf, terraform/environment/region/ecs_service_api.tf, terraform/environment/region/ecs_service_front.tf, terraform/environment/region/ecs_service_htmltopdf.tf, terraform/environment/region/ecs_service_scan.tf, terraform/environment/region/ecs_service_sirius_files_sync.tf, terraform/environment/region/ecs_task_analyse.tf, terraform/environment/region/ecs_task_backup.tf, terraform/environment/region/ecs_task_check_csv_upload.tf, terraform/environment/region/ecs_task_integration_tests.tf, terraform/environment/region/ecs_task_performance_data.tf, terraform/environment/region/ecs_task_reset_database.tf, terraform/environment/region/ecs_task_resilience_tests.tf, terraform/environment/region/ecs_task_restore.tf, terraform/environment/region/ecs_task_restore_from_production.tf, terraform/environment/region/ecs_task_sleep_mode.tf, terraform/environment/region/ecs_task_smoke_tests.tf, terraform/environment/region/modules/disaster_recovery/ecs.tf, terraform/environment/region/modules/task/main.tf, terraform/environment/region/modules/task/variables.tf, terraform/environment/region/modules/task/versions.tf
Tested building the images without the cache and they build much more respectable time now. I've used native runners instead of QEMU and that seems to help nicely as it doesn't emulate anymore and just builds for the environment that we want.
=> DDLS-498 build for graviton architecture (with more testing)

api/app/src/Entity/User.php, api/app/src/Repository/UserRepository.php, api/app/src/Security/ClientVoter.php, api/app/src/Security/OrganisationVoter.php, api/app/src/Security/UserVoter.php, api/app/tests/Unit/Service/Auth/AuthServiceTest.php, api/app/tests/Unit/Service/OrganisationRestHandlerTest.php, client/app/src/Security/ClientContactVoter.php
Update some method signatures to be compatible with Symfony v6
=> Improve compatibility with Symfony 6

api/app/src/Kernel.php
- getRootDir is no longer used after migration to Symfony 5
- getLogDir is set to the same value in the parent Kernel
- getCacheDir is set to a subdirectory of var/cache in parent Kernel, so overriding is not necessary
Simplify config maintenance
=> Remove unnecessary api config

.github/workflows/_cycle-secrets.yml, .github/workflows/_ecr-scanning.yml, .github/workflows/_run-terraform.yml, .github/workflows/_slack-notification.yml, .github/workflows/_tests-miscellaneous.yml, .github/workflows/scheduled-disaster-recovery-test.yml, .github/workflows/scheduled-workspace-cleanup.yml, renovate.json, terraform/environment/region/cloudwatch_scheduled_events_checks.tf
only use shas that have attached release rather than just commit to main in renovate.
Fixes DDLS-520
Add helper and manually do the python helper.
[_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about DigiDeps_
](https://docs.renovatebot.com/presets-helpers/)
=> DDLS-520 use versions helper for renovate

client/app/src/Controller/SettingsController.php, client/app/templates/Admin/Organisation/add-user.html.twig
Errors were thrown on certain endpoints following investigations into [DDLS-505](https://opgtransform.atlassian.net/jira/software/c/projects/DDLS/boards/197?selectedIssue=DDLS-505), and were thrown whilst in dev mode with debug enabled.
Whilst these specific errors cause no direct issues to users and aren't thrown when debug is disabled, they still present areas to tighten up on on how variables are set and queried in twig templates.
Fixes DDLS-549
- Set value on variable passed to Twig template for organisations - related to org/settings route
- Build on conditional logic to exclude null user id's - related to admin/organisations/{orgId}/add-user route
[DDLS-505]: …
=> DDLS-549: Add fixes raised by enable debug mode with twig templates

client/app/src/Kernel.php
- getRootDir is no longer used after migration to Symfony 5
- getLogDir is set to the same value in the parent Kernel
- getCacheDir is set to a subdirectory of var/cache in parent Kernel, so overriding is not necessary
=> Remove unnecessary client config

.github/workflows/_phpstan-client.yml, .github/workflows/workflow-pull-request-path.yml, Makefile, client/app/phpstan-baseline.neon, client/app/phpstan.neon, client/app/src/Command/ProcessLayCSVCommand.php, client/app/src/Command/ProcessOrgCSVCommand.php, client/app/src/Form/Admin/FullReviewChecklistType.php, client/docker/app/Dockerfile, docker-compose.override.yml
Add PHPStan checks for client app to CI to catch issues that are easy to miss in manual review
Fixes DDLS-579
=> Add PHPStan to client in CI

client/app/config/services.yml, client/app/src/Service/OrgService.php, client/app/src/Service/Redirector.php, client/app/tests/phpunit/Service/RedirectorTest.php
Injecting the session into services and controllers is deprecated since Symfony 5.3 and removed in 6.
Recommendation is to avoid this entirely, but where it is necessary inject the RequestStack.
Contributes to DDLS-572
https://symfony.com/blog/new-in-symfony-5-3-session-service-deprecation
=> DDLS-572 Replace injection of session

client/app/config/packages/local/monolog.yml, client/app/templates/Layouts/moj_template.html.twig
See more information in some log messages locally to help with debugging
Also, add a couple of is null/defined checks to google analytics to remove some twig rendering errors
=> Enable stacktraces for local logging

client/app/phpstan-baseline.neon, client/app/src/Controller/Admin/Client/SearchController.php, client/app/src/Controller/Admin/ReportSubmissionController.php, client/app/src/Controller/SettingsController.php, client/app/src/Security/LoginFormAuthenticator.php
Getting non scalar values (Objects, arrays, etc), using InputBag->get is deprecated and throws an exception in Symfony 6+
Contributes to DDLS-572
=> DDLS-572 Stop getting arrays with InputBag->get

api/app/src/Command/SatisfactionPerformanceStatsCommand.php
Wrong format. The scores have - instead of _. 
Fixes DDLS-580
Looks like we were already trying to do this except the replace was the wrong way round! 
NA
=> DDLS-580 fix formatting bug in satisfaction score extract

api/app/tests/Unit/Service/File/Storage/S3StorageTest.php, client/app/composer.json, client/app/composer.lock, client/app/src/Controller/Admin/ReportSubmissionController.php, client/app/tests/phpunit/Entity/Ndr/NdrTest.php, client/app/tests/phpunit/EventListener/SessionListenerTest.php, client/app/tests/phpunit/Form/Report/Asset/AssetTypeTitleTest.php, client/app/tests/phpunit/Service/Audit/AuditEventsTest.php, client/app/tests/phpunit/Service/Client/TokenStorage/RedisStorageTest.php, client/app/tests/phpunit/Service/DocumentServiceTest.php, client/app/tests/phpunit/Service/File/S3FileUploaderTest.php, client/app/tests/phpunit/Service/File/Storage/S3StorageTest.php, client/app/tests/phpunit/Service/JWT/JWTServiceTest.php, client/app/tests/phpunit/Service/Mailer/MailSenderTest.php, client/app/tests/phpunit/Service/ReportSectionLinksServiceTest.php, client/app/tests/phpunit/Service/RequestIdLoggerProcessorTest.php, client/app/tests/phpunit/Twig/ComponentsExtensionTest.php, client/docker/app/Dockerfile
Move Client to PHP 8.2
Fixes DDLS-625
=>  DDLS-625 Move Client to PHP 8.2

api/app/src/Entity/Organisation.php, api/app/src/Entity/PreRegistration.php, api/app/src/Model/SelfRegisterData.php
Convert API Symfony Validator annotations to attributes as they have various advantages
Fixes DDLS-627
Use rector and then manually review
=> DDLS-627 API Symfony Validator attributes

client/app/phpstan-baseline.neon, client/app/src/Service/Client/Internal/PreRegistrationApi.php, client/app/src/Service/Client/RestClient.php, client/app/tests/phpunit/Service/DocumentServiceTest.php
Simplify RestClient->delete
Using RestClient->apiCall isn't really needed, as it's always used in one way. So this should make the logic easier to read
=> Simplify RestClient->delete

.github/workflows/_run-task.yml, client/app/src/Form/Report/DecisionType.php, client/app/src/Service/StringUtils.php, client/app/tests/phpunit/Service/StringUtilsTest.php
Cleanup additional carriage returns
Fixes DDLS-623
Decided that as under normal circumstances the report pdf seems to remove extra new line formatting anyway, I thought I would clean it up as input.
Decisions made:
- Use reuseable StringUtils service instead of doing it inline so that I can unit test it easily and so we can use it in other places
- Apply it as a listener to that specific form instead of globally. I don't know if there are parts of the app where we might want additional formatting and didn't want to break anything.
- Do it at the form level rather than pdf generator level or DB level. Stop bad data at source is better in most circumstances.
Learnt about listeners on forms. Didn't know we had any of that :)
=> DDLS-623 do some cleanup on additional carriage returns on form entry

api/app/tests/Behat/bootstrap/v2/Reporting/Sections/ClientBenefitsCheckSectionTrait.php, api/app/tests/Behat/bootstrap/v2/Reporting/Sections/DeputyExpensesSectionTrait.php, api/app/tests/Behat/bootstrap/v2/Reporting/Sections/GiftsSectionTrait.php, api/app/tests/Behat/bootstrap/v2/Reporting/Sections/MoneyInSectionTrait.php, api/app/tests/Behat/bootstrap/v2/Reporting/Sections/MoneyOutSectionTrait.php, client/app/templates/Ndr/Asset/Other/_list_item.html.twig, client/app/templates/Ndr/BankAccount/_list.html.twig, client/app/templates/Report/BankAccount/_list.html.twig, client/app/templates/Report/ClientBenefitsCheck/_answers.html.twig, client/app/templates/Report/Contact/_list.html.twig, client/app/templates/Report/Debt/_answers.html.twig, client/app/templates/Report/DeputyExpense/_list.html.twig, client/app/templates/Report/Gift/_list.html.twig, client/app/templates/Report/MoneyIn/_list.html.twig, client/app/templates/Report/MoneyInShort/_answers.html.twig, client/app/templates/Report/MoneyOut/_list.html.twig, client/app/templates/Report/MoneyOutShort/_answers.html.twig, client/app/templates/Report/MoneyTransfer/_list.html.twig
Update summary pages to follow pattern of bold headers and non bold explanations.
Screenshots of summary pages that didn't follow this pattern are included in the ticket. 
Fixes DDLS-566
=> DDLS-566: Clean up summary pages to reflect bold headers and unbold user input

api/app/src/Repository/StagingDeputyshipRepository.php, api/app/src/Repository/StagingSelectedCandidateRepository.php, api/app/src/v2/Registration/DeputyshipProcessing/CourtOrderReportCandidatesFactory.php, api/app/src/v2/Registration/DeputyshipProcessing/DeputyshipCandidatesSelectorResult.php, api/app/src/v2/Registration/DeputyshipProcessing/DeputyshipsCandidatesSelector.php, api/app/tests/Integration/v2/Registration/DeputyshipProcessing/CourtOrderReportCandidatesFactoryIntegrationTest.php, api/app/tests/Unit/v2/Registration/DeputyshipProcessing/CourtOrderReportCandidatesFactoryTest.php, api/app/tests/Unit/v2/Registration/DeputyshipProcessing/DeputyshipsCandidatesSelectorTest.php
Fix the ingest process up to the point where it generates candidate objects.
Due to memory issues, the number of candidate objects returned to the builder (not yet implemented) is limited to 100. This is so that the rest of the process is able to run. The limit will be removed and made memory-efficient in the next ticket in this series (DDLS-552).
Fixes DDLS-653
=> DDLS-653 Fix out of memory errors during deputyships ingest

Makefile, api/app/scripts/api_integration_test.sh
The Makefile now has a command that can run single test suite or single test case within a test suite.
Fixes DDLS-647
=> DDLS-647: Add new command to run individual api integration tests

Makefile
* INTEGRATION_SELECTION appeared twice in Makefile, so second appearance overrode the first time it was set
* Should use ":=" so that the variable's value is only set if not set by user in make env
* Don't require INTEGRATION_SELECTION setting for solo integration test, as this value is always the same
These changes allow `make api-integration-tests` continue to work without requiring the user to specify `INTEGRATION_SELECTION=selection-all`.
=> Solo integration test changes make api-integration-tests target fail

api/app/phpstan-baseline.neon, api/app/src/Controller/Ndr/NdrController.php, api/app/src/Controller/Report/ReportController.php, api/app/src/Entity/Client.php, api/app/src/Entity/Report/Report.php, api/app/src/Repository/PreRegistrationRepository.php, api/app/src/Service/ReportService.php, api/app/tests/Unit/Service/ReportServiceTest.php
Provides evidence to help resolve DDLS-631 (and subsequent tickets)
The main change is to add a logger to the ReportService, but this highlighted numerous type hinting, linting, phpstan etc. errors which I also fixed.
=> DDLS-631 Log where duplicate reports are potentially being created

api/app/tests/Behat/bootstrap/v2/ReportSubmission/ReportSubmissionTrait.php, api/app/tests/Behat/bootstrap/v2/Reporting/Sections/DocumentsSectionTrait.php, api/app/tests/Behat/features-v2/report-submission/attaching-further-documents.feature, client/app/src/Controller/Report/DocumentController.php, client/app/templates/Layouts/application.html.twig, client/app/templates/Macros/macros.html.twig, client/app/templates/Report/Document/_list_submitted.html.twig
Amends user flow when a user removes a selected file before submitting to OPG - this applies to post submission doc uploads only.
User now has a simplified one click action to remove the file, instead of a 2 step process.
Fixes DDLS-689
- Redirect user back to document upload page when clicking the Remove link
- Utilised existing deletion logic but expanded on conditional to render updated flash message on the upload page
=> DDLS-689: Remove selected file from the current doc upload page

terraform/environment/scripts/cycle_secrets/cycle_secrets.py
Fixes a issue that causes noise in our logs after the cycle process
Refresh the containers so that the container pulls latest secret
NA
=> fix for cycle db issue

api/app/scripts/readonly_user_setup/_0_readonly_user_create.sql, terraform/environment/region/cloudwatch_insights_queries.tf
Checks if the env has rds_iam so it does not fail the entire script. Local Env for example wont have this role.
=> RDS_IAM Check

terraform/account/region/modules/ssm_ec2_instance/boot.sh
This change will:
Enable the MOTD by using the MOTD Manager.
Fix the bug where you need to turn on the instance twice for it to work.
=> Added fixes to the SSM instance

api/app/phpstan-baseline.neon, api/app/src/Controller/Ndr/AccountController.php, api/app/src/Controller/Ndr/AssetController.php, api/app/src/Controller/Ndr/ExpenseController.php, api/app/src/Controller/Ndr/NdrController.php, api/app/src/Controller/Ndr/VisitsCareController.php
Move Ndr controllers to Symfony core Security as Sensio is abandoned and will receive no further updates
Contributes to DDLS-862
Apply Rector rules to automatically update the Symfony conventions and manually review the changes
=> DDLS-862 Move Ndr controllers to Symfony core Security

api/app/composer.json, api/app/composer.lock, api/app/config/bundles.php, api/app/config/packages/sensio_framework_extra.yml, api/app/phpstan-baseline.neon, api/app/src/Entity/Ndr/VisitsCare.php, api/app/src/v2/Controller/ClientController.php, api/app/src/v2/Controller/CourtOrderController.php, api/app/src/v2/Controller/DeputyController.php, api/app/src/v2/Controller/OrganisationController.php, api/app/src/v2/Fixture/Controller/FixtureController.php, api/app/src/v2/Registration/Controller/LayDeputyshipUploadController.php, api/app/src/v2/Registration/Controller/OrgDeputyshipController.php, api/app/src/v2/Tools/Controller/ToolsController.php, api/app/tests/Integration/v2/Controller/OrganisationControllerTest.php
Remove sensio/framework-extra-bundle from the API as it is no longer supported and features were moved to core symfony
Fixes DDLS-862
=> DDLS-862 Remove sensio/framework-extra-bundle from the API

api/app/composer.json, api/app/composer.lock
Removes PHP 8.4 deprecation warnings
=> Update gbprod/uuid-normalizer to v7.0.2
