- shared/events.tf
There are still targets attached to it
> Reinstate nightly event rule

- environment/terraform.tfvars.json
Final fix to our pipeline based off DDPB-3031
Fixes DDPB-3031
We had incorrect environment variable for preprod set 
NA
> fix the master env state source value

- environment/dns_private.tf
Release part 2 of ddpb-3192
Fixes DDPB-3226
See ddpb-3192
See ddpb-3192
> ddpb-3226 update dns records to point to new rep groups

- environment/ecs.tf
Change log retention to 180 days
Fixes DDPB-3180
Add log retention
NA
> add retention

- .circleci/config.yml
- behat/tests/features/UserManagement/deleteUsers.feature
I'm going to self-merge these since the pipeline's broken and they'd just be tested twice otherwise
> DDPB-3204: Chaser fixes

- client/package-lock.json
- client/package.json
Just running `npm audit fix` now that our dependent packages have updated.
> Fix NPM vulnerabilities

- docs/AWS-DB-ACCESS.md
Just updating these following Jack needing access.
> Update cloud9 docs

- behat/tests/features-v2/CONTRIBUTING.md
- behat/tests/features-v2/report-submission/sections/CONTRIBUTING.md
To create stub folders and feature files for new feature-driven behat test suite.
Fixes DDPB-3399
Following from the conversation with Alex Saunders, I have created a folder for each high level feature of the application that we feel is mission critical, and broken down further within those features where necessary. 
For more information on the approach see the CONTRIBUTING.md file in the PR.
This is not set in stone and is easily adaptable especially at this early stage.
> DDPB-3399: Stub folders and feature files for new Behat

- behat/tests/behat.yml
- behat/tests/features-v2/acl/admin/navigation.feature
- behat/tests/features-v2/navigation/admin/navigation.feature
- client/src/AppBundle/Controller/Admin/FixtureController.php
- client/src/AppBundle/Resources/translations/admin-fixtures.en.yml
- client/src/AppBundle/Resources/translations/layout.en.yml
- client/src/AppBundle/Resources/views/Admin/Fixtures/index.html.twig
- client/src/AppBundle/Resources/views/Layouts/admin_moj_template.html.twig
Add navigation link for fixture endpoints to provide access to super admins.
Fixes DDPB-3251
> DDPB-3251 - Add fixture endpoints

- .circleci/config.yml
Forgot to update the master Circle workflow 🤦
> Update master workflow to run API unit tests on CircleCI

- .circleci/config.yml
- environment/api_rds.tf
To stop the database from being recreated and snapshots lost by terraform on a change. We have added 3 extra flags that should have been there which should stop it happening again!!
These are 
- "database protection" to prevent destruction
- "delete_automated_backups" to false which will stop automated backup being destroyed on destruction of database
- "skip_final_snapshot" to false so that final snapshot will be taken before destruction in the case where we force a destruction.
Fixes DDPB-3469
Change the flags in terraform.
NA
> stop database from being deleted on change

- README.md
Forcing first main build after rebuilding webhooks.
> Force first main build

- .circleci/config.yml
Upgrade tf version
Fixes DDPB-3507v2
upgrades tf version
> DDPB-3507v2 update terraform version

- Makefile
- client/src/AppBundle/Service/Client/Sirius/SiriusApiGatewayClient.php
- client/tests/phpunit/Pact/SiriusApiGatewayClientTest.php
- client/tests/phpunit/Service/Client/Sirius/SiriusApiGatewayClientTest.php
- docker-compose.dev.yml
- environment/mock_sirius_integration_service.tf
- environment/mock_sirius_integration_sg.tf
Fixes the broken URL of the OpenAPI spec required for behat tests to pass and upgrades the API version to v2.
> Point to v2 of integration OpenAPI spec

- .circleci/config.yml
- environment/provider.tf
- shared/provider.tf
Pinning version due to breaking change in v3
> Ping provider version

- .circleci/config.yml
- client/Dockerfile-dev
- client/app/config/services.yml
- client/docker/env/frontend.env
- client/docker/extra/robots.txt
- client/src/AppBundle/Controller/IndexController.php
- client/src/AppBundle/Resources/translations/home.en.yml
- client/src/AppBundle/Resources/views/Index/index.html.twig
- docker-compose.ci.dev.yml
- ecs_helper/cmd/circle_builds/cancel_redundant_builds.py
- environment/admin_service.tf
- environment/ecr.tf
- environment/front_service.tf
- environment/terraform.tfvars.json
We need a stable environment which can be used by interested parties to access the application. It should be publicly available but not indexed by search engines and it should be clear it's not a production environment to users.
- Also added minor fix to cancel redundant builds script
Fixes DDPB-3532
Created a new environment that gets refreshed as part of merge to main. Created a banner to make it obvious that its not prod env and added robots.txt in the web folder to make it non searchable.
Was a bit of a faff getting the robots.txt to only be included on the client image and to get the banner to appear only on this image.
> DDPB-3532 create development environment

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Add a contributing.md file to describe how we accept contributions from external parties.
https://www.contributor-covenant.org/ provides a useful boilerplate!
- [ /] I have performed a self-review of my own code
- [/ ] I have updated documentation (Confluence/ADR/tech debt doc) where relevant
> Rough draft of a contributing.md and COC to guide external contributors.

- shared/s3_replication.tf
This will teach me to both skip ci AND not run a terraform plan locally 🤦
> reference data object index correctly

- client/src/AppBundle/Controller/Admin/FixtureController.php
Doing some CS fixes to get integration pipeline to run.
> Force integration to run

- shared/document_sync.tf
- shared/variables.tf
Completely missed the naming of prod bucket in last ticket. This will apply permissions to correct name.
> DDPB-3659 rework for prod

- shared/subnet_private.tf
Fix a typo in the shared module that the pipeline didn't pick up.
> DDPB-3188 - Fix copy/paste error

- shared/cloud9.tf
> DDPB-3188 - Remove Name from Cloud9 Tags

- shared/document_sync.tf
- wkhtmltopdf/Dockerfile
> Add ListBucket role policy so we get 404s rather than 403s when a resource isn't in S3

- environment/api_rds.tf
> Ensure training is in line with production for postgres version

- environment/disaster_recovery/kms.tf
- environment/terraform.tfvars.json
Totally missed this piece of code! Needs quick fix!!
> DDPB-3651 use dynamic account

- docs/DISASTER_RECOVERY.md
Add DR documentation to repo.
Fixes DDPB-3621
NA
NA
> DDPB-3621 add dr docs

- .circleci/config.yml
Now removing the metrics curl step from the pipeline as the infra for the project is no more.
> Remove metrics pipeline step

- client/src/AppBundle/Resources/views/Ndr/Ndr/_header.html.twig
- client/src/AppBundle/Resources/views/Ndr/Ndr/overview.html.twig
Updates ready to submit banner from old style full page to GDS success banner.
Fixes DDPB-3761
> DDPB-3761: Update NDR ready to submit banner to use GDS component

- client/src/AppBundle/Resources/views/Index/terms.html.twig
Updated terms of use to reflect PA and Prof users
Fixes DDPB-2838
> DDPB-2838: Updated mark up for terms of use

- .circleci/config.yml
Fixup: Somehow missed the terraform init in the move around.
> add terraform init

- .circleci/config.yml
didn't quite get workflow dependencies right in main.
> DDPB-3755b fix workflow dependency in main pipeline

- client/src/Controller/ManageController.php
Missed one template reference during #563 - fixing now.
> Fix pingdom healthcheck template reference

- environment/admin_sg.tf
- environment/api_sg.tf
- environment/terraform.tfvars.json
- environment/variables.tf
Update the IP list against development for the BSI to access our admin env
Fixes DDPB-3843
Concat the admin IPs as we need the original ones but don't do same with front ones as we still want 0.0.0.0/0 to replace list on these ones.
NA
> DDPB-3843 update ip whitelist for BSI audit

- environment/admin_sg.tf
- environment/api_sg.tf
- environment/terraform.tfvars.json
- environment/variables.tf
Remove all the BSI access
Fixes DDPB-3867
Remove access we set up for BSI to dev
NA
> DDPB-3867 remove all the BSI access

- api/Dockerfile
- behat/Dockerfile
- client/Dockerfile
Composer updating to php 8.0.1 in latest version and we're not ready for that yet.
> DDPB-3870 lock composer

- client/.editorconfig
- client/assets/javascripts/__tests__/globals.js
- client/assets/javascripts/__tests__/modules/googleAnalyticsEvents.test.js
- client/assets/javascripts/main.js
- client/assets/javascripts/modules/googleAnalyticsEvents.js
- client/config/config.yml
- client/package-lock.json
- client/package.json
- client/src/Twig/FormFieldsExtension.php
- client/templates/Client/add.html.twig
- client/templates/Components/Form/_button.html.twig
- client/templates/Layouts/_google_analytics_events_gtag.html.twig
- client/templates/Layouts/application.html.twig
- client/templates/Layouts/moj_template.html.twig
- client/templates/Report/_report_form.html.twig
- client/templates/User/activate.html.twig
- client/templates/User/details.html.twig
- client/templates/User/register.html.twig
- docs/PULL_REQUEST_TEMPLATE.md
- docs/runbooks/GOOGLE-ANALYTICS.md
Adds in some scaffolding to standardise how we send Google Analytics events to Google.
Fixes DDPB-3895
I've added some Javascript code that checks for elements containing `data-attribute=ga-event` which then extracts other `data-*` values and pings of an event to Google for tracking. I've updated the twig form extensions we have to have to include a `form_submit_ga()` function so we can extend this to other forms where we need to without having to touch markup. We may want to add more of these helpers but that seemed out of scope for this ticket.
I also made the decision to update our twig extension helpers to all user `TwigFunction` rather than `Simple_TwigFunction` which was deprecated. I was going to leave this for a separate PR but I needed the newer function to get this code working …
> DDPB-3895: Send a Google Analytics event to Google

- client/Dockerfile
- client/package-lock.json
- client/package.json
- client/src/Controller/AbstractController.php
- client/templates/Settings/passwordEdit.html.twig
- client/templates/User/activate.html.twig
- client/templates/User/passwordReset.html.twig
- client/translations/validators.en.yml
Whilst looking into the activation issues, a few things came up. This addresses some things:
- Issues caused by double clicking it seems (probably better way of stopping this but added some tags around the submits to stop it)
- there was a missing template
- there was a template issue where we're calling characters letters
- Also chucking in an upgrade to dependency that dependabot mentioned
Fixes DDPB-3919
NA
The activation issue was very tricky to work out but obvious in hindsight (shout out to Charles for his help). 
The webpack upgrade was a bit picky. We can't upgrade node any further with the versions of packages we have. There's also a fun error based on the docker version being used by circle for remote_docker images that means this is the package selection chosen...
> DDPB-3919 update dependencies and fix activation issues

- client/package-lock.json
- client/package.json
- client/webpack.config.js
> webpack copy update

- client/package-lock.json
- client/package.json
- docker-compose.dev.yml
Update webpack
Fixes DDPB-3933
Update in npm and thoroughly check the app for java errors
> DDPB-3933 follow up pr for webpack

- client/public/error.html
- client/templates/Layouts/admin_moj_template.html.twig
- client/templates/Layouts/moj_template.html.twig
- docs/runbooks/MAINTENANCE-MODE.md
Remove the beta banner on the website from all pages
Fixes DDPB-3775
> [DDPB-3775] removed beta banner from all pages

- docker-compose.yml
- environment/ecr.tf
- environment/scan.tf
- environment/smoke_test.tf
Because the clamav docker provider didn't previously version their images we ended up using our own image which is now quite out of date and seems to be falling over on initial build with a OOM exception.
Tried with the latest fixed version (yes they seem to now be versioning) of the container and it seems to work without falling over on build. yay.
Also fixed a small path error that was missed with the behat move.
Fixes DDPB-3982
NA
NA
> DDPB-3982 fix bug with terraform apply

- .circleci/config.yml
Apparently we should have upgraded to 14.11 at min as part of the codecov fallout.
Fixes DDPB-3984
NA
NA
> DDPB-3984 update tf version

- .github/workflows/report.yml
Use our scanning tool to generate a list of packages used in manifest & lock files on the repo
> add scanning report

- Makefile
- api/tests/Behat/behat.yml
- api/tests/Behat/bootstrap/v2/Common/ExpectedResultsTrait.php
- api/tests/Behat/bootstrap/v2/Common/IShouldBeOnTrait.php
- api/tests/Behat/bootstrap/v2/Common/IVisitFrontendTrait.php
- api/tests/Behat/bootstrap/v2/Common/PageUrlsTrait.php
- api/tests/Behat/bootstrap/v2/Reporting/Sections/DebtsSectionTrait.php
- api/tests/Behat/bootstrap/v2/Reporting/Sections/ReportingSectionsFeatureContext.php
- api/tests/Behat/features-v2/reporting/sections/debts/debts.feature
Rewriting the debt behat tests
Fixes DDPB-3484
> DDPB-3484 - Rewrite behat tests for the debts section

- api/Dockerfile
- client/Dockerfile
- docker-compose.dev.yml
Lock composer ver as bug stopping us build.
> lock composer

- .circleci/config.yml
- api/Dockerfile
- client/Dockerfile
- dr_backup/Dockerfile
- ecs_helper/check_ecr_scan_results/aws_ecr_scan_results.py
- wkhtmltopdf/Dockerfile
- wkhtmltopdf/docker-entrypoint.sh
Update all our images so they pass the ECR scans and make ECR scan notify us if they get sec vulnerabilities again (as there was a syntax error preventing notifications)
Fixes DDPB-4009
So there's a few interesting things going on here in this tiny PR which caused me some headache. It all boils down to having latest version of everything in the end though there were points I went off on completely different paths and went into the weeds with python... Also went into the weeds with alpine packages.. in the end it was more straight forward.
First thing! Locally you need at least docker desktop 3.3 on mac 
Next circle remote docker needs to be 20.10
This is so we can even build alpine image 3.14 (as security has been tightened up) which both the new php and python images i've used use as the …
> DDPB-4009 keep images updated

- api/tests/Behat/behat.yml
- api/tests/Behat/bootstrap/v2/Common/BaseFeatureContext.php
- api/tests/Behat/bootstrap/v2/Common/INavigateToAdminTrait.php
- api/tests/Behat/bootstrap/v2/Common/IShouldBeOnAdminTrait.php
- api/tests/Behat/bootstrap/v2/Common/UserDetails.php
- api/tests/Behat/bootstrap/v2/Helpers/FixtureHelper.php
- api/tests/Behat/bootstrap/v2/Reporting/Admin/ReportingAdminFeatureContext.php
- api/tests/Behat/bootstrap/v2/Reporting/Admin/ReportingChecklistTrait.php
- api/tests/Behat/features-v2/reporting/admin/checklist/checklist.feature
> [DDPB-3948] reporting checklist admin behat tests

- api/tests/Behat/behat.yml
- api/tests/Behat/bootstrap/v2/AppNotification/AppNotificationFeatureContext.php
- api/tests/Behat/bootstrap/v2/AppNotification/AppNotificationTrait.php
- api/tests/Behat/bootstrap/v2/Common/IShouldBeOnAdminTrait.php
- api/tests/Behat/bootstrap/v2/Common/IShouldBeOnFrontendTrait.php
- api/tests/Behat/bootstrap/v2/Common/IVisitAdminTrait.php
- api/tests/Behat/bootstrap/v2/Common/IVisitFrontendTrait.php
- api/tests/Behat/bootstrap/v2/Common/PageUrlsTrait.php
- api/tests/Behat/features-v2/app-notification/app-notification.feature
- api/tests/Behat/features-v2/reporting/sections/gifts/gifts.feature
behat rewrite for admin app notifications
Fixes DDPB-3951
> [DDPB-3951] behat rewrite for admin app notifications

- api/Dockerfile
- client/Dockerfile
Alpine version upgrade for security
Fixes DDPB-4075
Update php version. The python ones are already set to auto update.
NA
> DDPB-4075 update alpine version

- .circleci/config.yml
- aws_config
Further updates to ddpb-4092 to fix pipeline
> DDPB-4092b add pre profile and fix circle logic

- api/tests/Behat/behat.yml
- api/tests/Behat/bootstrap/v2/Common/IShouldBeOnFrontendTrait.php
- api/tests/Behat/bootstrap/v2/Common/IVisitFrontendTrait.php
- api/tests/Behat/bootstrap/v2/Common/PageUrlsTrait.php
- api/tests/Behat/bootstrap/v2/Reporting/Sections/ActionsSectionTrait.php
- api/tests/Behat/bootstrap/v2/Reporting/Sections/AdditionalInformationSectionTrait.php
- api/tests/Behat/bootstrap/v2/Reporting/Sections/AssetsSectionTrait.php
- api/tests/Behat/bootstrap/v2/Reporting/Sections/DeputyExpensesSectionTrait.php
- api/tests/Behat/bootstrap/v2/Reporting/Sections/IncomeBenefitsSectionTrait.php
- api/tests/Behat/bootstrap/v2/Reporting/Sections/ReportingSectionsFeatureContext.php
- api/tests/Behat/features-v2/reporting/sections/accounts/accounts.ndr.feature
- api/tests/Behat/features-v2/reporting/sections/actions/actions.ndr.feature
- api/tests/Behat/features-v2/reporting/sections/additional-information/additional-information.ndr.feature
- api/tests/Behat/features-v2/reporting/sections/assets/assets.ndr.feature
- api/tests/Behat/features-v2/reporting/sections/debts/debts.ndr.feature
- api/tests/Behat/features-v2/reporting/sections/deputy-expenses/deputy-expenses.ndr.feature
- api/tests/Behat/features-v2/reporting/sections/income-benefits/income-benefits.ndr.feature
- client/src/Twig/FormFieldsExtension.php
- client/templates/Ndr/Action/step.html.twig
- client/templates/Ndr/Asset/Other/add.html.twig
- client/templates/Ndr/DeputyExpense/_list.html.twig
- client/translations/validators.en.yml
This adds the missing income and benefits behat tests for NDR and updates current tests to incorporate the NDR part of the report
Fixes DDPB-4060
> [DDPB-4060] added missing NDR behat tests

- api/src/Entity/Report/Checklist.php
- api/src/Entity/Report/Report.php
- api/src/Migrations/Version259.php
- api/src/TestHelpers/ReportTestHelper.php
- api/tests/Behat/behat.yml
- api/tests/Behat/bootstrap/v2/Common/BaseFeatureContext.php
- api/tests/Behat/bootstrap/v2/Common/ReportTrait.php
- api/tests/Behat/bootstrap/v2/Reporting/Admin/ReportingAdminFeatureContext.php
- api/tests/Behat/bootstrap/v2/Reporting/Admin/ReportingChecklistTrait.php
- api/tests/Behat/bootstrap/v2/Reporting/Sections/ClientBenefitsCheckSectionTrait.php
- api/tests/Behat/bootstrap/v2/UserManagement/UserManagementFeatureContext.php
- api/tests/Behat/features-v2/report-checklist/checklist.lay.feature
- api/tests/Behat/features-v2/report-checklist/checklist.org.feature
- api/tests/Behat/features-v2/reporting/sections/client-benefits-check/client-benefits-check.lay.feature
- api/tests/Behat/features-v2/reporting/sections/client-benefits-check/client-benefits-check.org.feature
- client/src/Controller/Admin/Client/ReportController.php
- client/src/Controller/Report/ClientBenefitsCheckController.php
- client/src/Entity/Report/Checklist.php
- client/src/Form/Admin/ReportChecklistType.php
- client/templates/Admin/Client/Report/checklist.html.twig
- client/templates/Admin/Client/Report/partials/_client-benefits-check.html.twig
- client/templates/Admin/Client/Report/sidebar/_lodging.html.twig
- client/templates/Ndr/Debt/summary.html.twig
- client/templates/Report/ClientBenefitsCheck/_answers.html.twig
- client/templates/Report/ClientBenefitsCheck/summary.html.twig
- client/templates/Report/Debt/_answers.html.twig
- client/translations/admin-checklist.en.yml
- docs/ADDING_REPORT_SECTIONS.md
Adds a question to the checklist for case managers to confirm if they are satisfied with the deputies answers for the Client Benefits Check section of the form.
Fixes DDPB-4018
> DDPB-4018: Add checklist for client benefits check

- CODEOWNERS
- Makefile
Updating the Makefile to have a help command and added a codeowners file for reviewers.
This was done inside DDPB-3997 but with that ticket now being on hold I thought I'd pull out these 2 changes
> [makefile-update] added codeowners file and updated makefile

- client/package-lock.json
- client/package.json
> [DDPB-4034b] Updated jest because that also relied on json-schema

- docker-compose.yml
- environment/scan.tf
Adding a temporary fix for a maintained version of our scanner rest API while we look at longer-term solutions.
Fixes DDPB-4191.
> DDPB-4191: Prefer acsauk/clamav-rest-1 to lokori/clamav-rest

- .circleci/config.yml
- api/tests/Behat/behat.yml
- environment/waf.tf
Associate the ALBs with WAF to enable the firewall
> DDPB-4193 - associate ALBs with the WAF

- environment/terraform.tfvars.json
> correctly asscociate WAF

- .circleci/config.yml
- ecs_helper/check_ecr_scan_results/aws_ecr_scan_results.py
- ecs_helper/check_ecr_scan_results/requirements.txt
> DDPB-4195 - ECR Scan timeout

- shared/waf.tf
> Add rule exclusion to allow PDF uploads

- .github/labeller.yml
- .github/workflows/labeller.yml
> Add github PR labelling

- api/src/v2/Assembler/NamedDeputyAssembler.php
- api/src/v2/Registration/Uploader/OrgDeputyshipUploader.php
To make some SQL statements less complex I've started to persist the deputy address number alongside the deputy number.
Fixes DDPB-4212
> DDPB-4212: Start persisting Deputy Address Number

- environment/check_csv_uploaded.tf
> Added environment variables to CSV Upload Check container

- shared/cloud9.tf
> DDPB-4245 - specify c9 breakglass user

- api/src/Controller/ClientController.php
- api/src/TestHelpers/ClientTestHelper.php
- api/src/v2/Controller/ClientController.php
- api/tests/Behat/bootstrap/v2/ClientManagement/ClientManagementTrait.php
- api/tests/Behat/bootstrap/v2/Common/BaseFeatureContext.php
- api/tests/Behat/bootstrap/v2/Common/IShouldBeOnAdminTrait.php
- api/tests/Behat/bootstrap/v2/Common/IVisitAdminTrait.php
- api/tests/Behat/bootstrap/v2/Common/PageUrlsTrait.php
- api/tests/Behat/bootstrap/v2/Common/UserDetails.php
- api/tests/Behat/bootstrap/v2/Helpers/FixtureHelper.php
- api/tests/Behat/features-v2/client-management/admin/unarchive.feature
- client/src/Controller/Admin/Client/ClientController.php
- client/src/Service/Client/Internal/ClientApi.php
- client/src/Service/Client/RestClient.php
- client/templates/Admin/Client/Client/archived.html.twig
- client/templates/Admin/Client/Client/details.html.twig
- client/templates/Admin/Client/Client/unarchived.html.twig
- client/templates/Admin/Client/Search/search.html.twig
- client/templates/Layouts/application.html.twig
- client/translations/admin-clients.en.yml
- client/translations/common.en.yml
To allow high level admin users to unarchive a client for a deputy. A client may have been unarchived incorrectly or needs to be reported on by another deputy.
Fixes DDPB-3525
> DDPB-3525: Created a function to unarchive client from admin

- api/tests/Behat/bootstrap/v2/Reporting/Sections/ClientBenefitsCheckSectionTrait.php
- client/src/Controller/Report/ClientBenefitsCheckController.php
- client/translations/report-client-benefits-check.en.yml
As some of the content has changed, the error messages need to change in line.
These changes should provide a more clearer message to the user when there is an error, that aligns with the question being asked.
Fixes DDPB-4259
Updated translations with new messages.
Fixed an issue with pulling in data to remove 
> DDPB-4259 - Update error messages for Benefits section

- api/src/Controller/StatsController.php
- api/src/Repository/NdrAssetRepository.php
Doh 🤦  running this with the old code gave us £74 billion in managed assets - this should be the real figures now.
> Multiple by a decimal rather than whole number (doh)

- api/Dockerfile
- client/Dockerfile
Fixes https://nvd.nist.gov/vuln/detail/CVE-2022-23308
Fixes DDPB-4292
> DDPB-4292: Update libxml2

- api/Dockerfile
- client/Dockerfile
Fix our high security vuln alerts and make us more secure.
> Add openssl to force upgraded packages.

- ecs_helper/check_ecr_scan_results/aws_ecr_scan_results.py
> DDPB-4303 - remove description field from ecr scan results

- client/composer.json
- client/composer.lock
Fixes [CVE-2021-46743 - firebase/php-jwt](https://nvd.nist.gov/vuln/detail/CVE-2021-46743)
> DDPB-4311: Bump alphagov/notifications-php-client to ^4.0.1

- api/Dockerfile
- client/Dockerfile
> Run apk upgrade in build to pull in up to date busybox.

- api/Dockerfile
- client/Dockerfile
Updates `curl gzip xz xz-libs libcurl` from alpine defaults
> Patches libraries on alpine

- api/src/Entity/Client.php
- api/src/v2/Registration/Uploader/OrgDeputyshipUploader.php
- api/tests/Unit/Entity/ClientTest.php
Moves the enforcement of lowercasing case numbers from business logic to entity setter.
Fixes DDPB-4334.
> DDPB-4334: Enforce lowercased case number and provide update on updating reports

- docs/architecture/decisions/0005-audit-logs.md
Add decision record on audit logs (back-dated). Fixes DDPB-3340
> Add audit logs adr

- client/src/Service/Client/Internal/ClientApi.php
Fixes the registration flow that is broken for case manager-created user accounts. A behat test will follow in the next PR - getting this through so users can register.
Fixes DDPB-4342
> DDPB-4342: Refer to correct constant

- api/src/v2/Registration/Uploader/OrgDeputyshipUploader.php
- api/tests/Behat/features-v2/registration/ingest.org.sirius.feature
- api/tests/Unit/v2/Registration/Uploader/OrgDeputyshipUploaderTest.php
Disabling for now until we can trust the data coming from Sirius.
Fixes DDPB-4350
> DDPB-4350: Disable auto discharge for Org CSV upload

- api/src/FixtureFactory/PreRegistrationFactory.php
- api/src/v2/Fixture/Controller/FixtureController.php
- client/src/Controller/Admin/IndexController.php
A couple of bugs crept in during some recent changes following the CSV migration that has broken the lay co-deputy and org fixture endpoints. This change ensures we are referring to correctly named services and adds missing required fields when creating pre-registration entities and users.
Fixes DDPB-4361
> DDPB-4361: Fix fixtures

- .circleci/config.yml
Bit of a cleanup for 4373 as it notifies us too often
Fixes DDPB-4373
I think in the medium term we could move this to github actions but would need to test out the notifications etc. I think it does clog up circle pipeline too much having this run hourly in circle tbh. I'm looking at some actions bits on deputy reporting so can modify this again in the further ticket for other non prod environment teardown. I think for now this might be our best bet.
NA
> Ddpb 4373b

- client/src/Controller/ClientController.php
- client/src/Controller/UserController.php
- client/src/Event/RegistrationFailedEvent.php
- client/src/EventSubscriber/RegistrationFailedSubscriber.php
- client/src/Service/Audit/AuditEvents.php
Adding extra logging in to another route where we verify lay details during the reg flow.
> Ensure we log in both places a reg attempt can fail

- shared/go_redeployer/go.mod
Now forcing an update of the package in our requires.
Fixes DDPB-4351
> DDPB-4351: Force update of gopkg.in/yaml.v3

- Makefile
- api/src/DataFixtures/UserFixtures.php
- api/src/Entity/Ndr/BankAccount.php
- api/src/Entity/Report/BankAccount.php
- api/src/Service/BruteForce/AttemptsIncrementalWaitingChecker.php
- api/src/v2/Assembler/ClientAssembler.php
- api/src/v2/Registration/DTO/OrgDeputyshipDto.php
- client/src/Entity/BankAccountInterface.php
- client/src/Entity/Ndr/AssetProperty.php
- client/src/Entity/Ndr/BankAccount.php
- client/src/Entity/Report/AssetProperty.php
- client/src/Entity/Report/Checklist.php
- client/src/Entity/Report/Fee.php
- client/src/Service/HtmlToPdfGenerator.php
Fixes instances where we either refer to a nonexistent or undeclared property.
I've also expanded the make commands so we can pass level as an argument.
Fixes DDPB-4380
> DDPB-4380: PHPStan Level 1 errors - Undefined properties

- api/src/Entity/Ndr/AssetProperty.php
- api/src/Entity/Report/Contact.php
- client/src/Service/Client/Internal/UserApi.php
More PHPStan level one fixes; this time ensuring we aren't calling any undefined methods or constants.
Fixes DDPB-4381
Fixes DDPB-4390
> DDPB-4381, DDPB-4390: Fix undefined methods and constants

- docs/architecture/decisions/0006-jwts.md
Belatedly adding an ADR for JWTs.
Wide open to feedback on the level of detail or if the anything isn't quite right as this is my first ADR 🙏
> Add ADR for JWT

- api/src/v2/Controller/OrganisationController.php
- client/src/Entity/Ndr/Debt.php
- client/src/Entity/Report/Debt.php
Fixes the unused parameter and access to undefined property PHPStan Error.
Fixes DDPB-4385
Fixes two errors on the client and api side
> DDPB-4385: Unused parameter & access to undefined property

- shared/sync.tf
Was very tricky to test the change in dev env and I copied config from similar job elsewhere. It's breaking the sync process though so I am reverting and need to spend the time getting this right if we want to fix this tfsec warning.
> revert a tfsec change

- client/translations/ndr-income-benefits.en.yml
Removed a personal pronoun from translation file
Fixes DDPB-4482
> [DDPB-4482] removed pronoun from translation file

- client/assets/scss/_digideps.scss
- client/assets/scss/digideps/_emergency-banner.scss
- client/templates/Index/index.html.twig
- client/templates/Layouts/admin_moj_template.html.twig
- client/templates/Layouts/moj_template.html.twig
Added the emergency banner to the website -- currently hard-coded but will need to change when we have more time
> Added an emergency banner to website

- api/tests/Behat/features/v2/authentication/password-reset.feature
> Add unicode to the password reset feature to check it works

- .circleci/config.yml
- client/Dockerfile
- client/scripts/client-unit-tests.sh
- client/tests/phpunit/Validator/Constraints/CommonPasswordValidatorTest.php
- client/tests/phpunit/phpunit.xml
- ecs_helper/cmd/circle_builds/requirements.txt
Tom's work but with PHP unit verbose on, to see if it tells us anything.
.
> Remote docker changes, but with some additional config.

- shared/dns_firewall.tf
- shared/terraform.tfvars.json
- shared/variables.tf
Monitor outbound traffic against the VPC
Fixes DDPB-4248
Ran it in environment initially to get a good baseline of what we would be expecting. The current options allow everything through we would be expecting in development environment.
No blocking for now as we find out what is usual and what isn't in production environment.
NA
> DDPB-4248 monitor egress traffic

- docker-compose.yml
- environment/mock_sirius_integration_service.tf
- environment/variables.tf
There were a couple of places where we weren't pinning
Fixes DDPB-4514
This will pin us everywhere where it is needed.
NA
> DDPB-4514 pin specific versions of docker images 

- .circleci/config.yml
Using old way of doing it which now breaks. This fixes it
> update ecr login command

- api/src/Controller/CoDeputyController.php
- client/src/Command/ProcessLayCSVCommand.php
- client/src/Command/ProcessOrgCSVCommand.php
- client/src/Controller/Admin/IndexController.php
- client/templates/Admin/Index/index.html.twig
- client/templates/Admin/Index/uploadOrgUsers.html.twig
- client/templates/Admin/Index/uploadUsers.html.twig
Also added a status indicator to the current process
Fixes DDPB-4577
> [DDPB-4577] fixed bug where hybrid were not being caught in the process

- environment/admin_service.tf
- environment/api_service.tf
- environment/front_service.tf
- environment/htmltopdf_service.tf
- environment/mock_sirius_integration_service.tf
- environment/scan_service.tf
Lifecycle rule breaking the path to live. Can look into it further as seems like it should be right but putting it back to how it was for now.
> DDPB-4060b follow up to remove lifecycle changes

- api/tests/Behat/features-v2/registration/self-register.feature
- api/tests/Behat/fixtures/sirius-csvs/lay-2-rows-co-deputy.csv
> Fixing fixture CSV and renaming Test Scenario

- htmltopdf/Dockerfile
- htmltopdf/requirements.txt
> fix the missing ecr scan issue

- shared/.terraform.lock.hcl
- shared/variables.tf
> Remove Ste from Cloud 9

- .circleci/config.yml
missing some paths for dependabot to trigger pipeline
> sec fix for missing paths

- docs/queries/Balance Mismatches Report.sql
- docs/queries/QUERIES.md
Adding in the queries/functions used to extract the data for the report.
Fixes DDPB-4595
> DDPB-4595 - Balance Mismatches Report

- .github/renovate.json
Adds Renovate config, app already installed
> DDPB-4589 - add Renovate config

- client/composer.lock
Reverts ministryofjustice/opg-digideps#1108
> Revert "app: bump symfony/security-bundle from 5.4.11 to 5.4.20 in /client"

- Makefile
- client/package.json
- docker-compose.dev.yml
- docker-compose.override.yml
Cherry pick of the build fixes from the modernise JS branch to make it smaller to review.
Adds the following to the local build:
- app-up now mounts local folders so checking changes to JS/CSS is faster
- JS test and build targets. Including one for filtering by individual suite name to speed up testing one change.
- update to node 18 LTS
> Build fixes

- api/Dockerfile
- api/tests/Behat/run-tests-parallel.sh
Bump a variety of OS level packages
> Docker fixes

- client/Dockerfile
Operating system updates part 2
> Updates part 2

- docs/queries/Accounts per Report.sql
- docs/queries/Balance Mismatches Report.sql
- docs/queries/Money Transfers per Report.sql
> DDPB 4462 & 4463: Money Transfers and Accounts queries

- api/composer.lock
- client/composer.lock
> Updating security bundle and fixing version of browser-kit

- ecs_helper/go.mod
- ecs_helper/go.sum
- ecs_helper/vendor/github.com/aws/aws-sdk-go/aws/credentials/processcreds/provider.go
- ecs_helper/vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- ecs_helper/vendor/github.com/aws/aws-sdk-go/aws/version.go
- ecs_helper/vendor/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/unmarshal_error.go
- ecs_helper/vendor/github.com/aws/aws-sdk-go/service/ecs/api.go
- ecs_helper/vendor/github.com/aws/aws-sdk-go/service/sts/api.go
- ecs_helper/vendor/modules.txt
Upgrade golang.org/x/net to address [CVE-2022-41721](https://github.com/ministryofjustice/opg-digideps/security/dependabot/58)
> Upgrade golang.org/x/net

- .circleci/config.yml
Fix path to live and destroy env in circle
> attempt to fix the destroy path and path to live

- lambdas/functions/synchronisation/Dockerfile
Force ssl upgrade in docker image
> Update ssl in sync docker image

- .github/workflows/workflow-path-to-live.yml
Renaming various steps and making path to live failures post to dev channel
> DDPB-4623 minor naming fixes to path to live

- environment/s3_access_logs.tf
- environment/s3_bucket/variables.tf
further fix as this broke pipeline on our old s3-access-logs buckets
>  DDPB-4673b amend access log bucket permissions

- client/Dockerfile
Remove db client where it isn't needed.
> Remove postrges client in client container

- client/src/Controller/Report/DocumentController.php
- client/src/Service/File/Storage/FileUploadFailedException.php
- client/src/Service/File/Storage/S3Storage.php
- client/tests/phpunit/Service/File/S3FileUploaderTest.php
- client/tests/phpunit/Service/File/Storage/S3StorageTest.php
As a deputy user 
I want to have early feedback if my document upload is unsuccessful
So that I don't have to waste time logging back in and re-uploading 
Fixes DDPB-4461
> DDPB-4461 Handle errors when attempting to upload document to S3

- api/Dockerfile
- api/composer.json
- api/composer.lock
- client/Dockerfile
- client/composer.json
- client/composer.lock
- renovate.json
some info here saying constraints from renovate only apply to python currently: https://docs.renovatebot.com/configuration-options/#constraints
As such I have update the     "config": {
"sort-packages": true,
"platform": {
"php": "8.1.19"
}
This is as suggested here: https://github.com/renovatebot/renovate/issues/2355
> DDPB-4704 fix renovate using php 8.2

- environment/.terraform.lock.hcl
- environment/admin.tf
- environment/alarms.tf
- environment/ecs.tf
- environment/front.tf
- environment/lambda/.terraform.lock.hcl
- environment/lambda/iam.tf
- environment/lambda/main.tf
- environment/lambda/variables.tf
- environment/s3.tf
- environment/s3_access_logs.tf
- environment/synchronisation_lambda.tf
Make infra tfsec compliant part 1
Fixes DDPB-3661
Splitting this into multiple PRs under the same ticket number. Spent quite some time trying to work out the elasticache encryption with a private key and figure it should really go in it's own PR.
Also need a PR to get rid of the duplicate s3 access logs stuff as we just add the force delete flag in this PR.
As such this is part 1 or probably 3 or 4 PRs to fix all the tfsec warnings.
NA
> DDPB-3661 improve tfsec compliance

- client/assets/javascripts/__tests__/modules_new/SessionTimeoutDialog.test.js
- client/templates/Report/Report/overview.html.twig
Couple of minor adjustments.
- Button has behaviour that allowed it be spammed.
- Test occasionally broke on minor timestamp issue. 
Here's screenshot to show where it still breaks:
> fix flakey js test and missed double click button

- lambdas/functions/synchronisation/go.mod
- lambdas/functions/synchronisation/go.sum
Recreated with new branch name
> Upgrade here as well.

- docs/queries/QUERIES.md
- environment/insights_queries.tf
The first of a number of business queries 
Fixes DDPB-4717
First of a number of queries that members of our team can run (including product and delivery managers) to assist in working out the cause of real world issues. This current query shows failed sign ups.
NA
> DDPB-4717 add cloudwatch query

- shared/certificates.tf
Additional DNS for digideps environments that are covered by global protect
Fixes DDPB-4726
Part 1. Create the certs in shared. Another PR incoming to add the DNS in environment folder.
NA
> DDPB-4726 additional dns part 1

- environment/.terraform.lock.hcl
- environment/admin_elb.tf
- environment/certificate.tf
- environment/dns_public.tf
- environment/front_elb.tf
Add additional DNS records
Fixes DDPB-4726
Added certs and new domain in previous PRs. This just adds non prod domains. We don't do prod as the SG rules on prod mean it would be open to public and we don't want them having a different route in.
NA
> DDPB-4726 add new DNS records

- .github/workflows/scheduled-cycle-secrets.yml
add prod to cycle secrets
Fixes DDPB-4597
Had trialled the cycling for a week in non prod envs. Seems to be working fine with those envs so extending to prod
NA
> DDPB-4597 add prod to cycle secrets

- file-scanner/Dockerfile
- htmltopdf/Dockerfile
- htmltopdf/app.py
> fix a couple of sec vulns

- .github/workflows/scheduled-cycle-secrets.yml
> rotate secrets in prod

- .github/workflows/scheduled-cycle-secrets.yml
turn off rotation job until we work out why it's going wrong.
> turn off rotation job

- .pre-commit-config.yaml
Improve coverage
Fixes DDPB-3622
tried to add an action to check pre-commits in pipe but it was failing on terraform apply and not sure it's worth working out why at the moment. 
NA
> DDPB-3622 improve the pre-commit coverage

- environment/api_rds.tf
- environment/disaster_recovery.tf
- environment/modules/aurora/outputs.tf
- environment/modules/aurora/variables.tf
- environment/modules/disaster_recovery/ecs.tf
- environment/modules/disaster_recovery/kms.tf
- environment/modules/disaster_recovery/variables.tf
- environment/modules/lambda/outputs.tf
- environment/modules/lambda/variables.tf
- environment/modules/s3_bucket/main.tf
- environment/modules/s3_bucket/variables.tf
- environment/modules/security_group/outputs.tf
- environment/modules/security_group/variables.tf
- environment/modules/task/variables.tf
- shared/modules/environment_secrets/variables.tf
As per OPG guidance
Fixes DDPB-4762
Makes module inputs easier to understand. Added types and descriptions to everything.
NA
> DDPB-4762 add descriptions and types to module input and outputs

- .github/workflows/scheduled-cycle-secrets.yml
Activate rotation for prod
Fixes DDPB-4597
Had this running in all the other envs to check for any issues. Seems to be working well. Activating in prod.
NA
> DDPB-4597 activate rotation for prod

- environment/api_elasticache.tf
- environment/frontend_shared_elasticache.tf
Backup window was conflicting with maintenance window. Easiest to leave as the defaults
> DDPB-4789b use default backup window

- shared/slack_notify.tf
Previous version connected by default to default sg of vpc...
Fixes DDPB-4791
Using latest version so I can remove the SG rules that were put in the default group (probably for the purpose of this module)
NA
> DDPB-4791 update slack notify

- environment/alarms.tf
- environment/dashboard.tf
- environment/waf.tf
- shared/slack_notify.tf
Renames alarm resources to snake case as per the OPG TF guidance
> DDPB-4759 - make alarm resources snake case

- environment/alarms.tf
- environment/dashboard.tf
> Amend healthcheck logic

- .github/workflows/_run-terraform.yml
> DDPB-4794b fix rename of module since original start of PR

- .github/workflows/_slack-notification.yml
- .github/workflows/workflow-path-to-live.yml
- .github/workflows/workflow-pull-request-path.yml
- .gitignore
- client/Dockerfile
- htmltopdf/Dockerfile
- lambdas/functions/slack_lambda/app/ci_slack.py
- lambdas/functions/slack_lambda/app/slack.py
upgrade alpine package
also fix a couple of icons with new slack changes
> upgrade alpine package

- .github/workflows/workflow-path-to-live.yml
Add in missing build_web_resources job in path to live
> DDPB-4735b amend to path to live to handle the changes

- .github/workflows/_run-terraform.yml
- .github/workflows/_slack-notification.yml
- .github/workflows/scheduled-cycle-secrets.yml
- .github/workflows/workflow-pull-request-dependabot-app.yml
- .github/workflows/workflow-pull-request-dependabot-terraform.yml
- .github/workflows/workflow-pull-request-path.yml
- lambdas/functions/slack_lambda/app/github_actions.txt
- lambdas/functions/slack_lambda/app/slack.py
workflow improvements
Fixes DDPB-4820
Fixed the cycle job that broke in last PR and used actionlint to find some other variables that weren't used and didn't have any negative affect previously but were incorrectly set.
Also added better release path message and gave us back our rocket 🚀 
NA
> DDPB-4820 workflow improvements

- account/.terraform.lock.hcl
- account/dns_firewall.tf
Further refine firewall rules
Fixes DDPB-4814
There are some questions in the jira ticket that stop us from fully turning this on but I have refined the rules to re-analyse in a week or two and see if the issues I have noticed are resolved by this more exact set of rules.
NA
> DDPB-4814 refine dns firewall rules

- .github/workflows/_ecr-scanning.yml
- .github/workflows/scheduled-workspace-cleanup.yml
Fix the overnight cleanup workflow
> Cleanup workflow not functioning correctly

- terraform/account/lambda_slack.tf
- terraform/environment/scheduled_events_checks.tf
move the lambda permissions to account folder
> DDPB-4835b move the lambda permissions to account folder

- client/app/src/Command/DocumentSyncCommand.php
- client/app/tests/phpunit/Command/DocumentSyncCommandTest.php
- terraform/account/lambda_slack.tf
logic fixes for event schedules
> DDPB-4835b logic fixes for event schedules

- Makefile
- docker-compose.dev.yml
Some fixes for our local integration tests that were missed.
> fix the local integration tests

- terraform/account/elasticache.tf
> DDLS-69 fix snapshot window conflict

- terraform/account/secrets.tf
Part 1 is just creating the secret and populating it manually
> DDLS-54 add secret part 1

- client/app/src/Controller/Admin/Client/ReportController.php
- client/app/src/Controller/Report/ReportController.php
- client/app/src/Service/ReportSubmissionService.php
- client/app/templates/Admin/Client/Report/new_checklist.html.twig
- client/app/templates/Admin/Client/Report/partials/_new_money-in-and-out.html.twig
- client/app/templates/Admin/Client/Report/partials/_new_money-summaries.html.twig
- client/app/templates/Report/Formatted/Accounts/_new_money_in_out.html.twig
- client/app/templates/Report/Formatted/Accounts/_new_money_in_out_short.html.twig
- client/app/templates/Report/Formatted/new_formatted_body.html.twig
- client/app/templates/Report/Formatted/new_formatted_standalone.html.twig
- client/app/templates/Report/Report/_new_pdf_download_link.html.twig
- client/app/templates/Report/Report/new_review.html.twig
Fixes DDLS-8 & DDLS-16
This change is for creating a new review page, new PDF & new Admin Checklist page for the enhanced Money In / Money Out questions which gives the option to decide if money has been put in / out or not by the deputy on behalf of the client. As part of the changes, new temporary routes and templates have been created so that they can be tested in isolation without impacting the existing system flow.
The Behat tests are planned to be updated during the wiring of all the changes together ([DDPB-4811](https://opgtransform.atlassian.net/browse/DDPB-4811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ) & …
> DDLS-8 & DDLS-16 - Checklist & PDF changes for No Money In & Out

- api/app/tests/Behat/bootstrap/v2/ReportSectionNavigation/ReportSectionNavigationTrait.php
- sync/Dockerfile
Unblocks failing Sync container build
Fixes DDLS-91
> DDLS-91 - Pin Alpine version in Sync

- docs/TESTING.md
Documentation for tests in phpstorm
> DDLS-98 add IDE unit testing process

- .github/workflows/_run-terraform.yml
- .github/workflows/workflow-path-to-live.yml
- .github/workflows/workflow-pull-request-path.yml
Use some of the nicer shared components from our ministryofjustice repo
Fixes DDLS-107
There are a few shared components that either replace or enhance some existing workflow functionality. The 3 that I am using here are:
versioning (use semver and have releases)
workspace manager (less clunky than doing it manually)
tf version (hides the clunky logic)
NA
> DDLS-107 update the ga workflows to use more shared components

- .github/workflows/workflow-path-to-live.yml
- .github/workflows/workflow-pull-request-path.yml
- terraform/account/outputs.tf
- terraform/environment/.terraform.lock.hcl
Add the output to outer folder in account to fix the failure on the environment plan. 
Also made default bump a minor
> DDLS-117b update the output from shared state

- .pre-commit-config.yaml
- terraform/account/region/cloud9.tf
shared roles for shared c9 owner
> DDLS-117d using shared roles for shared c9 owner

- client/app/templates/Report/Report/overview.html.twig
> DDLS-123: Remove dump function from report overview twig file

- terraform/environment/cloudwatch_global_alarms.tf
- terraform/environment/variables.tf
Missed out on this from last PR
> DDLS-116c fix for availability alert

- terraform/environment/provider.tf
- terraform/environment/region/cloudwatch_alarms.tf
- terraform/environment/variables.tf
Don't alert us of slow responses during csv upload
> DDLS-138 amend alarm to not spam us if csv is uploading

- .github/workflows/scheduled-cycle-secrets.yml
- .github/workflows/scheduled-update-training-environment.yml
- .github/workflows/scheduled-workspace-cleanup.yml
- terraform/environment/region/cloudwatch_scheduled_events.tf
- terraform/environment/region/cloudwatch_scheduled_events_checks.tf
- terraform/environment/region/ecs_service_admin.tf
- terraform/environment/region/ecs_service_api.tf
- terraform/environment/region/modules/aurora/main.tf
- terraform/environment/region/variables.tf
> DDLS-45 - Changes scheduled jobs to prevent any conflicts and adds var to files to TF

- terraform/environment/region/cloudwatch_scheduled_events.tf
- terraform/environment/region/cloudwatch_scheduled_events_checks.tf
- terraform/environment/region/ecs_iam_api.tf
Permissions change
Fixes DDLS-45
Change permisisons
NA
> DDLS-45 add api permissions

- api/app/src/Command/ProcessLayCSVCommand.php
- api/app/src/Command/ProcessOrgCSVCommand.php
- api/app/src/v2/Registration/Uploader/LayDeputyshipUploader.php
- api/app/src/v2/Registration/Uploader/OrgDeputyshipUploader.php
- api/app/tests/Unit/Command/ProcessOrgCSVCommandTest.php
- api/app/tests/Unit/v2/Registration/Uploader/LayDeputyshipUploaderTest.php
> DDLS-45 - Processing Output adjustments

- .github/workflows/_slack-notification.yml
- .github/workflows/workflow-path-to-live.yml
Move notifications to oidc
Fixes DDLS-158
Move notifications to use oidc
NA
> DDLS-158 move notifications to oidc

- .github/workflows/_ecr-scanning.yml
- .github/workflows/_latest-deployed-image.yml
- .github/workflows/_lint-terraform.yml
- .github/workflows/_run-task.yml
- .github/workflows/_run-terraform.yml
- .github/workflows/_scale-services.yml
- .github/workflows/_slack-notification.yml
- .github/workflows/scheduled-update-training-environment.yml
- .github/workflows/scheduled-workspace-cleanup.yml
- .github/workflows/workflow-destroy-on-merge.yml
- .github/workflows/workflow-path-to-live.yml
- .github/workflows/workflow-pull-request-path.yml
- scripts/pipeline/ecrscan/ecr_scan_results.py
Move remaining GA functionality to use OIDC
Fixes DDLS-158
There might be some stragglers but in this PR, we move pretty much everything over to use OIDC.
NA
> Ddls 158 - Move remaining GA functionality to use OIDC

- .github/workflows/scheduled-workspace-cleanup.yml
Use the forked version for now
When we can, look at using the shared github action to install
> update workspace manager

- terraform/environment/region/cloudwatch_scheduled_business_checks.tf
> DDLS-164c change threshold as too lenient

- .github/workflows/workflow-path-to-live.yml
- .github/workflows/workflow-pull-request-path.yml
- client/docker/web/confd/templates/app.conf.tmpl
Make nginx config 403 non existent files to stop nginx [error] codes on non existent files and to protect us in case certain files are accidentally added to public folder.
Fixes DDLS-221
Tried a number of approaches with the regex like look forward patterns but couldn't get it to work consistently. The pattern I have here seems to work as expected.
See screenshots in the Jira ticket of effects
NA
> DDLS-221 deny access to all files except existing js files

- .github/workflows/_build-and-push.yml
- terraform/environment/region/ecr.tf
Fix for pipeline failure as we are now using a different tag
> DDLS-221b fix to dev tag

- terraform/environment/region/variables.tf
Last part to use the newly created role in org infra
Fixes DDLS-125
NA
NA
> DDLS-125b use different role for non prod cross acct backups

- .github/workflows/manual-spin-up-development.yml
- .github/workflows/scheduled-cycle-secrets.yml
- .github/workflows/scheduled-disaster-recovery-test.yml
- .github/workflows/scheduled-update-training-environment.yml
- .github/workflows/scheduled-workspace-cleanup.yml
- .github/workflows/workflow-path-to-live.yml
- .github/workflows/workflow-pull-request-path.yml
- lambdas/functions/slack_lambda/app/slack.py
fix some logic workflow issues around DDLS-238
> DDLS-238b fix some logic workflow issues around DDLS-238

- .github/workflows/scheduled-disaster-recovery-test.yml
- orchestration/sleep_mode/main.go
- terraform/environment/region/cloudwatch_scheduled_events.tf
- terraform/environment/region/ecs_task_resilience_tests.tf
Various fixes to pipeline bits that were hard to test end to end.
- Fix a typo on DR testing job
- Fix a permissions issue that didn't appear during my test runs of this that was stopping the execution of resilience testing job.
- Change of times as UTC 8am is actually 9am..
- Make environment selection more specific
> Various small fixes for scheduled new jobs

- api/app/config/bundles.php
- api/app/src/DataFixtures/AdminUserFixtures.php
- api/app/src/DataFixtures/LayUserFixtures.php
- api/app/src/DataFixtures/PAUserFixtures.php
- api/app/src/DataFixtures/ProfUserFixtures.php
- api/app/src/DataFixtures/UserPasswordFixtures.php
- client/app/config/bundles.php
- client/app/config/packages/local/web_profiler.yml
Fix up for some missed local functionality
> DDLS-198b fix up some missing local functionality

- terraform/environment/terraform.tfvars.json
To merge in once the updates have applied without issue on preprod during maintenance period. Did plan against prod locally. Only updates the DB:
> DDLS-250 update prd minor version

- disaster-recovery/backup/Dockerfile
- docker-compose.commands.yml
- orchestration/restore.sh
Fix a couple of new bugs with path to live.
> DDLS-284 fix path to live

- api/app/src/Controller/PreRegistrationController.php
- api/app/src/Service/UserRegistrationService.php
- api/app/tests/Unit/Controller/PreRegistrationControllerTest.php
- api/app/tests/Unit/Service/UserRegistrationServiceTest.php
We had logic to check for an existing client with the same case number.
This was then used to prevent the same deputy from signing up twice.
It was also then used to prevent other deputies on the order from signing up, after another deputy had already signed-up.
However, this check did not properly account for case numbers with the letter 'T'. This meant that a user could type in an uppercase 'T', which would not be matched with any case numbers on our system as we store case numbers with a lowercase 't'.
Fixes DDLS-287
Used an existing method that exists in the client repo that lowers both the retrieved values from the database and the search term. This also fits the requirement of returning a single result or null.
Added additional api tests for the affected classes, making sure to …
> DDLS-287: Stop deputies with the a case numbers with a letter 'T' from signing up multiple times.

- client/app/src/Service/ParameterStoreService.php
- local-resources/localstack/localstack-init.sh
- terraform/environment/region/ecs_iam_api.tf
- terraform/environment/region/ssm_parameters.tf
Fixes DDLS-292
I followed the same approach as previous tickets DDPB 4030 and DDPB 4038
> DDLS-292 Added feature flag for multi accounts epic

- api/app/src/Controller/Report/ReportSubmissionController.php
- api/app/src/Repository/ReportSubmissionRepository.php
- api/app/tests/Unit/Entity/Repository/ReportSubmissionRepositoryTest.php
- api/docker/app/Dockerfile
- file-scanner/Dockerfile
Reverts ministryofjustice/opg-digideps#1642
> Revert "DDLS-296 improve performance of DAT download"

- api/app/src/Repository/UserRepository.php
- api/app/src/Service/UserService.php
- client/app/src/Controller/Admin/OrganisationController.php
- terraform/environment/region/cloudwatch_scheduled_events.tf
- terraform/environment/region/cloudwatch_scheduled_events_checks.tf
- Adds additional logging around org user creation
- Bug fix that stops Named prof deputies from creating Org users 
- Disables the User Zero Activity job, until we have had chance to discuss next steps. This is due to a bug that has come to light due to change in DB schema.
DDLS-331
> DDLS-331 - Adds logging for adding new org users.

- orchestration/anonymisation/processing/sql/3_org_email_identifers.sql
Stop non unique entries into email of dd_user
> DDLS-357d preprod anon process improvements

- .github/workflows/_lint-terraform.yml
- .github/workflows/scheduled-restore-anon-preprod.yml
- terraform/account/region/dynamodb.tf
- terraform/environment/region/ecs_iam_admin.tf
- terraform/environment/region/ecs_iam_execution.tf
- terraform/environment/region/ecs_iam_front.tf
- terraform/environment/region/ecs_iam_integration_tests.tf
- terraform/environment/region/ecs_iam_performance_data.tf
- terraform/environment/region/ecs_iam_shared.tf
- terraform/environment/region/ecs_service_admin_sg.tf
- terraform/environment/region/ecs_service_front_sg.tf
- terraform/environment/region/ecs_service_mock_sirius_sg.tf
- terraform/environment/region/ecs_service_scan_sg.tf
- terraform/environment/region/ecs_service_sirius_files_sync.tf
- terraform/environment/region/ecs_task_check_csv_upload.tf
- terraform/environment/region/ecs_task_integration_tests.tf
- terraform/environment/region/ecs_task_resilience_tests.tf
- terraform/environment/region/ecs_task_sleep_mode.tf
- terraform/environment/region/ecs_task_smoke_tests.tf
- terraform/environment/region/fault_injections_simulator_iam.tf
- terraform/environment/region/modules/disaster_recovery/ecs.tf
- terraform/environment/region/modules/disaster_recovery/ecs_sg.tf
- terraform/environment/region/s3_bucket.tf
- terraform/environment/region/s3_iam_replication.tf
> DDLS-323 add trivy infra scanner to pipeline

- api/app/tests/Behat/run-tests-parallel.sh
- api/app/tests/Behat/run-tests.sh
> BAU increase build maxtime on integration env

- orchestration/restore.sh
Fix for preprod overnight restore job
> DDLS-357 drop audit schema for preprod restore

- terraform/account/region/secrets.tf
Encrypt secrets with CMK
Fixes DDLS-392
Part three of three to add CMK to our secrets. Previously we added the decrypt permissions and the key and now we apply the key to the secrets.
NA
> DDLS-392 add encryption to secrets

- terraform/account/region/kms_service_s3.tf
- terraform/account/region/secrets.tf
Add s3 kms encryption
Fixes DDLS-398
Part 1 of 3. Add the key before we encrypt the buckets.
NA
> DDLS-398 add s3 kms encryption

- terraform/account/region/elasticache.tf
Reverts ministryofjustice/opg-digideps#1737
> Partial Revert of "DDLS-408 add dynamodb kms key part 1 of 2"

- terraform/environment/region/variables.tf
> update version of allow list

- .github/workflows/scheduled-restore-anon-preprod.yml
Turn of preprod restore and anon
> turn off preprod restore

- terraform/environment/region/cloudwatch_scheduled_events.tf
- terraform/environment/region/cloudwatch_scheduled_events_checks.tf
> turn off zero activity

- terraform/account/.envrc
- terraform/account/provider.tf
- terraform/account/versions.tf
- terraform/environment/.envrc
- terraform/environment/provider.tf
- terraform/environment/region/variables.tf
- terraform/environment/versions.tf
Upgrade TF and fix deprecation
Fixes DDLS-415
NA
NA
> DDLS-415 fix role syntax in terraform due to deprecation

- terraform/account/region/elasticache.tf
- terraform/account/region/s3_replication.tf
- terraform/environment/region/ecs_service_admin_sg.tf
- terraform/environment/region/ecs_service_api_sg.tf
- terraform/environment/region/ecs_service_front_sg.tf
- terraform/environment/region/elasticache_sg.tf
Last but one ticketbefore we can put in the trivy config scanner into our pipeline!
Fixes DDLS-323
Because of the shared nature of the SGs for redis, I'm having to add new groups then I'll do a follow up to delete the old groups. Was the easiest way I could think to add the description which is destructive to the groups without down time.
NA
> DDLS-323 finalise last bits of trivy config fixes

- terraform/account/region/elasticache.tf
- terraform/environment/region/ecs_service_admin_sg.tf
- terraform/environment/region/ecs_service_api_sg.tf
- terraform/environment/region/ecs_service_front_sg.tf
- terraform/environment/region/elasticache_sg.tf
Second to last PR on this ticket to get all the trivy config fixes done
Fixes DDLS-323
Remove all the bits using the original SG. We can then finally remove the original SGs.
NA
> DDLS-323 remove existing cache sg dependencies

- README.md
- terraform/account/provider.tf
- terraform/environment/provider.tf
PR to change the state file names
Fixes DDLS-434
As part of minimising access to state files
NA
> DDLS-434b change state files around

- api/app/composer.json
- api/app/composer.lock
- api/app/src/DataFixtures/AbstractDataFixture.php
- api/app/src/DataFixtures/UserPasswordFixtures.php
Upgrading to latest 2.x version of doctrine. 
Fixes DDLS-469
Needs doing anyway and but it's mainly to help rule out issues with db upgrade that I'm looking at. I will look at upgrade to 3.x soon but that's not quite as simple from the last time I had a brief look at it.
NA
> DDLS-469 upgrade doctrine to latest v2

- .github/workflows/_build-and-push.yml
- client/app/templates/Ndr/Ndr/review.html.twig
Fix a display issue
Fixes DDLS-491
Now fixed:
NA
> DDLS-491 fix display issue on NDRs

- docs/DOCUMENT_AND_CHECKLIST_SYNC.md
- terraform/environment/.envrc
- terraform/environment/region.tf
- terraform/environment/region/variables.tf
- terraform/environment/variables.tf
Add readme for the sync process
Fixes DDLS-471
Added readme around the process and fixed a little annoying issue with a shared state ownership
NA
> DDLS-471 add readme around do sync process

- terraform/account/region/elasticache.tf
Cleanup the old cluster
Fixes DDLS-467
Clean it up as not using the old one any more.
NA
> DDLS-467c cleanup of old redis cluster

- .github/workflows/_build-and-push.yml
Temporary fix for development build
> DDLS-498b fix the development build tag

- terraform/environment/region/cloudwatch_scheduled_events.tf
Switch off the dry run flag which prevents multi-client processing from changing the database.
Addendum to DDLS-432
-
-
> Apply multi-client changes to db

- api/app/src/Controller/SatisfactionController.php
- api/app/src/EventListener/DoctrineListener.php
- api/app/src/Repository/ClientRepository.php
- api/app/src/Repository/DeputyRepository.php
- api/app/src/Repository/DocumentRepository.php
- api/app/src/Repository/OrganisationRepository.php
- api/app/src/Repository/PreRegistrationRepository.php
- api/app/src/Repository/ReportRepository.php
- api/app/src/Repository/UserRepository.php
- Remove unused methods
- Fix some references that were leading to IDE misreporting usage
Remove unused code to make maintenance slightly easier
IDE displaying usage information, and find in files to double check for calls
> Remove unused methods from api repositories

- client/resources/package-lock.json
Fixes DDLS-518
`npm update` in the client/resources/ directory.
n/a
> DDLS-518 npm update to fix audit issue during build-app

- .github/workflows/_phpstan-api.yml
- .github/workflows/workflow-pull-request-path.yml
- Makefile
- api/app/phpstan-baseline.neon
- api/app/phpstan.neon
- api/docker/app/Dockerfile
- docker-compose.override.yml
> PoC for PHPStan in CI

- api/app/phpstan-baseline.neon
- api/app/src/Service/Audit/AuditEvents.php
- api/app/src/Service/Audit/AwsAuditLogHandler.php
- api/app/src/Service/Auth/AuthService.php
- api/app/src/Service/BruteForce/AttemptsInTimeChecker.php
- api/app/src/Service/BruteForce/AttemptsIncrementalWaitingChecker.php
- api/app/src/Service/Client/TokenStorage/RedisStorage.php
- api/app/src/Service/File/Storage/S3Storage.php
- api/app/src/Service/Formatter/RestFormatter.php
- api/app/src/Service/JWT/JWTService.php
- api/app/src/Service/OrgService.php
- api/app/src/Service/ParameterStoreService.php
- api/app/src/Service/PreRegistrationVerificationService.php
- api/app/src/Service/ReportService.php
- api/app/src/Service/ReportStatusService.php
- api/app/src/Service/RestHandler/OrganisationRestHandler.php
- api/app/src/Service/RestHandler/Report/DeputyCostsEstimateReportUpdateHandler.php
- api/app/src/Service/RestHandler/Report/DeputyCostsReportUpdateHandler.php
- api/app/src/Service/RestHandler/Report/PaFeesExpensesReportUpdateHandler.php
- api/app/src/Service/SecretManagerService.php
- api/app/src/Service/Stats/Query/Query.php
- api/app/src/Service/Stats/QueryFactory.php
- api/app/src/Service/UserRegistrationService.php
- api/app/src/Service/UserService.php
Apply Rector ClassPropertyAssignToConstructorPromotionRector and ReadOnlyPropertyRector rules
Automatically applying this and committing in batches is a lot quicker and less labor intensive than manually updating the code as it is changed
Use Rector
> Constructor property promotion Api App\Service

- client/app/templates/Admin/Index/viewUser.html.twig
- client/app/translations/admin.en.yml
> DDLS-509 Include deputy UID on admin view user page

- orchestration/restore.sh
Preprod restore failing on new
> fix broken preprod

- terraform/environment/region/cloudwatch_scheduled_events.tf
- terraform/environment/region/cloudwatch_scheduled_events_checks.tf
- terraform/environment/region/variables.tf
This is to get the deputyships CSV processing job to run correctly.
> Use correct name for deputyships CSV exported from Sirius

- client/app/phpstan-baseline.neon
- client/app/src/Validator/Constraints/ChainValidator.php
- client/app/src/Validator/Constraints/ClientBenefitsCheck/ClientBenefitsCheckValidator.php
- client/app/src/Validator/Constraints/ClientBenefitsCheck/MoneyReceivedOnClientsBehalfValidator.php
- client/app/src/Validator/Constraints/CommonPasswordValidator.php
- client/app/src/Validator/Constraints/DUserPasswordValidator.php
- client/app/src/Validator/Constraints/EmailSameDomainValidator.php
- client/app/src/Validator/Constraints/EndDateNotBeforeStartDateValidator.php
- client/app/src/Validator/Constraints/EndDateNotGreaterThanFifteenMonthsValidator.php
- client/app/src/Validator/Constraints/ProfDeputyCostsEstimate/CostBreakdownNotGreaterThanTotalValidator.php
- client/app/src/Validator/Constraints/YearMustBeFourDigitsAndValidValidator.php
- client/app/src/Validator/Constraints/YesNoNaValidator.php
This removes some static analysis errors that are reported after the upgrade to symfony 6 (as well as some current ones)
Contributes to DDLS-572
> DDLS-572 Update signature of ConstraintValidator->validate implementations

- api/app/composer.json
- api/app/composer.lock
- api/app/src/Security/HeaderTokenAuthenticator.php
- api/app/src/Security/RegistrationTokenAuthenticator.php
Upgrade to v6
- symfony/security-http
- symfony/http-client
- symfony/var-dumper
Fixes DDLS-571
> DDLS-571 API Symfony 6 remaining upgrades

- client/app/phpstan-baseline.neon
- client/app/src/Entity/User.php
- client/app/src/EventListener/AuthenticationHandler.php
- client/app/src/Security/UserProvider.php
- client/app/src/Service/DeputyProvider.php
- client/app/src/Service/SiriusApiErrorTranslator.php
- client/app/src/TestHelpers/UserHelpers.php
- client/app/tests/phpunit/Service/DeputyProviderTest.php
- client/app/tests/phpunit/Service/Mailer/MailFactoryTest.php
- client/app/tests/phpunit/Service/RequestIdLoggerProcessorTest.php
Update some method signatures for symfony v6 compatibility
Contributes to DDLS-571
> DDLS-571 Preperation for Client app symfony v6

- api/app/composer.lock
- api/app/src/Controller/Report/MoneyTransactionController.php
- Upgrade packages with current composer.json
- Change MoneyTransactionController->deleteMoneyTransactionAction to avoid Entity detached exception with newer Doctrine
Update existing API packages to latest available ahead of PHP 8.2 upgrade to isolate any issues that are unrelated to the change in PHP version
Contributes to DDLS-591
> DDLS-591 Update API lockfile

- scripts/custom_sql_query/run_custom_query.py
Small fix around prod environment
> DDLS-597 environment format changes

- api/app/phpstan-baseline.neon
- api/app/src/DataFixtures/LayUserFixtures.php
- api/app/src/Entity/CourtOrder.php
- api/app/src/Entity/CourtOrderDeputy.php
- api/app/src/Entity/Deputy.php
- api/app/src/Entity/Report/Report.php
- api/app/src/Entity/StagingDeputyship.php
- api/app/src/Entity/User.php
- api/app/src/Migrations/Version294.php
- api/app/src/Repository/CourtOrderRepository.php
- api/app/src/TestHelpers/ReportTestHelper.php
- api/app/src/v2/Controller/ControllerTrait.php
- api/app/src/v2/Controller/CourtOrderController.php
- api/app/src/v2/Service/CourtOrderService.php
- api/app/tests/Behat/bootstrap/v2/Helpers/FixtureHelper.php
- api/app/tests/Integration/Controller/AbstractTestController.php
- api/app/tests/Integration/Controller/JsonHttpTestClient.php
- api/app/tests/Integration/Fixtures.php
- api/app/tests/Integration/v2/Controller/CourtOrderControllerTest.php
> DDLS-577 Court order controller

- api/app/src/Command/IngestDeputyshipsCSVCommand.php
- api/app/src/Entity/StagingDeputyship.php
- api/app/src/Migrations/Version295.php
> DDLS-629 Deputyship ingestion fixes

- .github/workflows/_integration-tests-api.yml
- Makefile
- api/app/scripts/api_integration_test.sh
- api/app/tests/coverage/.gitignore
- docker-compose.override.yml
- docker-compose.yml
> API Integration test config

- api/app/composer.json
- api/app/composer.lock
- api/docker/app/Dockerfile
Fixing some more API side vulnerabilities
> DDLS-619 fix api side vulnerabilities

- api/docker/app/Dockerfile
- client/docker/app/Dockerfile
Version here: https://hub.docker.com/layers/library/php/8.3.21-fpm-alpine3.20/images/sha256-3419d067f7e4d10f91e0b72167591e118ff50772aed1b8a60c422f8a9c6db354
> Updated version of Alpine to latest.

- client/app/config/services_dev.yml
The broken paths are preventing Symfony profiler bar from loading
> Fix paths of services

- .github/workflows/_build-and-push.yml
> Added SBOM to the pipeline

- api/app/phpstan-baseline.neon
- api/app/src/Service/ReportService.php
- api/app/tests/Unit/Service/ReportServiceTest.php
- client/app/templates/Report/Report/overview.html.twig
> DDLS-573 Don’t allow report submission until after the report end date

- .github/workflows/_test-js.yml
- Makefile
- client/docker/resources/Dockerfile
- docker-compose.override.yml
- docker-compose.yml
- Rename make commands
- Use make commands in CI to align CI and local dev
- Remove lint from Docker container build
- Add volume mounts for local dev
> Align local and CI JS commands

- Makefile
- api/app/phpstan-baseline.neon
- api/app/src/Controller/UserController.php
- api/app/src/TestHelpers/UserTestHelper.php
- api/app/tests/Behat/bootstrap/v2/Common/AuthTrait.php
- api/app/tests/Behat/bootstrap/v2/Common/BaseFeatureContext.php
- api/app/tests/Behat/bootstrap/v2/Helpers/FixtureHelper.php
- api/app/tests/Behat/features-v2/acl/login/login.feature
- api/app/tests/Integration/Controller/ClientControllerTest.php
- api/app/tests/Integration/Controller/UserControllerTest.php
- client/app/phpstan-baseline.neon
- client/app/scripts/client-unit-tests.sh
- client/app/src/Controller/Report/ReportController.php
- client/app/src/Service/Client/Internal/UserApi.php
- client/app/templates/Layouts/application.html.twig
- client/app/templates/Macros/macros.html.twig
- client/app/tests/phpunit/Service/Client/Internal/UserApiTest.php
> DDLS-671 Fixes for returnPrimaryEmail bug

- .gitignore
- terraform/environment/terraform.tfvars.json
Upgrade DB in prod
Fixes DDLS-679
Upgrade rolled out fine in preprod. Let's do prod now.
Also added some more bits to the gitignore file that were missing.
NA
> DDLS-679b minor DB upgrade for prod

- .github/workflows/_cycle-secrets.yml
- .github/workflows/scheduled-cycle-app-secrets.yml
> DDLS-678 fix for cycle secrets

- lambdas/functions/monitor_notify_lambda/app/message_sending/send.py
- lambdas/functions/monitor_notify_lambda/app/monitor_notify.py
- terraform/account/region/sns.tf
Turn on breakglass alarm
Fixes DDLS-668
Notification goes to SNS which will then be forwarded on to slack. I've put a filter as we don't want all the CIS alerts in the main channel.
NA
> DDLS-668 turn on breakglass alarm

- api/app/tests/Behat/bootstrap/v2/Registration/SelfRegistrationTrait.php
- client/app/src/Controller/Report/ReportController.php
- client/app/translations/co-deputy.en.yml
- client/app/translations/common.en.yml
- client/app/translations/email-template.en.yml
- client/app/translations/register.en.yml
Update validation and flash messages with new OPG telephone number
Fixes DDLS-763
> DDLS-763: Amend OPG telephone number

- terraform/account/region/dns_firewall.tf
- terraform/account/region/kms_service_anomoly.tf
- terraform/account/region/s3_replication.tf
- terraform/account/region/vpc_flow_logs.tf
- terraform/account/region/waf.tf
Issues with the policy for anomoly detection fixed in the PR
Fixes DDLS-89
NA
NA
> DDLS-89b fix erroneous config for anomoly detection

- terraform/environment/.terraform.lock.hcl
- terraform/environment/region/cloudwatch_logging.tf
- terraform/environment/region/rds.tf
- terraform/environment/versions.tf
Second part of adding anomaly detectors to the relevant logs. 
Fixes DDLS-89
Environment side change just needed an upgrade to some tf providers to work.
NA
> DDLS-89b add anomaly detection

- api/app/config/packages/doctrine.yml
- terraform/environment/terraform.tfvars.json
Prod upgrade to postgres 14
Fixes DDLS-399
NA
NA
> DDLS-399d upgrade prod DB to 14

- api/app/scripts/readonly_user_setup/_0_readonly_user_create.sql
- docker-compose.yml
> Added RO PG 14 Permissions to RO User.

- api/app/src/Entity/CourtOrderDeputy.php
- api/app/src/Entity/Deputy.php
- api/app/src/Migrations/Version305.php
- api/app/tests/Integration/ApiBaseTestCase.php
- api/app/tests/Integration/Controller/UserControllerTest.php
- api/app/tests/Integration/Entity/DeputyTest.php
- api/app/tests/Integration/Entity/Repository/ReportRepositoryTest.php
- api/app/tests/Integration/Entity/UserTest.php
- api/app/tests/Unit/Repository/ReportRepositoryTest.php
See ticket for details.
~~Also started cleaning up the RestClient and RestClientInterface.~~ I started doing this, then backed it out when it caused havoc.
Fixes DDLS-860
See ticket
See ticket
> DDLS-860 Cascade deputy delete to court_order_deputy

- disaster-recovery/backup/cross_account_backup.py
Fix cross account backup
Fixes DDLS-880
The issue was because of our sorting, the preupgrade image was being selected every night.
As this is a standard snapshot we get after backups, have decided to just exclude it. Also refactored the script a bit.
NA
> DDLS-880 fix cross account backup job

- api/app/scripts/api_integration_test.sh
- docker-compose.yml
- local-resources/localstack/Dockerfile
- local-resources/localstack/init/init.sh
- local-resources/localstack/wait/healthcheck.sh
To fix CI builds. This is a big shift (from 0.14.5 to 4.6.0) but the APIs are pretty stable and it didn't require many changes. This also only affects local dev, as it doesn't touch any live code.
Fixes DDLS-887
> DDLS-887 Upgrade localstack to latest version

- api/app/src/Entity/Deputy.php
- api/app/src/v2/Controller/CourtOrderController.php
- api/app/tests/Behat/bootstrap/v2/CourtOrder/CourtOrderTrait.php
- api/app/tests/Behat/bootstrap/v2/Helpers/FixtureHelper.php
- api/app/tests/Behat/features-v2/court-order/court-order-page.feature
- client/app/src/Controller/CourtOrderController.php
- client/app/src/Entity/CourtOrder.php
- client/app/src/Entity/Deputy.php
- client/app/templates/CourtOrder/index.html.twig
- client/app/templates/Ndr/Ndr/index.html.twig
- client/app/templates/Report/Report/_codeputies.html.twig
- client/app/tests/phpunit/Entity/CourtOrderTest.php
> DDLS-852 Court order co-deputy display

- api/app/phpstan-baseline.neon
- api/app/src/Controller/ClientController.php
- api/app/src/Controller/CoDeputyController.php
- api/app/src/Controller/DeputyController.php
- api/app/src/Controller/HealthController.php
- api/app/src/Controller/NoteController.php
- api/app/src/Controller/PreRegistrationController.php
- api/app/src/Controller/Report/ContactController.php
- api/app/src/Controller/Report/ExpenseController.php
- api/app/src/Controller/SatisfactionController.php
- api/app/src/Controller/SelfRegisterController.php
- api/app/src/Controller/SettingController.php
- api/app/src/Controller/StatsController.php
- api/app/src/Controller/UserController.php
- api/app/src/Controller/UserResearchController.php
Move the remaining v1 controllers to Symfony core Security as Sensio is abandoned and will receive no further updates
Contributes to [DDLS-862](https://opgtransform.atlassian.net/browse/DDLS-862)
[DDLS-862]: https://opgtransform.atlassian.net/browse/DDLS-862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DDLS-862 Move remaining v1 controllers to Symfony core Security

- api/app/src/Model/DeputyshipProcessingLookupCache.php
- api/app/src/Repository/ClientRepository.php
- api/app/src/v2/Registration/DeputyshipProcessing/CourtOrderAndDeputyCandidatesFactory.php
- api/app/src/v2/Registration/DeputyshipProcessing/CourtOrderReportCandidatesFactory.php
- api/app/tests/Unit/Model/DeputyshipProcessingLookupCacheTest.php
- api/app/tests/Unit/v2/Registration/DeputyshipProcessing/CourtOrderAndDeputyCandidatesFactoryTest.php
> DDLS-899 Use lowercased case numbers when matching client during ingest

- api/app/phpstan-baseline.neon
- api/app/src/Entity/Ndr/Ndr.php
- api/app/src/Entity/Report/Report.php
- api/app/src/Entity/Report/Traits/AssetTrait.php
- api/app/src/Entity/Report/Traits/BankAccountTrait.php
- api/app/src/Entity/Report/Traits/StatusTrait.php
- api/app/src/Entity/ReportInterface.php
Improve type safety and maintainablility
> Declare types in API ReportInterface

- api/app/scripts/api_integration_test.sh
- api/app/src/Command/ProcessLayCSVCommand.php
- api/app/src/Service/DeputyCaseService.php
- api/app/src/Service/LayRegistrationService.php
- api/app/tests/Integration/Fixtures.php
- api/app/tests/Integration/Service/DeputyCaseServiceIntegrationTest.php
- api/app/tests/Integration/Service/LayRegistrationServiceIntegrationTest.php
- api/app/tests/Unit/Service/LayRegistrationServiceTest.php
- local-resources/local-load-balancer/certificates/certificates.md
> DDLS-961 Fix incorrect data persist, flush, and clear sequencing

- api/app/src/Command/ProcessLayCSVCommand.php
- api/app/src/Entity/Report/Report.php
- api/app/src/Service/LayRegistrationService.php
- api/app/tests/Unit/Service/LayRegistrationServiceTest.php
> DDLS-967 Fix post-processing errors causing lay ingest to fail

- client/docker/resources/Dockerfile
Use npm ci instead of install for extra safety
> fix npm ci

- api/app/tests/Behat/bootstrap/v2/Reporting/Sections/DebtsSectionTrait.php
- api/app/tests/Behat/features-v2/reporting/sections/debts/debts.feature
- api/app/tests/Behat/features-v2/reporting/sections/debts/debts.ndr.feature
- client/app/templates/Ndr/Debt/edit.html.twig
- client/app/templates/Report/Debt/edit.html.twig
> DDLS-937 Show more details field with error message

- client/app/composer.json
- client/app/composer.lock
- client/app/src/Entity/Traits/IsSoftDeleteableEntity.php
- client/app/src/Service/ApiCollector.php
- client/app/src/Service/ChecklistSyncService.php
- client/app/src/Service/Client/Internal/StatsApi.php
- client/app/src/Service/Client/RestClient.php
- client/app/src/Service/CssClassCollector.php
- client/docker/app/Dockerfile
Move the Client app onto a fully supported version of PHP
Fixes DDLS-DDLS-684
> DDLS-684 Upgrade client to PHP 8.4
